### ISSUE TITLE
Support JCasC

### ISSUE THREAD

**Issue by darxriggs** [jfrog/jenkins-artifactory-plugin#107]
Currently the plugin doesn't support [JCasC](https://jenkins.io/projects/jcasc/).

When an Artifactory server is configured in the global config, the JCasC export fails as follows
```
unclassified:
  artifactoryBuilder:
    artifactoryServers: "FAILED TO EXPORT org.jfrog.hudson.ArtifactoryBuilder$DescriptorImpl#artifactoryServers:\
      \ \nio.jenkins.plugins.casc.ConfiguratorException: Can't read attribute 'serverId'\
      \ from org.jfrog.hudson.ArtifactoryServer@12d71b12\n\tat io.jenkins.plugins.casc.Attribute._getValue(Attribute.java:252)\n\
      \tat io.jenkins.plugins.casc.Attribute.getValue(Attribute.java:174)\n\tat io.jenkins.plugins.casc.impl.configurators.DataBoundConfigurator.describe(DataBoundConfigurator.java:236)\n\
      \tat io.jenkins.plugins.casc.Attribute.describe(Attribute.java:192)\n\tat io.jenkins.plugins.casc.BaseConfigurator.compare(BaseConfigurator.java:387)\n\
      \tat io.jenkins.plugins.casc.impl.configurators.DescriptorConfigurator.describe(DescriptorConfigurator.java:61)\n\
      \tat io.jenkins.plugins.casc.impl.configurators.GlobalConfigurationCategoryConfigurator.describe(GlobalConfigurationCategoryConfigurator.java:105)\n\
      \tat io.jenkins.plugins.casc.impl.configurators.GlobalConfigurationCategoryConfigurator.lambda$describe$6(GlobalConfigurationCategoryConfigurator.java:98)\n\
      \tat java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)\n\
      \tat java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)\n\
      \tat java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)\n\
      \tat java.util.Iterator.forEachRemaining(Iterator.java:116)\n\tat java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)\n\
      \tat java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)\n\
      \tat java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)\n\
      \tat java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)\n\
      \tat java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)\n\
      \tat java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)\n\
      \tat java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)\n\
      \tat io.jenkins.plugins.casc.impl.configurators.GlobalConfigurationCategoryConfigurator.describe(GlobalConfigurationCategoryConfigurator.java:98)\n\
      \tat io.jenkins.plugins.casc.impl.configurators.GlobalConfigurationCategoryConfigurator.describe(GlobalConfigurationCategoryConfigurator.java:32)\n\
      \tat io.jenkins.plugins.casc.ConfigurationAsCode.export(ConfigurationAsCode.java:411)\n\
      \tat io.jenkins.plugins.casc.ConfigurationAsCode.doExport(ConfigurationAsCode.java:401)\n\
      \tat java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:627)\n\
      \tat org.kohsuke.stapler.Function$MethodFunction.invoke(Function.java:343)\n\
      \tat org.kohsuke.stapler.interceptor.RequirePOST$Processor.invoke(RequirePOST.java:77)\n\
      \tat org.kohsuke.stapler.PreInvokeInterceptedFunction.invoke(PreInvokeInterceptedFunction.java:26)\n\
      \tat org.kohsuke.stapler.Function.bindAndInvoke(Function.java:184)\n\tat org.kohsuke.stapler.Function.bindAndInvokeAndServeResponse(Function.java:117)\n\
      \tat org.kohsuke.stapler.MetaClass$1.doDispatch(MetaClass.java:130)\n\tat org.kohsuke.stapler.NameBasedDispatcher.dispatch(NameBasedDispatcher.java:58)\n\
      \tat org.kohsuke.stapler.Stapler.tryInvoke(Stapler.java:739)\n\tat org.kohsuke.stapler.Stapler.invoke(Stapler.java:870)\n\
      \tat org.kohsuke.stapler.MetaClass$10.dispatch(MetaClass.java:384)\n\tat org.kohsuke.stapler.Stapler.tryInvoke(Stapler.java:739)\n\
      \tat org.kohsuke.stapler.Stapler.invoke(Stapler.java:870)\n\tat org.kohsuke.stapler.Stapler.invoke(Stapler.java:668)\n\
      \tat org.kohsuke.stapler.Stapler.service(Stapler.java:238)\n\tat javax.servlet.http.HttpServlet.service(HttpServlet.java:790)\n\
      \tat org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:841)\n\
      \tat org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1650)\n\
      \tat hudson.util.PluginServletFilter$1.doFilter(PluginServletFilter.java:154)\n\
      \tat hudson.util.PluginServletFilter.doFilter(PluginServletFilter.java:157)\n\
      \tat org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1637)\n\
      \tat hudson.security.csrf.CrumbFilter.doFilter(CrumbFilter.java:64)\n\tat org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1637)\n\
      \tat hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:84)\n\
      \tat hudson.security.ChainedServletFilter.doFilter(ChainedServletFilter.java:90)\n\
      \tat hudson.security.HudsonFilter.doFilter(HudsonFilter.java:171)\n\tat org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1637)\n\
      \tat org.kohsuke.stapler.compression.CompressionFilter.doFilter(CompressionFilter.java:49)\n\
      \tat org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1637)\n\
      \tat hudson.util.CharacterEncodingFilter.doFilter(CharacterEncodingFilter.java:82)\n\
      \tat org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1637)\n\
      \tat org.kohsuke.stapler.DiagnosticThreadNameFilter.doFilter(DiagnosticThreadNameFilter.java:30)\n\
      \tat org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1637)\n\
      \tat org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:533)\n\
      \tat org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)\n\
      \tat org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:524)\n\
      \tat org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)\n\
      \tat org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:190)\n\
      \tat org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1595)\n\
      \tat org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:188)\n\
      \tat org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1253)\n\
      \tat org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:168)\n\
      \tat org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:473)\n\
      \tat org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1564)\n\
      \tat org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:166)\n\
      \tat org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1155)\n\
      \tat org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)\n\
      \tat org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:219)\n\
      \tat org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:126)\n\
      \tat org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)\n\
      \tat org.eclipse.jetty.server.Server.handle(Server.java:564)\n\tat org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:317)\n\
      \tat org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:251)\n\
      \tat org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:279)\n\
      \tat org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:110)\n\tat\
      \ org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:124)\n\tat\
      \ org.eclipse.jetty.util.thread.Invocable.invokePreferred(Invocable.java:128)\n\
      \tat org.eclipse.jetty.util.thread.Invocable$InvocableExecutor.invoke(Invocable.java:222)\n\
      \tat org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:294)\n\
      \tat org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:199)\n\
      \tat org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:672)\n\
      \tat org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:590)\n\
      \tat java.lang.Thread.run(Thread.java:748)\n"
```

**Comment by casz** [comment]
Also linked to: https://www.jfrog.com/jira/browse/HAP-1018

**Comment by casz** [comment]
wow, heaps of changes 😓

**Comment by jonbrohauge** [comment]
Using: 
Jenkins: 2.252
Artifactory plugin: 3.7.3 or 3.8.0

I read in a post that version 3.7.1 should have fixed this error, but I get it as well.

```
 artifactoryBuilder:
    artifactoryServers: |-
      FAILED TO EXPORT
      org.jfrog.hudson.ArtifactoryBuilder$DescriptorImpl#artifactoryServers: io.jenkins.plugins.casc.ConfiguratorException: Can't read attribute 'serverId' from org.jfrog.hudson.ArtifactoryServer@43f766dd
        at io.jenkins.plugins.casc.Attribute._getValue(Attribute.java:462)
        at io.jenkins.plugins.casc.Attribute.getValue(Attribute.java:236)
        at io.jenkins.plugins.casc.impl.configurators.DataBoundConfigurator.describe(DataBoundConfigurator.java:290)
        at io.jenkins.plugins.casc.Attribute._describe(Attribute.java:329)
        at io.jenkins.plugins.casc.Attribute.describe(Attribute.java:258)
        at io.jenkins.plugins.casc.Configurator.describe(Configurator.java:182)
        at io.jenkins.plugins.casc.impl.configurators.GlobalConfigurationCategoryConfigurator.describe(GlobalConfigurationCategoryConfigurator.java:115)
        at io.jenkins.plugins.casc.impl.configurators.GlobalConfigurationCategoryConfigurator.lambda$describe$3(GlobalConfigurationCategoryConfigurator.java:108)
        at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
        at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
        at java.util.Iterator.forEachRemaining(Iterator.java:116)
        at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
        at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
        at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:485)
        at io.jenkins.plugins.casc.impl.configurators.GlobalConfigurationCategoryConfigurator.describe(GlobalConfigurationCategoryConfigurator.java:108)
        at io.jenkins.plugins.casc.impl.configurators.GlobalConfigurationCategoryConfigurator.describe(GlobalConfigurationCategoryConfigurator.java:33)
```

**Comment by Or-Gabay** [comment]
@jonbrohauge, Artifactory plugin 3.8.0 supports JCasC.
Try to delete the old Artifactory plugin, restart Jenkins and install Artifactory plugin 3.8.0.

**Comment by jonbrohauge** [comment]
@Or-Gabay I have completely rebuilt my Jenkins from scratch with the new plugin.
However I'll try again after having deleted all known versions of the plugin in our jenkins-plugin-mirror

**Comment by jonbrohauge** [comment]
After purging all plugins, and builds on our mirror, and rebuilding everything for our Jenkins. It appears to work.
👍 for getting this fix in.

**Comment by Or-Gabay** [comment]
Thanks for the feedback @jonbrohauge!.
