### ISSUE TITLE
NPM Install debug mode for scripted pipeline 

### ISSUE THREAD

**Issue by fdolsky321** [jfrog/jenkins-artifactory-plugin#137]
Hello, I have some issue during installing dependencies by using Artifactory plugin (v. 3.2.2). Since during installing dependencies, its failing time to time, I would like to take a look at what package is causing the issue by using verbose mode for npm install (npm install -ddd). I tried this:
`def buildInfo = npmBuild.install args: '-ddd', path: npmPackageDirectory`

But this args parameter doesn't work for me, I can't see any detailed info there. Btw. the error, which I get, when installing dependencies is running, there is:
```
[Pipeline] newBuildInfo
[Pipeline] artifactoryNpmInstall
process hasn't exited
[Pipeline] }
[Pipeline] // withEnv
[Pipeline] }
[Pipeline] // ansiColor
[Pipeline] }
[Pipeline] // stage
[Pipeline] }
[Pipeline] // node
[Pipeline] End of Pipeline
[Bitbucket] Notifying commit build result
[Bitbucket] Build result notified
java.lang.RuntimeException: npm build failed
	at org.jfrog.hudson.pipeline.common.executors.NpmInstallExecutor.execute(NpmInstallExecutor.java:59)
	at org.jfrog.hudson.pipeline.scripted.steps.NpmInstallStep$Execution.run(NpmInstallStep.java:64)
	at org.jfrog.hudson.pipeline.scripted.steps.NpmInstallStep$Execution.run(NpmInstallStep.java:39)
	at org.jenkinsci.plugins.workflow.steps.AbstractSynchronousNonBlockingStepExecution$1$1.call(AbstractSynchronousNonBlockingStepExecution.java:47)
	at hudson.security.ACL.impersonate(ACL.java:290)
	at org.jenkinsci.plugins.workflow.steps.AbstractSynchronousNonBlockingStepExecution$1.run(AbstractSynchronousNonBlockingStepExecution.java:44)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Finished: FAILURE
```

**Comment by fdolsky321** [comment]
btw. when I'm using npm install --verbose directly, works as expected. Would be really awesome to have this verbose functionality available for using install by your plugin.

**Comment by barbelity** [comment]
@fdolsky321,
We have committed [this fix](https://github.com/jfrog/build-info/commit/287ba11641280dd132edd6c59c009d8824065083), which outputs npm logs to the Jenkins build-log. It will be part of our next release of the plugin. In the meantime, [this snapshot version](https://oss.jfrog.org/oss-snapshot-local/org/jenkins-ci/plugins/artifactory/3.2.x-SNAPSHOT/artifactory-3.2.x-20190408.120931-22.hpi) of the plugin contains that commit.
If you do install it, please let us know if your issue is resolved.

**Comment by fdolsky321** [comment]
Thank you @barbelity for quick response, I tried in our staging instance and get different error. Btw. I expected some log even w/o using verbose mode as args, but nothing appeared, after putting verbose by `args: '-ddd'` I retrieved following issue:
```
Unrecognized token 'npm': was expecting 'null', 'true', 'false' or NaN
 at [Source: (String)"npm info it worked if it ends with ok
npm verb cli [ '/opt/jenkins/tools/jenkins.plugins.nodejs.tools.NodeJSInstallation/NodeJS_10/bin/node',
npm verb cli   '/opt/jenkins/tools/jenkins.plugins.nodejs.tools.NodeJSInstallation/NodeJS_10/bin/npm',
npm verb cli   'c',
npm verb cli   'ls',
npm verb cli   '--json',
npm verb cli   '-ddd' ]
npm info using npm@6.4.1
npm info using node@v10.15.3
npm verb exit [ 0, true ]
npm timing npm Completed in 54ms
npm info ok 
{
  "json": true,
  "loglevel": "silly""[truncated 3065 chars]; line: 1, column: 4]
```

**Comment by barbelity** [comment]
@fdolsky321 I can see that we currently have an issue when running npm builds with '-ddd' argument.
The problem is that before running the 'npm install' command, the plugin executes 'npm config ls' and parses the response as json. When using the '-ddd' argument, additional data is returned - which fails our parser.
Please try executing the job without '-ddd', and let us know if it works for you.

**Comment by fdolsky321** [comment]
Hi @barbelity the yes, I already tried and now I tried once again, same result. When I use this command:
`def buildInfo = npmBuild.install path: npmPackageDirectory`

I don't get any detailed information in log, just this:
```
[Pipeline] newBuildInfo
[Pipeline] artifactoryNpmInstall
process hasn't exited
[Pipeline] }
[Pipeline] // withEnv
[Pipeline] }
[Pipeline] // ansiColor
[Pipeline] }
[Pipeline] // stage
[Pipeline] echo
[Pipeline] }
[Pipeline] // node
[Pipeline] End of Pipeline
[Bitbucket] Notifying commit build result
[Bitbucket] Build result notified
java.lang.RuntimeException: npm build failed
	at org.jfrog.hudson.pipeline.common.executors.NpmInstallExecutor.execute(NpmInstallExecutor.java:59)
	at org.jfrog.hudson.pipeline.scripted.steps.NpmInstallStep$Execution.run(NpmInstallStep.java:64)
	at org.jfrog.hudson.pipeline.scripted.steps.NpmInstallStep$Execution.run(NpmInstallStep.java:39)
	at org.jenkinsci.plugins.workflow.steps.AbstractSynchronousNonBlockingStepExecution$1$1.call(AbstractSynchronousNonBlockingStepExecution.java:47)
	at hudson.security.ACL.impersonate(ACL.java:290)
	at org.jenkinsci.plugins.workflow.steps.AbstractSynchronousNonBlockingStepExecution$1.run(AbstractSynchronousNonBlockingStepExecution.java:44)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Finished: FAILURE
```

**Comment by fdolsky321** [comment]
basically no additional details in comparison with v.3.2.2

**Comment by fdolsky321** [comment]
I was able to find in log the issue with "process hasn't exited".

```
SEVERE: process hasn't exited
java.lang.IllegalThreadStateException: process hasn't exited
	at java.lang.UNIXProcess.exitValue(UNIXProcess.java:423)
	at org.jfrog.build.extractor.executor.CommandExecutor.exeCommand(CommandExecutor.java:78)
	at org.jfrog.build.extractor.npm.NpmDriver.runCommand(NpmDriver.java:80)
	at org.jfrog.build.extractor.npm.NpmDriver.install(NpmDriver.java:42)
	at org.jfrog.build.extractor.npm.extractor.NpmBuildInfoExtractor.runInstall(NpmBuildInfoExtractor.java:153)
	at org.jfrog.build.extractor.npm.extractor.NpmBuildInfoExtractor.extract(NpmBuildInfoExtractor.java:61)
	at org.jfrog.build.extractor.npm.extractor.NpmInstall.execute(NpmInstall.java:50)
	at org.jfrog.hudson.npm.NpmInstallCallable.invoke(NpmInstallCallable.java:53)
	at org.jfrog.hudson.npm.NpmInstallCallable.invoke(NpmInstallCallable.java:20)
	at hudson.FilePath$FileCallableWrapper.call(FilePath.java:3085)
	at hudson.remoting.UserRequest.perform(UserRequest.java:212)
	at hudson.remoting.UserRequest.perform(UserRequest.java:54)
	at hudson.remoting.Request$2.run(Request.java:369)
	at hudson.remoting.InterceptingExecutorService$1.call(InterceptingExecutorService.java:72)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by barbelity** [comment]
Thanks for the updates @fdolsky321.
Npm executions currently run with a timeout, which causes the build to return a failure in cases that timeout hits. I committed [this fix](https://github.com/jfrog/build-info/commit/2215d7d3d2880d938320522a1f0c8a77528325da#diff-8a1e5b219e67e7f2291ada4c78fd73bbL70), which removes the timeout and allows npm to finish its execution.
Please install and run your build with [this snapshot version](https://oss.jfrog.org/oss-snapshot-local/org/jenkins-ci/plugins/artifactory/3.2.x-SNAPSHOT/artifactory-3.2.x-20190424.112643-24.hpi) and update us with its results.

**Comment by fdolsky321** [comment]
Thanks for your Snapshot, now previous issue doesn't appear again, but now its stacked in this phase:
```
The npm dependencies above could not be found in Artifactory and therefore are not included in the build-info. Make sure the dependencies are available in Artifactory for this build. Deleting the local cache will force populating Artifactory with these dependencies.
```

**Comment by fdolsky321** [comment]
Hm, after 16 mins, this issue appeared:
```
[Bitbucket] Notifying commit build result
[Bitbucket] Build result notified
java.io.IOException: Unexpected EOF
	at hudson.remoting.ChunkedInputStream.readUntilBreak(ChunkedInputStream.java:99)
	at hudson.remoting.ChunkedCommandTransport.readBlock(ChunkedCommandTransport.java:39)
	at hudson.remoting.AbstractSynchronousByteArrayCommandTransport.read(AbstractSynchronousByteArrayCommandTransport.java:35)
	at hudson.remoting.SynchronousCommandTransport$ReaderThread.run(SynchronousCommandTransport.java:63)
Also:   hudson.remoting.Channel$CallSiteStackTrace: Remote call to stg-default-agent-eu
		at hudson.remoting.Channel.attachCallSiteStackTrace(Channel.java:1741)
		at hudson.remoting.Request.call(Request.java:202)
		at hudson.remoting.Channel.call(Channel.java:954)
		at hudson.FilePath.act(FilePath.java:1071)
		at hudson.FilePath.act(FilePath.java:1060)
		at org.jfrog.hudson.pipeline.common.executors.NpmInstallExecutor.execute(NpmInstallExecutor.java:57)
		at org.jfrog.hudson.pipeline.scripted.steps.NpmInstallStep$Execution.run(NpmInstallStep.java:64)
		at org.jfrog.hudson.pipeline.scripted.steps.NpmInstallStep$Execution.run(NpmInstallStep.java:39)
		at org.jenkinsci.plugins.workflow.steps.AbstractSynchronousNonBlockingStepExecution$1$1.call(AbstractSynchronousNonBlockingStepExecution.java:47)
		at hudson.security.ACL.impersonate(ACL.java:290)
		at org.jenkinsci.plugins.workflow.steps.AbstractSynchronousNonBlockingStepExecution$1.run(AbstractSynchronousNonBlockingStepExecution.java:44)
		at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
		at java.util.concurrent.FutureTask.run(FutureTask.java:266)
		at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
		at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
		at java.lang.Thread.run(Thread.java:748)
Caused: hudson.remoting.RequestAbortedException
	at hudson.remoting.Request.abort(Request.java:340)
	at hudson.remoting.Channel.terminate(Channel.java:1038)
	at hudson.remoting.SynchronousCommandTransport$ReaderThread.run(SynchronousCommandTransport.java:96)
Finished: FAILURE
```

**Comment by fdolsky321** [comment]
I would be curious, what's exactly behind this `npm install`... When I'm using `npm ci`, there is no issue at all. In `.npmrc` there is configured the Artifactory repo and this configuration works absolutely fine.

**Comment by barbelity** [comment]
When using the plugin's npm-install command it executes a new process running npm. We pass the required configuration to npm by creating a .npmrc file.
I couldn't reproduce the 'Unexpected EOF' issue on my environment. When searching for this error, I find that it may happen after an [agent runs out of memory](https://issues.jenkins-ci.org/browse/JENKINS-23419?focusedCommentId=216266&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-216266) or due to [environmental problems](https://stackoverflow.com/questions/44964832/jenkins-ec2-plugin-cant-launch-windows-slave-unexpected-eof?rq=1).
Please let me know what do you think.

**Comment by fdolsky321** [comment]
@barbelity thanks a lot for your answer. Well, if it wouldn't work neither for Jfrog CLI or just npm install command, I would agree with you. But this is really issue related only to the plugin itself. I don't have time for debugging this issue for now, I've just decided to use Jfrog CLI, which works fine for me. So you don't know about any other similar issue reported from anyone?

**Comment by yahavi** [comment]
@fdolsky321,
This [PR](https://github.com/jfrog/build-info/pull/232/files) resolves the issue with the verbose flags (`-ddd`, `--verbose` etc.). For more information, please take a look at this [Jira issue](https://www.jfrog.com/jira/browse/BI-486).
The latest version (Currently v3.2.4) includes a fix for this issue. Feel free to upgrade.
