### ISSUE TITLE
No example for <object of type org.jfrog.hudson.ServerDetails> in jenkins scripted pipeline

### ISSUE THREAD

**Issue by fzbassman** [jfrog/jenkins-artifactory-plugin#277]
I'm using the snippet generator in Jenkins to try and setup polling of artifactory for a change to a file via scripted pipeline (in properties).  When using the snippet generator an example is generated that looks like so (extras omitted):

properties([[pipelineTriggers([[$class: 'ArtifactoryTrigger', ç, paths: 'triggers/release-trigger', spec: 'H/15 * * * *']])])

This fails to execute without 'ServerDetails' (details:), the problem is there's no documentation I can find, or example of what 'ServerDetails' is supposed to be (it's not Artifactory.server).  Omitting 'details' still seems to provide what looks like a valid configuration after the job is initially executed, however when polling occurs, the following error appears in the Jenkins log:

org.jfrog.hudson.trigger.ArtifactoryTrigger.run() failed for hudson.model.FreeStyleProject@bc83c67[test-job]
java.lang.NullPointerException
	at org.jfrog.hudson.trigger.ArtifactoryTrigger.run(ArtifactoryTrigger.java:55)
	at hudson.triggers.Trigger.checkTriggers(Trigger.java:279)
	at hudson.triggers.Trigger$Cron.doRun(Trigger.java:226)
	at hudson.triggers.SafeTimerTask.run(SafeTimerTask.java:91)
	at jenkins.security.ImpersonatingScheduledExecutorService$1.run(ImpersonatingScheduledExecutorService.java:58)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

Polling artifactory from a freestyle job works fine, polling git from a scripted pipeline works fine.  Polling artifactory from a scripted pipeline does not.

Not sure if this should be a bug, enhancement request or a question, or if knowing what 'I'm using the snippet generator in Jenkins to try and setup polling of artifactory for a change to a file via scripted pipeline (in properties).  When using the snippet generator an example is generated that looks like so (extras omitted):

properties([[pipelineTriggers([[$class: 'ArtifactoryTrigger', details: <object of type org.jfrog.hudson.ServerDetails>, paths: 'triggers/release-trigger', spec: 'H/15 * * * *']])])

This fails to execute without 'ServerDetails' (details:), the problem is there's no documentation I can find, or example of what 'ServerDetails' is supposed to be (it's not Artifactory.server).  Omitting 'details' still seems to provide what looks like a valid configuration after the job is initially executed, however when polling occurs, the following error appears in the Jenkins log:

org.jfrog.hudson.trigger.ArtifactoryTrigger.run() failed for hudson.model.FreeStyleProject@bc83c67[test-job]
java.lang.NullPointerException
	at org.jfrog.hudson.trigger.ArtifactoryTrigger.run(ArtifactoryTrigger.java:55)
	at hudson.triggers.Trigger.checkTriggers(Trigger.java:279)
	at hudson.triggers.Trigger$Cron.doRun(Trigger.java:226)
	at hudson.triggers.SafeTimerTask.run(SafeTimerTask.java:91)
	at jenkins.security.ImpersonatingScheduledExecutorService$1.run(ImpersonatingScheduledExecutorService.java:58)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

Polling artifactory from a freestyle job works fine, polling git from a scripted pipeline works fine.  Polling artifactory from a scripted pipeline does not.

Not sure if this should be a bug, enhancement request or a question.   There should at least be come clarity on what 'details: <object of type org.jfrog.hudson.ServerDetails>' should be for a scripted pipeline using the snippet generator.

**Comment by uljo2** [comment]
Seems to still be valid. Having problems filling in correct values for the server I have choosen. Do you have a link to that pull request?
