### ISSUE TITLE
rtDockerPush fails with "Could not push image" despite pushing successfully

### ISSUE THREAD

**Issue by jkenn99** [jfrog/jenkins-artifactory-plugin#283]
**Describe the bug**
I'm able to push images fine using the CLI, using curl to the docker API, or from a Jenkins pipeline using the docker plugin. However, when using the rtDockerPush step the image is pushed to the registry successfully, but the step fails anyway.

This is output at the end of the pipeline log:
```
Also:   hudson.remoting.Channel$CallSiteStackTrace: Remote call to container-slave
		at hudson.remoting.Channel.attachCallSiteStackTrace(Channel.java:1788)
		at hudson.remoting.UserRequest$ExceptionResponse.retrieve(UserRequest.java:356)
		at hudson.remoting.Channel.call(Channel.java:998)
		at org.jfrog.hudson.pipeline.common.docker.utils.DockerAgentUtils.pushImage(DockerAgentUtils.java:129)
		at org.jfrog.hudson.pipeline.common.executors.DockerExecutor.execute(DockerExecutor.java:70)
		at org.jfrog.hudson.pipeline.declarative.steps.docker.DockerPushStep$Execution.run(DockerPushStep.java:96)
		at org.jfrog.hudson.pipeline.declarative.steps.docker.DockerPushStep$Execution.run(DockerPushStep.java:71)
		at org.jenkinsci.plugins.workflow.steps.AbstractSynchronousNonBlockingStepExecution$1$1.call(AbstractSynchronousNonBlockingStepExecution.java:47)
		at hudson.security.ACL.impersonate(ACL.java:359)
		at org.jenkinsci.plugins.workflow.steps.AbstractSynchronousNonBlockingStepExecution$1.run(AbstractSynchronousNonBlockingStepExecution.java:44)
		at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
		at java.util.concurrent.FutureTask.run(FutureTask.java:266)
		at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
		at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
		at java.lang.Thread.run(Thread.java:748)
com.github.dockerjava.api.exception.DockerClientException: Could not push image
	at com.github.dockerjava.core.command.PushImageResultCallback.throwFirstError(PushImageResultCallback.java:38)
	at com.github.dockerjava.core.async.ResultCallbackTemplate.awaitCompletion(ResultCallbackTemplate.java:94)
	at com.github.dockerjava.core.command.PushImageResultCallback.awaitSuccess(PushImageResultCallback.java:53)
	at org.jfrog.hudson.pipeline.common.docker.utils.DockerUtils.pushImage(DockerUtils.java:64)
	at org.jfrog.hudson.pipeline.common.docker.utils.DockerAgentUtils$2.call(DockerAgentUtils.java:137)
	at org.jfrog.hudson.pipeline.common.docker.utils.DockerAgentUtils$2.call(DockerAgentUtils.java:129)
	at hudson.remoting.UserRequest.perform(UserRequest.java:211)
	at hudson.remoting.UserRequest.perform(UserRequest.java:54)
	at hudson.remoting.Request$2.run(Request.java:369)
	at hudson.remoting.InterceptingExecutorService$1.call(InterceptingExecutorService.java:72)
	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.lang.Thread.run(Thread.java:834)
```
In artifactory.log the only hint I have is `Error uploading manifest: 'null'`.

**To Reproduce**
¯\_(ツ)_/¯
Not sure how to narrow it down at this point.

**Expected behavior**
Step should not fail the pipeline 

**Versions**
- Jenkins version: 2.222.3
- Jenkins Artifactory plugin version: 3.6.2
- Jenkins operating system: CentOS 8.1.1911
- Artifactory Version: 6.16.0

**Additional context**
Looking for suggestions for how to diagnose further.

**Comment by jkenn99** [comment]
Recently did some updates, and still having the same issue.

**Versions**
- Jenkins version: 2.222.3
- Jenkins Artifactory plugin version: 3.7.0
- Jenkins operating system: CentOS 8.2.2004
- Artifactory Version: 6.20.0

I no longer see `Error uploading manifest: 'null'` in artifactory.log, but the pipeline is still failing with the exception around `com.github.dockerjava.api.exception.DockerClientException: Could not push image`

**Comment by Or-Gabay** [comment]
@jkenn99,  is this occurs for every image you are trying to push?.
It will be helpful if you could share your pipeline script so I will be able to reproduce it on my side.

**Comment by faizan2131993** [comment]
@Or-Gabay, Even I get to see the same issue after upgrading it to the latest artifactory plugin version in Jenkins. And I do see it is happening with all the image push that uses rtDockerPush functionality.



`node('rhel') {
    def server = Artifactory.newServer url: SERVER_URL, credentialsId: CREDENTIALS
    def rtDocker = Artifactory.docker server: server
    def buildInfo = Artifactory.newBuildInfo()

    stage ('Dockerfile') {
        sh "echo \"FROM debian:latest\" > Dockerfile"
        sh "echo \"RUN apt-get update && apt-get install -y git\" >> Dockerfile"
    }

    stage ('Add properties') {
        // Attach custom properties to the published artifacts:
        rtDocker.addProperty("project-name", "docker1").addProperty("status", "stable")
    }

    stage ('Build docker image') {
        docker.withRegistry(SERVER_URL, CREDENTIALS) {
          docker.build("ARTIFACTORY_DOCKER_REGISTRY" + "/" + "pipeline-library/tests" + ":" + "1.10")
        }
    }

    stage ('Push image to Artifactory') {
      buildInfo = rtDocker.push ARTIFACTORY_DOCKER_REGISTRY  + "/" + "pipeline-library/tests" + ":" + "1.10", "docker-dev-local"
    }

    stage ('Publish build info') {
        server.publishBuildInfo buildInfo
    }
}`

The issue is produced during the rtDocker.pus.

**Comment by Or-Gabay** [comment]
@faizan2131993 , Could you please upgrade your Jenkins plugging to 3.9.0 and see if this issue recurs?

**Comment by Sjnahak** [comment]
Hi All / @Or-Gabay @eyalbe4 ,

# Plugin version used
```
artifactory plugin version 3.9.0
Jenkins version Jenkins 2.249.2
OWASP Markup Formatter Plugin 2.1
```
We are having issue with pushing docker image below is the error : 
```
[Docker_Push] $ java -cp /jenkins/workspace/test-API/Docker_Push@tmp/artifactory/cache/artifactory-plugin/3.9.0/* org.jfrog.build.extractor.docker.extractor.DockerPush
Nov 02, 2020 6:20:56 AM org.jfrog.build.extractor.packageManager.PackageManagerLogger info
INFO: Pushing image: repo-node-dev.jfrog.io/test:latest
Nov 02, 2020 6:21:08 AM org.jfrog.build.extractor.packageManager.PackageManagerLogger info
INFO: Trying to fetch manifest from Artifactory, assuming reverse proxy configuration.
Nov 02, 2020 6:21:09 AM org.jfrog.build.extractor.packageManager.PackageManagerLogger error
SEVERE: The manifest could not be fetched from Artifactory, assuming reverse proxy configuration - Failed to retrieve repository configuration 'repo-node-dev': HTTP/1.1 400 Bad Request
Nov 02, 2020 6:21:09 AM org.jfrog.build.extractor.packageManager.PackageManagerLogger info
INFO: Trying to fetch manifest from Artifactory, assuming proxy-less.
Nov 02, 2020 6:21:09 AM org.jfrog.build.extractor.packageManager.PackageManagerLogger error
SEVERE: The manifest could not be fetched from Artifactory - Failed to retrieve repository configuration 'repo-node-dev': HTTP/1.1 400 Bad Request
Nov 02, 2020 6:21:09 AM org.jfrog.build.extractor.packageManager.PackageManagerLogger error
SEVERE: The manifest could not be fetched from Artifactory.
Nov 02, 2020 6:21:09 AM org.jfrog.build.extractor.packageManager.PackageManagerLogger warn
WARNING: Could not find docker image: repo-node-dev.jfrog.io/test:latest in Artifactory.
java.lang.NullPointerException
	at org.jfrog.build.extractor.docker.extractor.DockerPush.setImageLayersProps(DockerPush.java:118)
	at org.jfrog.build.extractor.docker.extractor.DockerPush.execute(DockerPush.java:100)
	at org.jfrog.build.extractor.packageManager.PackageManagerExtractor.executeAndSaveBuildInfo(PackageManagerExtractor.java:29)
	at org.jfrog.build.extractor.docker.extractor.DockerPush.main(DockerPush.java:78)
```

# syntax for docker push using declarative 
```
stage('Docker-Build') {
            steps {
                script {
                    withDockerRegistry(credentialsId: 'docker_jenkins', url: 'https://test-node-dev.jfrog.io') {
                    docker.build('test-node-dev.jfrog.io' + '/test:latest', 'folder/Node/')   
                    }
                }
                
            }
        }
		
		stage('Docker-Push') {
            steps {
                rtDockerPush(
					serverId: 'artifactory-1',
					image: 'test-node-dev.jfrog.io' + '/test:latest',
					targetRepo: 'test-node-dev',
					buildName: 'test',
					buildNumber: '${BUILD_NUMBER}', 
                )
                
            }
        }
```
Any hints highly appreciated

**Comment by Or-Gabay** [comment]
@Sjnahak , it seems that `repo-node-dev` doesn't exist in Artifactory.

**Comment by Sjnahak** [comment]
@Or-Gabay sorry there was some typo , i have updated my comment.
the jfrog repo exists.

**Comment by rbjorklin** [comment]
I'm seeing a similar issue on the following setup:

## Versions

* Jenkins version: 2.277.1
* Jenkins Artifactory plugin version: 3.10.6
* Jenkins operating system: [jenkins/jenkins:2.277.1-lts-jdk11](https://hub.docker.com/r/jenkins/jenkins/tags?page=1&ordering=last_updated&name=2.277.1-lts-jdk11)
* Artifactory Version: 6.23.7

## Logs

```
[<REDACTED>] $ java -Djava.io.tmpdir=/tmp/workspace/<REDACTED>@tmp/artifactory/javatmpdir -cp /tmp/workspace/<REDACTED>@tmp/artifactory/cache/artifactory-plugin/3.10.6/* org.jfrog.build.extractor.docker.extractor.DockerPush
May 03, 2021 10:55:30 PM org.jfrog.build.extractor.packageManager.PackageManagerLogger info
INFO: Pushing image: docker.example.org/team1/loadtest-service:1.0.0
May 03, 2021 10:55:35 PM org.jfrog.build.extractor.packageManager.PackageManagerLogger info
INFO: Searching manifest for image "docker.example.org/team1/loadtest-service:1.0.0" in "https://artifactory.example.org" under "example-docker-release-local" repository
May 03, 2021 10:55:35 PM org.jfrog.build.extractor.packageManager.PackageManagerLogger info
INFO: Searching manifest in path: example-docker-release-local/team1/loadtest-service/1.0.0
May 03, 2021 10:55:35 PM org.jfrog.build.extractor.packageManager.PackageManagerLogger info
INFO: Trying to download manifest from https://artifactory.example.org/example-docker-release-local/team1/loadtest-service/1.0.0/manifest.json
May 03, 2021 10:55:36 PM org.jfrog.build.extractor.packageManager.PackageManagerLogger info
INFO: The search failed with "Unable to find https://artifactory.example.org/example-docker-release-local/team1/loadtest-service/1.0.0/manifest.json".
May 03, 2021 10:55:36 PM org.jfrog.build.extractor.packageManager.PackageManagerLogger info
INFO: Searching manifest in path: team1/loadtest-service/1.0.0
May 03, 2021 10:55:36 PM org.jfrog.build.extractor.packageManager.PackageManagerLogger info
INFO: Trying to download manifest from https://artifactory.example.org/team1/loadtest-service/1.0.0/manifest.json
May 03, 2021 10:55:36 PM org.jfrog.build.extractor.packageManager.PackageManagerLogger info
INFO: The search failed with "Unable to find https://artifactory.example.org/team1/loadtest-service/1.0.0/manifest.json".
May 03, 2021 10:55:36 PM org.jfrog.build.extractor.packageManager.PackageManagerLogger error
SEVERE: The manifest could not be fetched from Artifactory.
May 03, 2021 10:55:36 PM org.jfrog.build.extractor.packageManager.PackageManagerLogger warn
WARNING: Could not find docker image: docker.example.org/team1/loadtest-service:1.0.0 in Artifactory.
java.lang.NullPointerException
        at org.jfrog.build.extractor.docker.extractor.DockerPush.setImageLayersProps(DockerPush.java:118)
        at org.jfrog.build.extractor.docker.extractor.DockerPush.execute(DockerPush.java:100)
        at org.jfrog.build.extractor.packageManager.PackageManagerExtractor.executeAndSaveBuildInfo(PackageManagerExtractor.java:33)
        at org.jfrog.build.extractor.docker.extractor.DockerPush.main(DockerPush.java:78)

...

java.lang.RuntimeException: docker build failed
        at org.jfrog.hudson.pipeline.common.Utils.launch(Utils.java:289)
        at org.jfrog.hudson.pipeline.common.executors.BuildInfoProcessRunner.execute(BuildInfoProcessRunner.java:59)
        at org.jfrog.hudson.pipeline.common.executors.DockerPushExecutor.execute(DockerPushExecutor.java:42)
        at org.jfrog.hudson.pipeline.declarative.steps.docker.DockerPushStep$Execution.runStep(DockerPushStep.java:92)
        at org.jfrog.hudson.pipeline.declarative.steps.docker.DockerPushStep$Execution.runStep(DockerPushStep.java:77)
        at org.jfrog.hudson.pipeline.ArtifactorySynchronousNonBlockingStepExecution.run(ArtifactorySynchronousNonBlockingStepExecution.java:54)
        at org.jenkinsci.plugins.workflow.steps.SynchronousNonBlockingStepExecution.lambda$start$0(SynchronousNonBlockingStepExecution.java:47)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)
```

## Jenkins pipeline step

```
rtDockerPush(
    serverId: "artifactory",
    image: "${imageName}:${imageTag}",
    targetRepo: "example-docker-${env.TAG_NAME ? 'release' : 'scratch'}-local",
)
```

## Comment / Observation

The push seems to complete and then the step fails on trying to validate that the push actually completed. Does this seem plausible?

**Comment by Or-Geva** [comment]
@rbjorklin, thanks for reporting this, however, I do think the `targetRepo` is wrong.
After the image was pushed,`rtDockerPush` tries to search for it in Artifactory using the `serverId` and `targetRepo`.
Search in Artifactory what repository contains the pushed image and set `targetRepo` to this repository name.

**Comment by augustocarvalho** [comment]
We have a similar issue. 
The image is actually pushed but with no buildName and buildNumber properties. Even if we force the properties with fix values. 
rtDockerPush(
                            serverId: RT_SERVER_ID,
                            targetRepo: RT_REPO,
                            image: DOCKER_IMAGE_LATEST,
                            buildName: 'mybuildname',
                            buildNumber: '17',
                    )


Sep 28, 2022 11:08:12 AM org.jfrog.build.extractor.packageManager.PackageManagerLogger error
SEVERE: Failed to set properties to  'IMAGE_URL/1.0.0-latest/manifest.json'
Sep 28, 2022 11:08:12 AM org.jfrog.build.extractor.packageManager.PackageManagerLogger error
SEVERE: JFrog service failed. Received 400: {
  "errors" : [ {
    "status" : 400,
    "message" : "Properties value cannot be empty."
  } ]
}
java.io.IOException: JFrog service failed. Received 400: {
  "errors" : [ {
    "status" : 400,
    "message" : "Properties value cannot be empty."
  } ]
}
