### ISSUE TITLE
rtNugetResolver/Run crashes when reading package.config generated by Visual Studio

### ISSUE THREAD

**Issue by zwartsj** [jfrog/jenkins-artifactory-plugin#329]
**Describe the bug**
When a package file is created by Visual Studio it will have the format will have byte order mark as described in 
https://en.wikipedia.org/wiki/Byte_order_mark i.e. UTF-8 format.

When artifactory plugin reads this file it will crash, as see in the following output:

Aug 31, 2020 5:21:27 PM org.jfrog.build.extractor.packageManager.PackageManagerLogger error
SEVERE: Unexpected first character (char code 0xEF), not valid in xml document: could be mangled UTF-8 BOM marker. Make sure that the Reader uses correct encoding or pass an InputStream instead
com.fasterxml.jackson.core.JsonParseException: Unexpected first character (char code 0xEF), not valid in xml document: could be mangled UTF-8 BOM marker. Make sure that the Reader uses correct encoding or pass an InputStream instead
	at com.fasterxml.jackson.dataformat.xml.util.StaxUtil.throwAsParseException(StaxUtil.java:37)
	at com.fasterxml.jackson.dataformat.xml.XmlFactory._createParser(XmlFactory.java:584)
	at com.fasterxml.jackson.dataformat.xml.XmlFactory.createParser(XmlFactory.java:464)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3214)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3182)
	at org.jfrog.build.extractor.nuget.types.NugetPackgesConfig.readPackageConfig(NugetPackgesConfig.java:55)
	at org.jfrog.build.extractor.nuget.extractor.NugetRun.collectDependenciesFromPackagesConfig(NugetRun.java:310)
	at org.jfrog.build.extractor.nuget.extractor.NugetRun.singleProjectHandler(NugetRun.java:273)
	at org.jfrog.build.extractor.nuget.extractor.NugetRun.collectDependenciesFromProjectDir(NugetRun.java:245)
	at org.jfrog.build.extractor.nuget.extractor.NugetRun.collectDependencies(NugetRun.java:218)
	at org.jfrog.build.extractor.nuget.extractor.NugetRun.execute(NugetRun.java:105)
	at org.jfrog.build.extractor.packageManager.PackageManagerExtractor.executeAndSaveBuildInfo(PackageManagerExtractor.java:29)
	at org.jfrog.build.extractor.nuget.extractor.NugetRun.main(NugetRun.java:451)
Caused by: com.ctc.wstx.exc.WstxIOException: Unexpected first character (char code 0xEF), not valid in xml document: could be mangled UTF-8 BOM marker. Make sure that the Reader uses correct encoding or pass an InputStream instead
	at com.ctc.wstx.io.ReaderBootstrapper.bootstrapInput(ReaderBootstrapper.java:175)
	at com.ctc.wstx.stax.WstxInputFactory.doCreateSR(WstxInputFactory.java:573)
	at com.ctc.wstx.stax.WstxInputFactory.createSR(WstxInputFactory.java:633)
	at com.ctc.wstx.stax.WstxInputFactory.createSR(WstxInputFactory.java:687)
	at com.ctc.wstx.stax.WstxInputFactory.createXMLStreamReader(WstxInputFactory.java:350)
	at com.fasterxml.jackson.dataformat.xml.XmlFactory._createParser(XmlFactory.java:582)
	... 11 more

**To Reproduce**
- Create the package.config file using Visual Studio or Convert to UTF-8 format. 

**Expected behavior**
- Jenkins Artifactory plugin should be able to work with package config files generated by VS without modifications

**Screenshots**

**Versions**
- Jenkins Artifactory plugin version: 
3.8.1
- Jenkins operating system:
Windows Server 2012 RS
- Artifactory Version:
6.3.3 rev 60303900

**Additional context**
Problem can be solved using following solution or similar. 
https://www.rgagnon.com/javadetails/java-handle-utf8-file-with-bom.html

**Comment by papanito** [comment]
We are affected by this bug too and this is very annoying

**Comment by eyalbe4** [comment]
Thanks for reporting this @zwartsj and @papanito!
The above PR fixes the issue. We're planning to release a patch soon. We'll update this issue when the patch is released.

**Comment by RobiNino** [comment]
@zwartsj , @papanito, Thank you for reporting this issue.
We just released version 3.9.1 of the plugin which includes a fix.
We'd appreciate your feedback for it.

**Comment by papanito** [comment]
Thanks will have a look tomorrow

**Comment by papanito** [comment]
I currently get
```
ERROR: transport error 202: gethostbyname: unknown host
ERROR: JDWP Transport dt_socket failed to initialize, TRANSPORT_INIT(510)
JDWP exit error AGENT_ERROR_TRANSPORT_INIT(197): No transports initialized [debugInit.c:750]
```

**Comment by papanito** [comment]
I can confirm that the issue is gone with the latest version of the plugin. Thanks guys

**Comment by eyalbe4** [comment]
Happy to hear this @papanito. Thanks for confirming.
