### ISSUE TITLE
rtDockerPush fails after upgrade from 3.7.3 to 3.8.1

### ISSUE THREAD

**Issue by alexeyt820** [jfrog/jenkins-artifactory-plugin#334]
**Describe the bug**
After upgrade of plugin from 3.7.3 to 3.8.1 rtDockerPush fails
```
19:10:07  [GitHub_gim-fsp_prototype] $ java -cp /home/jenkins/workspace/GitHub_gim-fsp_prototype@tmp/artifactory/cache/artifactory-plugin/3.8.1/* org.jfrog.build.extractor.docker.extractor.DockerPush
19:10:07  ERROR: Couldn't execute docker task. IOException: Cannot run program "java" (in directory "/home/jenkins/workspace/GitHub_gim-fsp_prototype"): error=2, No such file or directory
```

**To Reproduce**
Nothing specific, declarative pipeline step consisting of pulling image from local repo and pushing into Artifactory
```
      ...
        steps {
            script {
              def dockerTag = getGitDescription().dockerTag
              withDockerRegistry(credentialsId: 'docker-registry-ci', url: "https://${REGISTRIES.ci.host}") {
                def image = docker.image("${dockerImageName('ci', dockerTag)}")
                image.pull()
              }
              sh "docker tag ${dockerImageName('ci', dockerTag)} ${dockerImageName('dev', dockerTag)}"
              sh "docker tag ${dockerImageName('ci', dockerTag)} ${dockerImageName('dev', 'latest')}"
              rtDockerPush (
                      serverId: REGISTRIES.dev.id,
                      image: dockerImageName('dev', dockerTag),
                      targetRepo: REGISTRIES.dev.targetRepo,
                      properties: "commit=${getCommit()}"
              )
   ....
```
**Expected behavior**
Push docker image successfully

**Screenshots**

**Versions**
- Jenkins Artifactory plugin version: 3.8.1
- Jenkins operating system: master: Windows, but step runs in Linux (CentOS)
- Jenkins version: 2.235.5
- Artifactory Version: hosted, idk

**Additional context**

**Comment by simonwalton** [comment]
We have encountered this too - without warning, the plugin now depends upon Java always being available within the execution context. Is this something that is always going to be the case?

**Comment by Or-Gabay** [comment]
@simonwalton & @alexeyt820, Artifactory plugin V3.8.0 or above assumed that there's already java installed on the Jenkins agent.
The issue of plugin dependencies collisions in Jenkins is sometimes extremely hard to resolve. For that reason, we use a new separate process to perform docker push/pull.
The motivation for implementing this described here - https://github.com/jfrog/jenkins-artifactory-plugin/issues/268

**Comment by antonovicha** [comment]
@Or-Gabay So it seems that from now on jenkins docker pipelines will require extra configuration or wont work any more?
Any ideas how to proceed for such pipelines? We are using node docker containers and JAVA is not part of said container.
Error is:

> org.jfrog.build.extractor.docker.extractor.DockerPush
> OCI runtime exec failed: exec failed: container_linux.go:349: starting container process caused "exec: \"java\": executable file not found in $PATH": unknown

When push stage is configured as `agent any`, error is:

> org.jfrog.build.extractor.docker.extractor.DockerPush
> OCI runtime exec failed: exec failed: container_linux.go:349: starting container process caused "chdir to cwd (\"%PATH_TO_PIPELINE%@2\") set in config.json failed: no such file or directory": unknown

**Comment by eyalbe4** [comment]
@antonovicha,

I'm afraid java is now a requirement for for docker images used to push docker images using the Artifactory Plugins. The Artifactory Plugin always used [docker-java](https://github.com/docker-java/docker-java), which is java library which wraps the docker daemon API. The only change that was recently introduced as part of the Artifactory Plugin, is that the docker-java API is now invoked in a new process, which causes Jenkins to run this java process inside your container. It appears that before this change, the docker push was happening on your Jenkins agent (which has java installed) but outside the container you're using (which doesn't have java installed).

I think that the best approach towards resolving this issue, is to create a new docker image, which is based on the image you're using now, and just have the Docker file install java on it. 

As you can see in https://github.com/jfrog/jenkins-artifactory-plugin/issues/268 we were simply left with no choice but to implement this change (which wasn't easy to implement by the way). The reality is that Jenkins plugins can easily cause dependencies collisions between them, which are sometimes impossible to resolve.

**Comment by antonovicha** [comment]
@eyalbe4 Thanks for in depth answer. I will investigate possibility of custom docker container for our solution later on.

In mean time I came up with workaround:
I am running pipeline as `agent any`, and `Build` stage as `agent docker...`. I was forced to merge build & unit test stages into one, because it was not working as 2 separate stages with `agent docker`. Now I have 1 dockerized stage and artifactory docker push happens on Jenkins, so it works.

**Comment by antonovicha** [comment]
Here is what I am trying now:
```
pipeline {
  agent {
    docker {
      image "node:12.16.1"
      args "-v /usr/bin/docker:/usr/bin/docker -v /var/run/docker.sock:/var/run/docker.sock --group-add ${env.DOCKER_GRP_ID}"
    }
  }
...
stage('Java in steps') {
  steps {
    script {
      docker.image("openjdk:15").inside("-v /usr/bin/docker:/usr/bin/docker -v /var/run/docker.sock:/var/run/docker.sock --group-add ${env.DOCKER_GRP_ID}") {
        rtDockerPush (
          serverId: REDACTED,
          image: REDACTED,
          targetRepo: REDACTED
        )
      }
    }
  }
}
```

And following error happens:
> JENKINS_PIPELINE_PATH@tmp/artifactory/cache/artifactory-plugin/3.8.x-SNAPSHOT-1602663522858/* org.jfrog.build.extractor.docker.extractor.DockerPush
> Oct 14, 2020 8:18:43 AM org.jfrog.build.extractor.packageManager.PackageManagerLogger info
> INFO: Pushing image: REDCATED
> Exception in thread "main" java.lang.ExceptionInInitializerError
> 	at com.github.dockerjava.netty.NettyDockerCmdExecFactory$UnixDomainSocketInitializer.init(NettyDockerCmdExecFactory.java:140)
> 	at com.github.dockerjava.netty.NettyDockerCmdExecFactory.init(NettyDockerCmdExecFactory.java:114)
> 	at com.github.dockerjava.core.DockerClientImpl.withDockerCmdExecFactory(DockerClientImpl.java:193)
> 	at com.github.dockerjava.core.DockerClientBuilder.build(DockerClientBuilder.java:45)
> 	at org.jfrog.build.extractor.docker.DockerJavaWrapper.getDockerClient(DockerJavaWrapper.java:75)
> 	at org.jfrog.build.extractor.docker.DockerJavaWrapper.pushImage(DockerJavaWrapper.java:39)
> 	at org.jfrog.build.extractor.docker.extractor.DockerPush.execute(DockerPush.java:104)
> 	at org.jfrog.build.extractor.packageManager.PackageManagerExtractor.executeAndSaveBuildInfo(PackageManagerExtractor.java:29)
> 	at org.jfrog.build.extractor.docker.extractor.DockerPush.main(DockerPush.java:89)
> Caused by: java.lang.StringIndexOutOfBoundsException: begin 0, end 3, length 2
> 	at java.base/java.lang.String.checkBoundsBeginEnd(String.java:3734)
> 	at java.base/java.lang.String.substring(String.java:1903)
> 	at org.apache.commons.lang.SystemUtils.getJavaVersionAsFloat(SystemUtils.java:1133)
> 	at org.apache.commons.lang.SystemUtils.<clinit>(SystemUtils.java:818)
> 	... 9 more

Any ideas?

**Comment by antonovicha** [comment]
Update: downgrading java version to 14 helped. I.e. `docker.image("openjdk:14")`.

**Comment by jeniamayzel** [comment]
is there another WA rather than using  docker.image("openjdk:14"). just for docker Push ?

**Comment by jeniamayzel** [comment]
there is another failure in 3.9.0 plugin version
`java.lang.NullPointerException
	at org.jfrog.build.extractor.docker.extractor.DockerPush.setImageLayersProps(DockerPush.java:118)
	at org.jfrog.build.extractor.docker.extractor.DockerPush.execute(DockerPush.java:100)
	at org.jfrog.build.extractor.packageManager.PackageManagerExtractor.executeAndSaveBuildInfo(PackageManagerExtractor.java:29)
	at org.jfrog.build.extractor.docker.extractor.DockerPush.main(DockerPush.java:78)`

**Comment by sbeaulie** [comment]
I get the same NullPointerExecption on 3.10.3, did you find a way to resolve?

**Comment by sherykottai** [comment]
I am getting the same error with Artifactory plugin 3.10.5
@sbeaulie and @jeniamayzel , Any of you found a solution for this? Thanks.

**Comment by sbeaulie** [comment]
No, I reverted back to a previous version, which is obviously not desired.

**Comment by cyberarkDevopsCandidate** [comment]
@sbeaulie @sherykottai I wrote some code (Jenkins Groovy Step) that take the image layers data from 'manifest.json" in Artifactory Browser and injects it into Docker Info data --> it appears in Build info afterwards

**Comment by jeniamayzel** [comment]
@sbeaulie @sherykottai I wrote some code (Jenkins Groovy Step) that take the image layers data from 'manifest.json" in Artifactory Browser and injects it into Docker Info data --> it appears in Build info afterwards

**Comment by Or-Geva** [comment]
Please try to run [this](https://github.com/jfrog/project-examples/blob/master/jenkins-examples/pipeline-examples/declarative-examples/docker-push-example/Jenkinsfile) project example and see if it works for you. Could you share a pipeline script that reproduces this issue? it would help me solve this issue.

**Comment by Maxghost33** [comment]
I also have the same issue: 
java.lang.NullPointerException
	at org.jfrog.build.extractor.docker.extractor.DockerPush.setImageLayersProps(DockerPush.java:118)
	at org.jfrog.build.extractor.docker.extractor.DockerPush.execute(DockerPush.java:100)
	at org.jfrog.build.extractor.packageManager.PackageManagerExtractor.executeAndSaveBuildInfo(PackageManagerExtractor.java:33)
	at org.jfrog.build.extractor.docker.extractor.DockerPush.main(DockerPush.java:78)
when use:
                rtDockerPush(
                      serverId: "id",
                      image: "image_name",
                      targetRepo: "repo"
                  )
Could someone help?

**Comment by Or-Geva** [comment]
@Maxghost33, could you share your pipeline script?

**Comment by Maxghost33** [comment]
@Or-Geva 

properties([
  parameters([
    string(name: 'IMAGE_LABEL', trim: true, defaultValue: '', description: ''),
    string(name: 'IMAGE_NAME', trim: true, defaultValue: '', description: ''),
    string(name: 'IMAGE_TAG', trim: true, defaultValue: '', description: ''),
    ])
])

@Library("jenkinsci-shared-library@v0.2.0") _
pipeline {

    agent {
        label '.......'
    }

    environment{
        BAMS_HOST='........'
        IMAGE_PREFIX_NAME='.........'
    }

    stages {

        stage("Checkout dockerfiles") {
            steps {
                gitCheckoutBranch url: 'git@git......git', credentialsId: 'cred_id', branch: "master"
            }
        }

        stage("Build Image") {
            steps {
                dir ("docker-slaves/${env.IMAGE_LABEL}") {
                    sh "docker image build -t ${HOST}/${IMAGE_PREFIX_NAME}${IMAGE_NAME}:${IMAGE_TAG} -f Dockerfile ."
                }
            }
        }

        stage("Publish Image") {
            steps {
                rtDockerPush(
                      serverId: "serverId",
                      image: "${HOST}/${IMAGE_PREFIX_NAME}${IMAGE_NAME}:${IMAGE_TAG}",
                      targetRepo: "repo"
                  )

                rtPublishBuildInfo (
                      serverId: "serverId"
                  )
            }
        }
    }
}


version for Artifactory Plugin: 3.10.1, Jenkins: 2.285

**Comment by Or-Geva** [comment]
Thanks, @Maxghost33, Do you see the pushed image's `manifest.json` in `repo` repository? if so, what it's full path in Artifactory & content?

**Comment by alexey-tr** [comment]
What is need to be done to make it work. I've tried to add jdk tool to declarative pipeline, task still fails
```
[GitHub_etl_master] $ java -Djava.io.tmpdir=/home/jenkins/workspace/GitHub_etl_master@tmp/artifactory/javatmpdir -cp /home/jenkins/workspace/GitHub_etl_master@tmp/artifactory/cache/artifactory-plugin/3.10.6/* org.jfrog.build.extractor.docker.extractor.DockerPush
ERROR: Couldn't execute docker task. IOException: Cannot run program "java" (in directory "/home/jenkins/workspace/GitHub_etl_master"): error=2, No such file or directory
docker build failed
```

**Comment by eyalbe4** [comment]
@alexey-tr,
It looks like you don't have java installed on the Jenkins agent, or it is not in the PATH. The error you shared includes ```Cannot run program "java"```

**Comment by alexey-tr** [comment]
> @alexey-tr,
> It looks like you don't have java installed on the Jenkins agent, or it is not in the PATH. The error you shared includes `Cannot run program "java"`

Doubt it, I run "sh java -version" before rtDockerPush, and it prints java version
```groovy
stage('Push to dev') {
          tools {
            jdk 'jdk8'
          }
          steps {
            script {
              sh "java -version"
              ...
              rtDockerPush (
                      serverId: REGISTRIES.dev.id,
                      image: dockerImageName('dev', dockerTag),
                      targetRepo: REGISTRIES.dev.targetRepo,
                      properties: "commit=${getCommit()}"
              )
             ...
          }
     }
}
```

output:
```
[Pipeline] sh
21:26:45  + java -version
21:26:45  java version "1.8.0_202"
...
[Pipeline] rtDockerPush
21:26:48  [GitHub_gim-fsp_master] $ java -Djava.io.tmpdir=/home/jenkins/workspace/GitHub_gim-fsp_master@tmp/artifactory/javatmpdir -cp /home/jenkins/workspace/GitHub_gim-fsp_master@tmp/artifactory/cache/artifactory-plugin/3.10.6/* org.jfrog.build.extractor.docker.extractor.DockerPush
21:26:48  ERROR: Couldn't execute docker task. IOException: Cannot run program "java" (in directory "/home/jenkins/workspace/GitHub_gim-fsp_master"): error=2, No such file or directory
...
```

**Comment by eyalbe4** [comment]
@alexey-tr,
Are you using a recent version of the Jenkins Artifactory Plugin? If not, please go ahead and upgrade. If the issue persists after the upgrade, can you please open a terminal **on the agent machine**, and try running ```java -version```?

**Comment by alexey-tr** [comment]
The problem started after upgrading to 3.10.6. Agent machine has Java:
```
java -version
java version "1.8.0_121"
Java(TM) SE Runtime Environment (build 1.8.0_121-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.121-b13, mixed mode)
```

Does plugin ignores java brought by 
```groovy
tools {
  jdk 'jdk8'
}
```
?

**Comment by eyalbe4** [comment]
I'm not sure @alexey-tr.
Let us check this and we'll reply here.
On which version of the plugin did this work for you?

**Comment by alexey-tr** [comment]
3.7.3 worked
