### ISSUE TITLE
rtMavenRun gives an incorrect error message

### ISSUE THREAD

**Issue by ankits** [jfrog/jenkins-artifactory-plugin#377]
**Describe the bug**
rtMavenRun gives an incorrect error message when executed in a closure.

**To Reproduce**
Run rtMavenRun in a dir closure. 

```

dir('testbed') {    
     rtMavenRun(
            // Tool name from Jenkins configuration.
            tool: 'maven3',
            pom: 'pom.xml',
            goals: '} -DskipTests -Dcheckstyle.skip=true -Prelease clean install',
            // Maven options.
            opts: '-B -X --no-transfer-progress',
            resolverId: 'Maven_Resolver',
            deployerId: 'Maven_Deployer',
    )
}

```

You will get an error message saying: 
```
java.io.IOException: Deployer Maven_Deployer doesn't exist!
	at org.jfrog.hudson.pipeline.declarative.steps.maven.MavenStep$Execution.setDeployer(MavenStep.java:112)
	at org.jfrog.hudson.pipeline.declarative.steps.maven.MavenStep$Execution.setMavenBuild(MavenStep.java:102)
	at org.jfrog.hudson.pipeline.declarative.steps.maven.MavenStep$Execution.run(MavenStep.java:92)
	at org.jfrog.hudson.pipeline.declarative.steps.maven.MavenStep$Execution.run(MavenStep.java:79)
	at org.jenkinsci.plugins.workflow.steps.SynchronousNonBlockingStepExecution.lambda$start$0(SynchronousNonBlockingStepExecution.java:47)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Finished: FAILURE
```
**Expected behavior**
Expected error message should be to not run the rtMavenRun in a dir closure. Because everything works fine if I remove the closure. 

**Screenshots**

**Versions**
- Jenkins Artifactory plugin version:  3.9.0
- Jenkins operating system: 2.249.3
- Artifactory Version: 6.23.1

**Additional context**

**Comment by yahavi** [comment]
@ankits,
Thanks for reporting this issue! 
We are working on a fix. We will keep you updated.

**Comment by yahavi** [comment]
@ankits,
We fixed this issue in https://github.com/jfrog/jenkins-artifactory-plugin/pull/382.

Here's a snapshot version which includes the fix:
https://oss.jfrog.org/oss-snapshot-local/org/jenkins-ci/plugins/artifactory/3.10.x-SNAPSHOT/artifactory-3.10.x-20201206.160529-3.hpi

We'd appreciate your feedback on that.

**Comment by yahavi** [comment]
@ankits,
Jenkins Artifactory plugin 3.10.1 is released. This version includes the fix for this issue. Feel free to upgrade.
We'd appreciate your feedback on that.
