### ISSUE TITLE
newConanClient() fails when run in Docker for Windows container scope

### ISSUE THREAD

**Issue by jasal82** [jfrog/jenkins-artifactory-plugin#378]
**Describe the bug**
Artifactory.newConanClient() fails with the following error message:
`conan config: error: unrecognized arguments: && exit %0%`

I see the following `docker exec` invocation in the log:
```
docker exec --workdir c:\workdir d3ab8259a62e5749a756d5c0b0adeebf12b3a82969876ed717559e5fc3b60ec2 cmd.exe /C "conan config set "log.trace_file=""C:\Conan\conan_log.log""" && exit %%ERRORLEVEL%%"
```

**To Reproduce**
Minimal pipeline script to reproduce:
```groovy
node("dockerHost") {
  docker.image('some_win_image:latest').inside {
    def conanClient = Artifactory.newConanClient()
  }
}
```

**Expected behavior**
Doesn't fail.

**Versions**
- Jenkins Artifactory plugin version: Latest
- Jenkins operating system: Windows
- Artifactory Version: 6.23.1

**Comment by jasal82** [comment]
Must be a peculiarity of the `docker exec` command. Running `cmd.exe /C "conan config set ...` directly works fine.

**Comment by Or-Gabay** [comment]
@jasal82, Thank you for reporting this issue.
I would like to share with you a snapshot, which includes a fix for this issue.
[artifactory.hpi.zip](https://github.com/jfrog/jenkins-artifactory-plugin/files/5660314/artifactory.hpi.zip)
I will appreciate your feedback on that!.

**Comment by jasal82** [comment]
@Or-Geva Sorry for the delay, I was on vacation. I'll check this as soon as possible.

**Comment by jasal82** [comment]
Fix verified, works fine now.

**Comment by Or-Geva** [comment]
Thanks!.

**Comment by Or-Geva** [comment]
@jasal82 , the fix for this issue is included in the latest Jenkins Artifactory plugin 3.10.4.
Feel free to upgrade and share your feedback.

**Comment by jasal82** [comment]
`newConanClient()` can be used now but when uploading build info it fails, callstack is below. The exact same thing works on Linux containers. Not sure if this is also a problem with the plugin.

```
14:58:18  Also:   hudson.remoting.Channel$CallSiteStackTrace: Remote call to JNLP4-connect connection from deags09343.sickcn.net/10.2.160.143:54202
14:58:18  		at hudson.remoting.Channel.attachCallSiteStackTrace(Channel.java:1800)
14:58:18  		at hudson.remoting.UserRequest$ExceptionResponse.retrieve(UserRequest.java:357)
14:58:18  		at hudson.remoting.Channel.call(Channel.java:1001)
14:58:18  		at hudson.FilePath.act(FilePath.java:1157)
14:58:18  		at hudson.FilePath.act(FilePath.java:1146)
14:58:18  		at hudson.FilePath.touch(FilePath.java:1719)
14:58:18  		at org.jfrog.hudson.pipeline.common.executors.ConanExecutor.persistBuildProperties(ConanExecutor.java:139)
14:58:18  		at org.jfrog.hudson.pipeline.common.executors.ConanExecutor.execCommand(ConanExecutor.java:98)
14:58:18  		at org.jfrog.hudson.pipeline.scripted.steps.conan.RunCommandStep$Execution.runStep(RunCommandStep.java:50)
14:58:18  		at org.jfrog.hudson.pipeline.scripted.steps.conan.RunCommandStep$Execution.runStep(RunCommandStep.java:37)
14:58:18  		at org.jfrog.hudson.pipeline.ArtifactorySynchronousNonBlockingStepExecution.run(ArtifactorySynchronousNonBlockingStepExecution.java:42)
14:58:18  		at org.jenkinsci.plugins.workflow.steps.SynchronousNonBlockingStepExecution.lambda$start$0(SynchronousNonBlockingStepExecution.java:47)
14:58:18  		at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
14:58:18  		at java.util.concurrent.FutureTask.run(FutureTask.java:266)
14:58:18  		at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
14:58:18  		at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
14:58:18  		at java.lang.Thread.run(Thread.java:748)
14:58:18  Also:   	Also:   hudson.remoting.Channel$CallSiteStackTrace: Remote call to JNLP4-connect connection from deags09341.sickcn.net/10.2.160.141:51533
14:58:18  			at hudson.remoting.Channel.attachCallSiteStackTrace(Channel.java:1800)
14:58:18  			at hudson.remoting.UserRequest$ExceptionResponse.retrieve(UserRequest.java:357)
14:58:18  			at hudson.remoting.Channel.call(Channel.java:1001)
14:58:18  			at hudson.FilePath.act(FilePath.java:1157)
14:58:18  			at hudson.FilePath.act(FilePath.java:1146)
14:58:18  			at hudson.FilePath.touch(FilePath.java:1719)
14:58:18  			at org.jfrog.hudson.pipeline.common.executors.ConanExecutor.persistBuildProperties(ConanExecutor.java:139)
14:58:18  			at org.jfrog.hudson.pipeline.common.executors.ConanExecutor.execCommand(ConanExecutor.java:98)
14:58:18  			at org.jfrog.hudson.pipeline.scripted.steps.conan.RunCommandStep$Execution.runStep(RunCommandStep.java:50)
14:58:18  			at org.jfrog.hudson.pipeline.scripted.steps.conan.RunCommandStep$Execution.runStep(RunCommandStep.java:37)
14:58:18  			at org.jfrog.hudson.pipeline.ArtifactorySynchronousNonBlockingStepExecution.run(ArtifactorySynchronousNonBlockingStepExecution.java:42)
14:58:18  			at org.jenkinsci.plugins.workflow.steps.SynchronousNonBlockingStepExecution.lambda$start$0(SynchronousNonBlockingStepExecution.java:47)
14:58:18  			at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
14:58:18  			at java.util.concurrent.FutureTask.run(FutureTask.java:266)
14:58:18  			at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
14:58:18  			at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
14:58:18  			at java.lang.Thread.run(Thread.java:748)
14:58:18  java.nio.file.NoSuchFileException: C:\Conan\ScanCtrl_Conan\.conan\artifacts.properties
```

**Comment by jasal82** [comment]
@Or-Geva When setting `userHome` to something outside of the workspace folder (e.g. `C:\Conan`) I always get a NoSuchFileException on the `artifacts.properties` during `ConanExecutor.persistBuildProperties()`. In the workspace folder it's working fine. Am I doing something wrong?
