### ISSUE TITLE
npmBuild.install falls with a NullPointerException

### ISSUE THREAD

**Issue by bolivard-k** [jfrog/jenkins-artifactory-plugin#396]
**Describe the bug**
Since version 3.10.0, npm dependencies install is failing with a `NullPointerException`.

**To Reproduce**
Run a npmInstall task in a scripted pipeline with the sample repository https://github.com/JFrog/project-examples.git, like that:
`def buildInfo = npmBuild.install args: '--verbose', path: './npm-example'`

The result will be something like that :
```
...
npm timing audit submit Completed in 1398ms
npm http fetch POST 200 http://*************/npm/npm-registry/-/npm/v1/security/audits/quick 1399ms
npm timing audit body Completed in 1ms
npm verb exit [ 0, true ]
npm timing npm Completed in 1754ms
npm info ok 
audited 19 packages in 1.535s
found 0 vulnerabilities


Dec 18, 2020 10:19:10 AM org.jfrog.build.extractor.packageManager.PackageManagerLogger error
SEVERE: null
java.lang.NullPointerException
	at org.jfrog.build.extractor.npm.extractor.NpmBuildInfoExtractor.getDependenciesMapFromBuild(NpmBuildInfoExtractor.java:335)
	at org.jfrog.build.extractor.npm.extractor.NpmBuildInfoExtractor.getDependenciesMapFromLatestBuild(NpmBuildInfoExtractor.java:325)
	at org.jfrog.build.extractor.npm.extractor.NpmBuildInfoExtractor.collectDependencies(NpmBuildInfoExtractor.java:246)
	at org.jfrog.build.extractor.npm.extractor.NpmBuildInfoExtractor.extract(NpmBuildInfoExtractor.java:81)
	at org.jfrog.build.extractor.npm.extractor.NpmInstallCi.execute(NpmInstallCi.java:62)
	at org.jfrog.build.extractor.packageManager.PackageManagerExtractor.executeAndSaveBuildInfo(PackageManagerExtractor.java:33)
	at org.jfrog.build.extractor.npm.extractor.NpmInstallCi.main(NpmInstallCi.java:90)

java.lang.NullPointerException
	at org.jfrog.build.extractor.npm.extractor.NpmBuildInfoExtractor.getDependenciesMapFromBuild(NpmBuildInfoExtractor.java:335)
	at org.jfrog.build.extractor.npm.extractor.NpmBuildInfoExtractor.getDependenciesMapFromLatestBuild(NpmBuildInfoExtractor.java:325)
	at org.jfrog.build.extractor.npm.extractor.NpmBuildInfoExtractor.collectDependencies(NpmBuildInfoExtractor.java:246)
	at org.jfrog.build.extractor.npm.extractor.NpmBuildInfoExtractor.extract(NpmBuildInfoExtractor.java:81)
	at org.jfrog.build.extractor.npm.extractor.NpmInstallCi.execute(NpmInstallCi.java:62)
 [wrapped] java.lang.RuntimeException: java.lang.NullPointerException
	at org.jfrog.build.extractor.npm.extractor.NpmInstallCi.execute(NpmInstallCi.java:65)
	at org.jfrog.build.extractor.packageManager.PackageManagerExtractor.executeAndSaveBuildInfo(PackageManagerExtractor.java:33)
	at org.jfrog.build.extractor.npm.extractor.NpmInstallCi.main(NpmInstallCi.java:90)
[Pipeline] }
[Pipeline] // stage
[Pipeline] }
[Pipeline] // node
[Pipeline] End of Pipeline
```

**Expected behavior**
A successful NpmInstall task

**Versions**
- Jenkins Artifactory plugin version: 3.10.0
- Jenkins operating system: 2.263.1
- Artifactory Version: 6.19.1

**Additional context**
Versions of nodejs used for testing : 14.15.1 (npm 6.14.9)  or 12.13.0 (npm 6.12.0)

**Comment by yahavi** [comment]
Thanks for reporting this issue, @bolivard-k.
The fix is included in the latest Jenkins Artifactory plugin 3.10.1. Feel free to upgrade.
We'd appreciate your feedback on that!

**Comment by bolivard-k** [comment]
Well done: issue fixed! 🎉
Thanks.
