### ISSUE TITLE
regression in v3.1.0 - tmpdir

### ISSUE THREAD

**Issue by mgriffin13** [jfrog/jenkins-artifactory-plugin#397]
**Describe the bug**
As described in https://github.com/jfrog/jenkins-artifactory-plugin/issues/268#issuecomment-701978735, the Artifactory plugin should not require the *exec* bit set on the tmpdir.

**To Reproduce**
Install v3.10.0 of the Artifactory plugin
Set noexec on TMPDIR
Attempt to push a docker image

**Expected behavior**
The image should be pushed.

**Stacktrace**
```java
INFO: Pushing image: <docker image>

[main] INFO io.netty.util.internal.NativeLibraryLoader - /tmp/libnetty_transport_native_epoll_x86_645122100664082345429.so exists but cannot be executed even when execute permissions set; check volume for "noexec" flag; use -Dio.netty.native.workdir=[path] to set native working directory separately.

Exception in thread "main" java.lang.UnsatisfiedLinkError: failed to load the required native library

                at io.netty.channel.epoll.Epoll.ensureAvailability(Epoll.java:79)

                at io.netty.channel.epoll.EpollEventLoop.<clinit>(EpollEventLoop.java:54)

                at io.netty.channel.epoll.EpollEventLoopGroup.newChild(EpollEventLoopGroup.java:134)

                at io.netty.channel.epoll.EpollEventLoopGroup.newChild(EpollEventLoopGroup.java:35)

                at io.netty.util.concurrent.MultithreadEventExecutorGroup.<init>(MultithreadEventExecutorGroup.java:84)

                at io.netty.util.concurrent.MultithreadEventExecutorGroup.<init>(MultithreadEventExecutorGroup.java:58)

                at io.netty.util.concurrent.MultithreadEventExecutorGroup.<init>(MultithreadEventExecutorGroup.java:47)

                at io.netty.channel.MultithreadEventLoopGroup.<init>(MultithreadEventLoopGroup.java:59)

                at io.netty.channel.epoll.EpollEventLoopGroup.<init>(EpollEventLoopGroup.java:104)

                at io.netty.channel.epoll.EpollEventLoopGroup.<init>(EpollEventLoopGroup.java:91)

                at io.netty.channel.epoll.EpollEventLoopGroup.<init>(EpollEventLoopGroup.java:68)

                at com.github.dockerjava.netty.NettyDockerCmdExecFactory$UnixDomainSocketInitializer.epollGroup(NettyDockerCmdExecFactory.java:149)

                at com.github.dockerjava.netty.NettyDockerCmdExecFactory$UnixDomainSocketInitializer.init(NettyDockerCmdExecFactory.java:141)

                at com.github.dockerjava.netty.NettyDockerCmdExecFactory.init(NettyDockerCmdExecFactory.java:114)

                at com.github.dockerjava.core.DockerClientImpl.withDockerCmdExecFactory(DockerClientImpl.java:193)

                at com.github.dockerjava.core.DockerClientBuilder.build(DockerClientBuilder.java:45)

                at org.jfrog.build.extractor.docker.DockerJavaWrapper.getDockerClient(DockerJavaWrapper.java:77)

                at org.jfrog.build.extractor.docker.DockerJavaWrapper.pushImage(DockerJavaWrapper.java:41)

                at org.jfrog.build.extractor.docker.extractor.DockerPush.execute(DockerPush.java:91)

                at org.jfrog.build.extractor.packageManager.PackageManagerExtractor.executeAndSaveBuildInfo(PackageManagerExtractor.java:33)

                at org.jfrog.build.extractor.docker.extractor.DockerPush.main(DockerPush.java:76)

Caused by: java.lang.UnsatisfiedLinkError: /tmp/libnetty_transport_native_epoll_x86_645122100664082345429.so: /tmp/libnetty_transport_native_epoll_x86_645122100664082345429.so: failed to map segment from shared object: Operation not permitted

                at java.lang.ClassLoader$NativeLibrary.load(Native Method)

                at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1941)

                at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1824)

                at java.lang.Runtime.load0(Runtime.java:809)

                at java.lang.System.load(System.java:1086)

                at io.netty.util.internal.NativeLibraryUtil.loadLibrary(NativeLibraryUtil.java:36)

                at io.netty.util.internal.NativeLibraryLoader.loadLibrary(NativeLibraryLoader.java:351)

                at io.netty.util.internal.NativeLibraryLoader.load(NativeLibraryLoader.java:205)

                at io.netty.channel.epoll.Native.loadNativeLibrary(Native.java:198)

                at io.netty.channel.epoll.Native.<clinit>(Native.java:61)

                at io.netty.channel.epoll.Epoll.<clinit>(Epoll.java:38)

                ... 20 more

                Suppressed: java.lang.UnsatisfiedLinkError: /tmp/libnetty_transport_native_epoll_x86_645122100664082345429.so: /tmp/libnetty_transport_native_epoll_x86_645122100664082345429.so: failed to map segment from shared object: Operation not permitted

                                at java.lang.ClassLoader$NativeLibrary.load(Native Method)

                                at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1941)

                                at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1824)

                                at java.lang.Runtime.load0(Runtime.java:809)

                                at java.lang.System.load(System.java:1086)

                                at io.netty.util.internal.NativeLibraryUtil.loadLibrary(NativeLibraryUtil.java:36)

                                at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

                                at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)

                                at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)

                                at java.lang.reflect.Method.invoke(Method.java:498)

                                at io.netty.util.internal.NativeLibraryLoader$1.run(NativeLibraryLoader.java:371)

                                at java.security.AccessController.doPrivileged(Native Method)

                                at io.netty.util.internal.NativeLibraryLoader.loadLibraryByHelper(NativeLibraryLoader.java:363)

                                at io.netty.util.internal.NativeLibraryLoader.loadLibrary(NativeLibraryLoader.java:341)

                                ... 24 more

                Suppressed: java.lang.UnsatisfiedLinkError: no netty_transport_native_epoll_x86_64 in java.library.path

                                at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1867)

                                at java.lang.Runtime.loadLibrary0(Runtime.java:870)

                                at java.lang.System.loadLibrary(System.java:1122)

                                at io.netty.util.internal.NativeLibraryUtil.loadLibrary(NativeLibraryUtil.java:38)

                                at io.netty.util.internal.NativeLibraryLoader.loadLibrary(NativeLibraryLoader.java:351)

                                at io.netty.util.internal.NativeLibraryLoader.load(NativeLibraryLoader.java:136)

                                ... 23 more

                                Suppressed: java.lang.UnsatisfiedLinkError: no netty_transport_native_epoll_x86_64 in java.library.path

                                                at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1867)

                                                at java.lang.Runtime.loadLibrary0(Runtime.java:870)

                                                at java.lang.System.loadLibrary(System.java:1122)

                                                at io.netty.util.internal.NativeLibraryUtil.loadLibrary(NativeLibraryUtil.java:38)

                                                at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

                                                at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)

                                                at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)

                                                at java.lang.reflect.Method.invoke(Method.java:498)

                                                at io.netty.util.internal.NativeLibraryLoader$1.run(NativeLibraryLoader.java:371)

                                                at java.security.AccessController.doPrivileged(Native Method)

                                                at io.netty.util.internal.NativeLibraryLoader.loadLibraryByHelper(NativeLibraryLoader.java:363)

                                                at io.netty.util.internal.NativeLibraryLoader.loadLibrary(NativeLibraryLoader.java:341)

                                                ... 24 more

                Suppressed: java.lang.UnsatisfiedLinkError: could not load a native library: netty_transport_native_epoll

                                at io.netty.util.internal.NativeLibraryLoader.load(NativeLibraryLoader.java:226)

                                at io.netty.channel.epoll.Native.loadNativeLibrary(Native.java:201)

                                ... 22 more

                Caused by: java.io.FileNotFoundException: META-INF/native/libnetty_transport_native_epoll.so

                                at io.netty.util.internal.NativeLibraryLoader.load(NativeLibraryLoader.java:175)

                                ... 23 more

                                Suppressed: java.lang.UnsatisfiedLinkError: no netty_transport_native_epoll in java.library.path

                                                at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1867)

                                                at java.lang.Runtime.loadLibrary0(Runtime.java:870)

                                                at java.lang.System.loadLibrary(System.java:1122)

                                                at io.netty.util.internal.NativeLibraryUtil.loadLibrary(NativeLibraryUtil.java:38)

                                                at io.netty.util.internal.NativeLibraryLoader.loadLibrary(NativeLibraryLoader.java:351)

                                                at io.netty.util.internal.NativeLibraryLoader.load(NativeLibraryLoader.java:136)

                                                ... 23 more

                                                Suppressed: java.lang.UnsatisfiedLinkError: no netty_transport_native_epoll in java.library.path

                                                                at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1867)

                                                                at java.lang.Runtime.loadLibrary0(Runtime.java:870)

                                                                at java.lang.System.loadLibrary(System.java:1122)

                                                                at io.netty.util.internal.NativeLibraryUtil.loadLibrary(NativeLibraryUtil.java:38)

                                                                at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

                                                                at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)

                                                                at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)

                                                                at java.lang.reflect.Method.invoke(Method.java:498)

                                                                at io.netty.util.internal.NativeLibraryLoader$1.run(NativeLibraryLoader.java:371)

                                                                at java.security.AccessController.doPrivileged(Native Method)

                                                                at io.netty.util.internal.NativeLibraryLoader.loadLibraryByHelper(NativeLibraryLoader.java:363)

                                                                at io.netty.util.internal.NativeLibraryLoader.loadLibrary(NativeLibraryLoader.java:341)

                                                                ... 24 more
```

**Versions**
- Jenkins Artifactory plugin version: 3.10.0
- Jenkins operating system: 2.263.1.2
- Artifactory Version: 7.11.5

**Additional context**

**Comment by Or-Geva** [comment]
@mgriffin13, thank you for reporting this issue.
I would like to share with you a snapshot, which includes a fix for this issue.
[artifactory.hpi.zip](https://github.com/jfrog/jenkins-artifactory-plugin/files/5810907/artifactory.hpi.zip)
I will appreciate your feedback on that!.

**Comment by mgriffin13** [comment]
Thanks. I'll try it out

**Comment by Or-Geva** [comment]
@mgriffin13, the fix for this issue is included in the latest Jenkins Artifactory plugin 3.10.4.
Feel free to upgrade and share your feedback.

**Comment by mgriffin13** [comment]
Thank you. Other operational issues prevented me from testing the snapshot, but I should be able to test the 3.10.4 update this week.
