### ISSUE TITLE
Pipeline generic upload stopped working

### ISSUE THREAD

**Issue by glevy** [jfrog/jenkins-artifactory-plugin#419]
**Describe the bug**
Generic upload with uploadSpec fails.

**To Reproduce**
`
node("slave"){
sh """
    mkdir test
    ls -ltr > test/test.txt
"""
def server = Artifactory.newServer url: 'http//:artifactory:8081/artifactory', credentialsId: 'XXX-XXXX-XXX'

def uploadSpec = """{
   "files": [
       {
            "pattern": "test/*.txt",
            "target": "local-lib-repo/testing/generic/upload/"
       }
    ]
}
}"""
server.upload spec: uploadSpec
`
**Expected behavior**

test.txt to be uploaded to Artifactory

**Screenshots**

`
10:37:51  java.lang.Exception: Error occurred during operation, please refer to logs for more information.
10:37:51       at org.jfrog.build.extractor.producerConsumer.ProducerConsumerExecutor.start(ProducerConsumerExecutor.java:85)
10:37:51       at org.jfrog.build.extractor.clientConfiguration.util.spec.SpecsHelper.uploadArtifactsBySpec(SpecsHelper.java:111)
10:37:51       at org.jfrog.hudson.generic.GenericArtifactsDeployer$FilesDeployerCallable.invoke(GenericArtifactsDeployer.java:157)
10:37:51  Also:   hudson.remoting.Channel$CallSiteStackTrace: Remote call to JNLP4-connect connection from 10.244.0.0/10.244.0.0:31660
10:37:51               at hudson.remoting.Channel.attachCallSiteStackTrace(Channel.java:1800)
10:37:51               at hudson.remoting.UserRequest$ExceptionResponse.retrieve(UserRequest.java:357)
10:37:51               at hudson.remoting.Channel.call(Channel.java:1001)
10:37:51               at hudson.FilePath.act(FilePath.java:1155)
10:37:51               at hudson.FilePath.act(FilePath.java:1144)
10:37:51               at org.jfrog.hudson.pipeline.common.executors.GenericUploadExecutor.execute(GenericUploadExecutor.java:57)
10:37:51               at org.jfrog.hudson.pipeline.scripted.steps.UploadStep$Execution.runStep(UploadStep.java:67)
10:37:51               at org.jfrog.hudson.pipeline.scripted.steps.UploadStep$Execution.runStep(UploadStep.java:54)
10:37:51               at org.jfrog.hudson.pipeline.ArtifactorySynchronousNonBlockingStepExecution.run(ArtifactorySynchronousNonBlockingStepExecution.java:42)
10:37:51               at org.jenkinsci.plugins.workflow.steps.SynchronousNonBlockingStepExecution.lambda$start$0(SynchronousNonBlockingStepExecution.java:47)
10:37:51               at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
10:37:51               at java.util.concurrent.FutureTask.run(FutureTask.java:266)
10:37:51               at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
10:37:51               at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
10:37:51  Caused: java.lang.RuntimeException: Failed uploading artifacts by spec
10:37:51       at org.jfrog.hudson.generic.GenericArtifactsDeployer$FilesDeployerCallable.invoke(GenericArtifactsDeployer.java:161)
10:37:51       at org.jfrog.hudson.generic.GenericArtifactsDeployer$FilesDeployerCallable.invoke(GenericArtifactsDeployer.java:108)
10:37:51       at hudson.FilePath$FileCallableWrapper.call(FilePath.java:3311)
10:37:51       at hudson.remoting.UserRequest.perform(UserRequest.java:211)
10:37:51       at hudson.remoting.UserRequest.perform(UserRequest.java:54)
10:37:51       at hudson.remoting.Request$2.run(Request.java:376)
10:37:51       at hudson.remoting.InterceptingExecutorService.lambda$wrap$0(InterceptingExecutorService.java:78)
10:37:51       at java.util.concurrent.FutureTask.run(FutureTask.java:266)
10:37:51       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
10:37:51       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
10:37:51       at hudson.remoting.Engine$1.lambda$newThread$0(Engine.java:119)
10:37:51       at java.lang.Thread.run(Thread.java:748)
10:37:51  Finished: FAILURE
`

**Versions**
- Jenkins Artifactory plugin version: 3.10.3
- Jenkins operating system: Docker lts image
- Artifactory Version: 6.3.3

**Additional context**

**Comment by glevy** [comment]
closing for now

**Comment by Kharibin** [comment]
Any continuation for this? Why closed?

**Comment by mitreab** [comment]
any updates on this? I encounter the same issue

**Comment by BroomfieldBit** [comment]
I too have the same issue.

**Comment by eyalbe4** [comment]
@BroomfieldBit,
Are you using the latest Artifactory Plugin version?
How do we reproduce this issue?
Will you be able to share a small pipeline snippet that we can use to reproduce the issue?

**Comment by BroomfieldBit** [comment]
> @BroomfieldBit, Are you using the latest Artifactory Plugin version? How do we reproduce this issue? Will you be able to share a small pipeline snippet that we can use to reproduce the issue?

Thanks for the reply. I am running plugin 3.13.2. I see 3.14.2 is available.

This is the stage that breaks in my Jenkinsfile.

`    stage('Upload to Artifactory') {
      steps {
        withCredentials([usernamePassword(credentialsId:'numbersdashesandletters', usernameVariable: 'USERNAME', passwordVariable: 'PASSWORD')]) {
          dir("${WORKDIR}") {
	          rtServer (
    	        id: 'Artifactory-1',
      	      url: 'https://internal-artifactory.com/artifactory',
    	        credentialsId: 'numbersdashesandletters',
              bypassProxy: true,
	            timeout: 60
	          )
            rtUpload (
    	        serverId: 'Artifactory-1',
              spec: '''{
                "files": [
                 {
                    "pattern": "testdir/",
                    "target": "Software/ACME/",
                    "flat" : "false",
                    "recursive": "true"
                  }
                ]
              }'''
	          )
          }
        }
      }
    }`

The following is the relevant job output. 

[Pipeline] {
[Pipeline] rtServer
[Pipeline] rtUpload
[Pipeline] }
[Pipeline] // dir
[Pipeline] }
[Pipeline] // withCredentials
[Pipeline] }
[Pipeline] // stage
[Pipeline] }
[Pipeline] // withEnv
[Pipeline] }
[Pipeline] // withEnv
[Pipeline] }
[Pipeline] // node
[Pipeline] End of Pipeline
java.lang.Exception: Error occurred during operation, please refer to logs for more information.
	at org.jfrog.build.extractor.producerConsumer.ProducerConsumerExecutor.start(ProducerConsumerExecutor.java:85)
	at org.jfrog.build.extractor.clientConfiguration.util.spec.SpecsHelper.uploadArtifactsBySpec(SpecsHelper.java:110)
	at org.jfrog.hudson.generic.GenericArtifactsDeployer$FilesDeployerCallable.invoke(GenericArtifactsDeployer.java:157)
Also:   hudson.remoting.Channel$CallSiteStackTrace: Remote call to Builder
		at hudson.remoting.Channel.attachCallSiteStackTrace(Channel.java:1797)
		at hudson.remoting.UserRequest$ExceptionResponse.retrieve(UserRequest.java:356)
		at hudson.remoting.Channel.call(Channel.java:1001)
		at hudson.FilePath.act(FilePath.java:1166)
		at hudson.FilePath.act(FilePath.java:1155)
		at org.jfrog.hudson.pipeline.common.executors.GenericUploadExecutor.execute(GenericUploadExecutor.java:56)
		at org.jfrog.hudson.pipeline.declarative.steps.generic.UploadStep$Execution.runStep(UploadStep.java:39)
		at org.jfrog.hudson.pipeline.declarative.steps.generic.UploadStep$Execution.runStep(UploadStep.java:24)
		at org.jfrog.hudson.pipeline.ArtifactorySynchronousNonBlockingStepExecution.run(ArtifactorySynchronousNonBlockingStepExecution.java:54)
		at org.jenkinsci.plugins.workflow.steps.SynchronousNonBlockingStepExecution.lambda$start$0(SynchronousNonBlockingStepExecution.java:47)
		at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
Caused: java.lang.RuntimeException: Failed uploading artifacts by spec
	at org.jfrog.hudson.generic.GenericArtifactsDeployer$FilesDeployerCallable.invoke(GenericArtifactsDeployer.java:159)
	at org.jfrog.hudson.generic.GenericArtifactsDeployer$FilesDeployerCallable.invoke(GenericArtifactsDeployer.java:108)
	at hudson.FilePath$FileCallableWrapper.call(FilePath.java:3338)
	at hudson.remoting.UserRequest.perform(UserRequest.java:212)
	at hudson.remoting.UserRequest.perform(UserRequest.java:54)
	at hudson.remoting.Request$2.run(Request.java:369)
	at hudson.remoting.InterceptingExecutorService$1.call(InterceptingExecutorService.java:72)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Finished: FAILURE

**Comment by eyalbe4** [comment]
@BroomfieldBit,
It appears that Jenkins fails uploading the specified files to Artifactory. Are you certain there isn't a connectivity issue between your Jenkins agent and Artifactory?
To verify the connectivity, you can add the connection details of Artifactory in **Manage | Configure System**  and use the **Test connection** button. Also set the **Bypass proxy** option, because I can see your pipeline script uses it.
You should also verify that the ```testdir``` directory actually exists inside the current directory.

**Comment by BroomfieldBit** [comment]
![Screenshot 2021-12-20 154818](https://user-images.githubusercontent.com/94640614/146842986-016cb823-083d-4516-b167-8c65fd1bbb5c.png)
Bypass proxy is enabled.

[user@pcs-builder repo]$ ls -l

-rw-r--r-- 1 user user 2206 Dec 20 17:46 Jenkinsfile
drwxr-xr-x 2 user user   39 Dec 20 13:07 testdir
[user@pcs-builder repo]$ ls -l testdir/

-rw-r--r-- 1 user user  0 Dec 20 13:07 test2.txt
-rw-r--r-- 1 user user 20 Dec 20 11:25 test.txt

**Comment by BroomfieldBit** [comment]
@eyalbe4 Better example in the pipeline.

[Pipeline] dir
Running in /jenkins/workspace/path/to/repo
[Pipeline] rtServer
[Pipeline] sh
+ ls -l
total 12
-rw-r--r-- 1 user user 2281 Dec 20 18:22 Jenkinsfile
drwxr-xr-x 2 user user   39 Dec 20 18:22 testdir
[Pipeline] sh
+ ls -l testdir
total 4
-rw-r--r-- 1 user user  0 Dec 20 18:22 test2.txt
-rw-r--r-- 1 user user 20 Dec 20 18:22 test.txt
[Pipeline] sh
+ pwd
/jenkins/workspace/path/to/repo
[Pipeline] rtUpload
[Pipeline] }
[Pipeline] // dir
[Pipeline] }
[Pipeline] // withCredentials
[Pipeline] }
[Pipeline] // stage
[Pipeline] }
[Pipeline] // withEnv
[Pipeline] }
[Pipeline] // withEnv
[Pipeline] }
[Pipeline] // node
[Pipeline] End of Pipeline
java.lang.Exception: Error occurred during operation, please refer to logs for more information.
	at org.jfrog.build.extractor.producerConsumer.ProducerConsumerExecutor.start(ProducerConsumerExecutor.java:85)
	at org.jfrog.build.extractor.clientConfiguration.util.spec.SpecsHelper.uploadArtifactsBySpec(SpecsHelper.java:110)
	at org.jfrog.hudson.generic.GenericArtifactsDeployer$FilesDeployerCallable.invoke(GenericArtifactsDeployer.java:157)
Also:   hudson.remoting.Channel$CallSiteStackTrace: Remote call to 017-Builder
		at hudson.remoting.Channel.attachCallSiteStackTrace(Channel.java:1797)
		at hudson.remoting.UserRequest$ExceptionResponse.retrieve(UserRequest.java:356)
		at hudson.remoting.Channel.call(Channel.java:1001)
		at hudson.FilePath.act(FilePath.java:1166)
		at hudson.FilePath.act(FilePath.java:1155)
		at org.jfrog.hudson.pipeline.common.executors.GenericUploadExecutor.execute(GenericUploadExecutor.java:56)
		at org.jfrog.hudson.pipeline.declarative.steps.generic.UploadStep$Execution.runStep(UploadStep.java:39)
		at org.jfrog.hudson.pipeline.declarative.steps.generic.UploadStep$Execution.runStep(UploadStep.java:24)
		at org.jfrog.hudson.pipeline.ArtifactorySynchronousNonBlockingStepExecution.run(ArtifactorySynchronousNonBlockingStepExecution.java:54)
		at org.jenkinsci.plugins.workflow.steps.SynchronousNonBlockingStepExecution.lambda$start$0(SynchronousNonBlockingStepExecution.java:47)
		at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
Caused: java.lang.RuntimeException: Failed uploading artifacts by spec
	at org.jfrog.hudson.generic.GenericArtifactsDeployer$FilesDeployerCallable.invoke(GenericArtifactsDeployer.java:159)
	at org.jfrog.hudson.generic.GenericArtifactsDeployer$FilesDeployerCallable.invoke(GenericArtifactsDeployer.java:108)
	at hudson.FilePath$FileCallableWrapper.call(FilePath.java:3338)
	at hudson.remoting.UserRequest.perform(UserRequest.java:212)
	at hudson.remoting.UserRequest.perform(UserRequest.java:54)
	at hudson.remoting.Request$2.run(Request.java:369)
	at hudson.remoting.InterceptingExecutorService$1.call(InterceptingExecutorService.java:72)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Finished: FAILURE

**Comment by eyalbe4** [comment]
@BroomfieldBit,
You can consider opening a ticket to JFrog Support. They may be able to help you pinpoint the cause of the issue.

**Comment by BroomfieldBit** [comment]
@eyalbe4 , okay. Thank you for your time and attention.
