### ISSUE TITLE
Null pointer exception after calling collect function outside of pipeline {} declaration code

### ISSUE THREAD

**Issue by JayanthSureshjfrog** [jfrog/jenkins-artifactory-plugin#431]
In the latest version of Jenkins Artifactory Plugin (3.10.5) , when collect() function is called outside of pipeline {} declaration code, the pipeline is failing with _java.lang.NullPointerException_. However, the same will work in Jenkins Artifactory Plugin 3.6.1 version.

**Steps to Reproduce:**
1. Run the below pipeline script in Jenkins with Jenkins Artifactory Plugin (3.10.5)
_#!/usr/bin/env groovy
def setupBuildInfo()
{
   def buildInfo = Artifactory.newBuildInfo()
   buildInfo.env.capture = true
   buildInfo.env.collect()
   return buildInfo
}
def BUILD_INFO = setupBuildInfo()
pipeline {
 agent {
   any {
     inheritFrom 'k8s-build'
   }
 }
 stages {
   stage('get build info') {
     steps {
       script {
         //use BUILD_INFO in the stage
         println(BUILD_INFO)
       }
     }
   }
 }
}_

**Output:**
_Running in Durability level: MAX_SURVIVABILITY
[Pipeline] Start of Pipeline
[Pipeline] newBuildInfo
[Pipeline] collectEnv
[Pipeline] End of Pipeline
java.lang.NullPointerException
	at org.jfrog.hudson.pipeline.common.executors.CollectEnvExecutor.execute(CollectEnvExecutor.java:31)
	at org.jfrog.hudson.pipeline.scripted.steps.CollectEnvStep$Execution.runStep(CollectEnvStep.java:44)
	at org.jfrog.hudson.pipeline.scripted.steps.CollectEnvStep$Execution.runStep(CollectEnvStep.java:31)
	at org.jfrog.hudson.pipeline.ArtifactorySynchronousNonBlockingStepExecution.run(ArtifactorySynchronousNonBlockingStepExecution.java:42)
	at org.jenkinsci.plugins.workflow.steps.SynchronousNonBlockingStepExecution.lambda$start$0(SynchronousNonBlockingStepExecution.java:47)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Finished: FAILURE_

**Expected behavior**
The same script will run successfully in Jenkins Artifactory Plugin 3.6.1 version and below will be the output.
**Expected Output:**
_Running in Durability level: MAX_SURVIVABILITY
[Pipeline] Start of Pipeline
[Pipeline] newBuildInfo
[Pipeline] collectEnv
[Pipeline] node
Running on Jenkins in /var/lib/jenkins/workspace/collection-test
[Pipeline] {
[Pipeline] stage
[Pipeline] { (get build info)
[Pipeline] script
[Pipeline] {
[Pipeline] echo
org.jfrog.hudson.pipeline.common.types.buildInfo.BuildInfo@739bb151
[Pipeline] }
[Pipeline] // script
[Pipeline] }
[Pipeline] // stage
[Pipeline] }
[Pipeline] // node
[Pipeline] End of Pipeline
Finished: SUCCESS_

**Versions**
- Jenkins Artifactory plugin version: 3.10.5
- Jenkins operating system: Ubuntu 18.04
- Artifactory Version: 7.15.3

**Comment by Or-Geva** [comment]
@JayanthSureshjfrog, The example you mention is a bit odd.
Could you explain why is there a groovy code outside of the agent block? what sense does it make to collect env outside the agent block?
Moreover, The `Jenkins Artifactory Plugin 3.6.1` had a bug in which `buildInfo.env.collect()` collects the master's env vars regardless of the agent from which it was invoked.
The fix for this issue came on version 3.10.5.

**Comment by mwolniewicz** [comment]
Hi, the groovy code is outside the agent block, so it can be used among all stages defined in pipeline. It can be of course executed inside one of the stages (then the code works) but it will require creation of an additional stage to just initialize the values. The ticket was created, because in previous Jenkins Artifactory Plugin 3.6.1 this functionality just worked. So my question is, do you support execution of buildInfo.env.collect() outside pipeline block?

**Comment by eyalbe4** [comment]
@mwolniewicz,
Since ```buildInfo.env.collect()``` collects the environment variables from the build agent, it needs to know which build agent to collect the environment variables from. I'm therefore not sure running this method should be allowed from outside of an agent scope. 
Doing so however should prompt a clear error message.
Please let us know what you think.

**Comment by mwolniewicz** [comment]
If the function need to run inside pipeline / agent block that's fine, but as you pointed out the error message should be clear and not return java.lang.NullPointerException.

**Comment by mwolniewicz** [comment]
@eyalbe4 is there any update on this?
