### ISSUE TITLE
Maven/Tycho build missing .polyglot.build.properties

### ISSUE THREAD

**Issue by jmorcate** [jfrog/jenkins-artifactory-plugin#450]
My build is failing with the following message:
```
ava.lang.IllegalArgumentException: File not found: /var/jenkins_home/workspace/acme/acme/.polyglot.build.properties
	at org.jfrog.build.extractor.clientConfiguration.deploy.DeployDetails$Builder.build(DeployDetails.java:142)
	at org.jfrog.hudson.pipeline.common.types.buildInfo.BuildInfo$DeployPathsAndPropsCallable.lambda$invoke$0(BuildInfo.java:378)
	at java.util.LinkedHashMap.forEach(LinkedHashMap.java:684)
	at org.jfrog.hudson.pipeline.common.types.buildInfo.BuildInfo$DeployPathsAndPropsCallable.invoke(BuildInfo.java:368)
	at org.jfrog.hudson.pipeline.common.types.buildInfo.BuildInfo$DeployPathsAndPropsCallable.invoke(BuildInfo.java:344)
	at hudson.FilePath.act(FilePath.java:1164)
	at hudson.FilePath.act(FilePath.java:1147)
	at org.jfrog.hudson.pipeline.common.types.buildInfo.BuildInfo.getAndAppendDeployableArtifactsByModule(BuildInfo.java:210)
	at org.jfrog.hudson.pipeline.common.executors.MavenExecutor.execute(MavenExecutor.java:83)
	at org.jfrog.hudson.pipeline.declarative.steps.maven.MavenStep$Execution.runStep(MavenStep.java:95)
	at org.jfrog.hudson.pipeline.declarative.steps.maven.MavenStep$Execution.runStep(MavenStep.java:80)
	at org.jfrog.hudson.pipeline.ArtifactorySynchronousNonBlockingStepExecution.run(ArtifactorySynchronousNonBlockingStepExecution.java:54)
	at org.jenkinsci.plugins.workflow.steps.SynchronousNonBlockingStepExecution.lambda$start$0(SynchronousNonBlockingStepExecution.java:47)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Finished: FAILURE
```
All my efforts for forcing the plugin to ignore this file have been ignored.  In fact, most of the modifications I have done are ignored. For example, if I change the IP of the server, the build fails at the same point with the same message. This is my Jenkinsfile:
```
node {
    def server
    def rtMaven
    def buildInfo
    stage("Prepare ...") {
        checkout([
            $class: 'GitSCM', 
            branches: [[name: '*/master']], 
            extensions: [
                [$class: 'RelativeTargetDirectory', relativeTargetDir: '.']
            ], 
            userRemoteConfigs: [
                [url: 'http://bitbucket:7990/scm/acme/acme-releng.git']
            ]
        ])
        checkout([
            $class: 'GitSCM', 
            branches: [[name: '*/master']], 
            extensions: [
                [$class: 'RelativeTargetDirectory', relativeTargetDir: 'acme']
            ], 
            userRemoteConfigs: [
                [url: 'http://bitbucket:7990/scm/acme/acme.git']
            ]
        ])
    }
    stage("Configure ...") {
	    server = rtServer (
		    id: 'acn-artifactory-server',
		    url: 'http://192.168.178.26:8082/artifactory',
		    username: 'admin',
		    password: 'password',
		    timeout: 300
	    )
	    rtMaven = Artifactory.newMavenBuild();


        rtMaven.resolver server: server, releaseRepo: 'acn-libs-release', snapshotRepo: 'acn-libs-snapshot'
        rtMaven.deployer server: server, releaseRepo: 'acn-libs-release-local', snapshotRepo: 'acn-libs-snapshot-local'

        rtMaven.deployer.artifactDeploymentPatterns.addExclude('acme/acme/.polyglot.build.properties')

        rtMaven.deployer.threads = 3      
        rtMaven.deployer.deployArtifacts = true  
    }

    stage ('Build ...') {
        buildInfo = rtMavenRun (
            tool: 'Maven 3.6.3', 
            pom: './pom.xml',
            goals: 'clean install')
        
    }
}
```

**Comment by yahavi** [comment]
@jmorcate,
It looks like you mixed between [scripted](https://www.jfrog.com/confluence/display/JFROG/Scripted+Pipeline+Syntax) and [declarative](https://www.jfrog.com/confluence/display/JFROG/declarative+Pipeline+Syntax) pipelines syntaxes. 
In most of your pipeline you are using the scripted syntax, but rtServer and rtMavenRun are declarative.

Try to switch the `rtServer` step to the following: 
```groovy
def server = Artifactory.newServer url: 'http://192.168.178.26:8082/artifactory', username: 'admin', password: 'password'
```
Also, please switch `rtMavenRun` to these 2 lines:
```groovy
rtMaven.tool = 'Maven 3.6.3'
rtMaven.run pom: './pom.xml', goals: 'clean install'
```

See relevant documentation here: https://www.jfrog.com/confluence/display/JFROG/Scripted+Pipeline+Syntax#ScriptedPipelineSyntax-MavenBuildswithArtifactory

You can find an example here: https://github.com/jfrog/project-examples/blob/master/jenkins-examples/pipeline-examples/scripted-examples/maven-example/Jenkinsfile

Please let us know if it helped.

**Comment by jmorcate** [comment]
@yahavi

Ok, the solution is not to exclude, but to include, 
```
rtMaven.deployer.artifactDeploymentPatterns.addInclude('*.jar')
```

**Comment by yahavi** [comment]
@jmorcate
Thanks for your feedback. I'm glad to know you managed to solve it out.

This exclude pattern should also work:
```groovy
rtMaven.deployer.artifactDeploymentPatterns.addExclude('*.polyglot.build.properties')
```

Please notice that the include/exclude patterns calculated from the local Maven repository (from which your project is installed), usually the `$USER_HOME/.m2` path.

Please let us know if there is anything we can do to help.

**Comment by TIBCOrkrajews** [comment]
So why does '*.polyglot.build.properties' work? Is it actually matching againt `g/a/c/foo/whatever.polyglot.properties` and not just `whatever.polyglot.properties` ?
