### ISSUE TITLE
Plugin doesn't support npm 7.7.x

### ISSUE THREAD

**Issue by fdolsky321** [jfrog/jenkins-artifactory-plugin#470]
Using `rtNpm` doesn't work for npm version 7.7.x. I'm getting error:
```
18:04:58  npm ERR! code ENOWORKSPACES
18:04:58  npm ERR! This command does not support workspaces.
18:04:58  npm verb exit 1
18:04:58  npm timing npm Completed in 271ms
18:04:58  npm verb code 1
18:04:58  
18:04:58  npm ERR! A complete log of this run can be found in:
18:04:58  npm ERR!     /opt/jenkins/.npm/_logs/2021-05-12T16_04_58_862Z-debug.log
18:04:58  
18:04:58  	at org.jfrog.build.extractor.npm.extractor.NpmInstallCi.execute(NpmInstallCi.java:65)
18:04:58  	at org.jfrog.build.extractor.packageManager.PackageManagerExtractor.executeAndSaveBuildInfo(PackageManagerExtractor.java:33)
18:04:58  	at org.jfrog.build.extractor.npm.extractor.NpmInstallCi.main(NpmInstallCi.java:90)
```

**To Reproduce**
Just use npm version 7.7.x and running command:
`def buildInfo = rtNpm.install path: '.', args: '--verbose'`

**Expected behavior**
NPM packages installation will run successfully for npm version 7.7.x

**Versions**
- Jenkins Artifactory plugin version: 3.10.6
- Jenkins operating system: Ubuntu 20.04 running in Docker
- Artifactory Version: Artifactory Enterprise, 6.10.7

**Additional context**
Looks like this bug was already reported AND solved in JFrog CLI - https://github.com/jfrog/jfrog-cli/issues/1030
by this commit - https://github.com/jfrog/jfrog-cli-core/commit/cff076fd0db7bf400c041a8d80f555af1c646f79

**Comment by asafgabai** [comment]
Hi @fdolsky321,
Thank you for reporting this issue.
It was fixed and merged ([jfrog/build-info#484](https://github.com/jfrog/build-info/pull/484)), and is going to be released by the end of next week.

**Comment by fdolsky321** [comment]
> Hi @fdolsky321,
> Thank you for reporting this issue.
> It was fixed and merged ([jfrog/build-info#484](https://github.com/jfrog/build-info/pull/484)), and is going to be released by the end of next week.

Thank you so much!

**Comment by Or-Geva** [comment]
@fdolsky321, Jenkins-Artifactory-Plugin 3.11.0 is released!!.
Feel free to upgrade and share your feedback.
