### ISSUE TITLE
java.io.IOException: Issues Collection Failed: Git log command failed: fatal: Invalid revision range 1ccb1db82634d99f21823s1e225237406c895f26..

### ISSUE THREAD

**Issue by mksha** [jfrog/jenkins-artifactory-plugin#480]
**Describe the bug**
Plugin failed to publish the issues to artifactory when using muti-branch pipeline with PRs. When triggering PR build , it failed to publish the issues to Artifactory.

**To Reproduce**
1. Create a multi-branch pipeline in jenkins with PR enabled.
2. Trigger the build using PR and try to publish the issues to artifactory.
3. It will collect the issues but when try to publish it fails because of revision range is wrong.

**Expected behavior**
Should be able to publish the issues for PRs also in multi-branch pipeline

**Versions**
- Jenkins Artifactory plugin version: 3.10
- Jenkins operating system: Linux
- Artifactory Version: 6.5.9

**Additional context**

`Also: hudson.remoting.Channel$CallSiteStackTrace: Remote call to JNLP4-connect connection from 10.108.251.177/10.108.251.177:60078
 at hudson.remoting.Channel.attachCallSiteStackTrace(Channel.java:1800)
 at hudson.remoting.UserRequest$ExceptionResponse.retrieve(UserRequest.java:356)
 at hudson.remoting.Channel.call(Channel.java:1001)
 at hudson.FilePath.act(FilePath.java:1158)
 at hudson.FilePath.act(FilePath.java:1147)
 at org.jfrog.hudson.pipeline.common.executors.CollectIssuesExecutor.execute(CollectIssuesExecutor.java:49)
 at org.jfrog.hudson.pipeline.scripted.steps.CollectIssuesStep$Execution.runStep(CollectIssuesStep.java:57)
 at org.jfrog.hudson.pipeline.scripted.steps.CollectIssuesStep$Execution.runStep(CollectIssuesStep.java:41)
 at org.jfrog.hudson.pipeline.ArtifactorySynchronousNonBlockingStepExecution.run(ArtifactorySynchronousNonBlockingStepExecution.java:42)
 at org.jenkinsci.plugins.workflow.steps.SynchronousNonBlockingStepExecution.lambda$start$0(SynchronousNonBlockingStepExecution.java:47)
 at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
 at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
 at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
 at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
 at java.base/java.lang.Thread.run(Thread.java:829)
java.io.IOException: Issues Collection Failed: Git log command failed: fatal: Invalid revision range 1ccb1db82634d99f2182323bcc5237406c895f26..

 at org.jfrog.build.extractor.issuesCollection.IssuesCollector.getGitLog(IssuesCollector.java:144)
 at org.jfrog.build.extractor.issuesCollection.IssuesCollector.doCollect(IssuesCollector.java:91)
 at org.jfrog.build.extractor.issuesCollection.IssuesCollector.collectIssues(IssuesCollector.java:45)
 at org.jfrog.hudson.pipeline.common.executors.CollectIssuesExecutor$CollectIssuesCallable.invoke(CollectIssuesExecutor.java:82)
 at org.jfrog.hudson.pipeline.common.executors.CollectIssuesExecutor$CollectIssuesCallable.invoke(CollectIssuesExecutor.java:62)
 at hudson.FilePath$FileCallableWrapper.call(FilePath.java:3314)
 at hudson.remoting.UserRequest.perform(UserRequest.java:211)
 at hudson.remoting.UserRequest.perform(UserRequest.java:54)
 at hudson.remoting.Request$2.run(Request.java:376)
 at hudson.remoting.InterceptingExecutorService.lambda$wrap$0(InterceptingExecutorService.java:78)
 at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
 at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
 at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
 at hudson.remoting.Engine$1.lambda$newThread$0(Engine.java:119)
 at java.base/java.lang.Thread.run(Thread.java:834)`

**Comment by mksha** [comment]
@yoshaul can you pls take a look?
