### ISSUE TITLE
Artifactory Publish with Unrecognized field "deploySucceeded" (class org.jfrog.build.client.DeployableArtifactDetail), not marked as ignorable

### ISSUE THREAD

**Issue by dhaval-vithalani** [jfrog/jenkins-artifactory-plugin#522]
**Describe the bug**
Artifactory Publish post upgrade to latest jenkins-artifactory-plugin (3.11.4)

**To Reproduce**
Artifactory Publish through Jenkins artifactory plugin. 
```
hudson.remoting.ProxyException: com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "deploySucceeded" (class org.jfrog.build.client.DeployableArtifactDetail), not marked as ignorable (3 known properties: "sourcePath", "artifactDest", "sha1"])
 at [Source: (File); line: 1, column: 473] (through reference chain: java.util.LinkedHashMap["charging-operations-models"]->java.util.ArrayList[0]->org.jfrog.build.client.DeployableArtifactDetail["deploySucceeded"])
	at com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException.from(UnrecognizedPropertyException.java:61)
	at com.fasterxml.jackson.databind.DeserializationContext.handleUnknownProperty(DeserializationContext.java:987)
	at com.fasterxml.jackson.databind.deser.std.StdDeserializer.handleUnknownProperty(StdDeserializer.java:1974)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownProperty(BeanDeserializerBase.java:1701)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownVanilla(BeanDeserializerBase.java:1679)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:330)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:187)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer._deserializeFromArray(CollectionDeserializer.java:355)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:244)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:28)
	at com.fasterxml.jackson.databind.deser.std.MapDeserializer._readAndBindStringKeyMap(MapDeserializer.java:609)
	at com.fasterxml.jackson.databind.deser.std.MapDeserializer.deserialize(MapDeserializer.java:437)
	at com.fasterxml.jackson.databind.deser.std.MapDeserializer.deserialize(MapDeserializer.java:32)
	at com.fasterxml.jackson.databind.deser.DefaultDeserializationContext.readRootValue(DefaultDeserializationContext.java:322)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4593)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3433)
	at org.jfrog.build.extractor.clientConfiguration.deploy.DeployableArtifactsUtils.loadDeployableArtifactsByModuleFromFile(DeployableArtifactsUtils.java:63)
	at org.jfrog.build.extractor.clientConfiguration.deploy.DeployableArtifactsUtils.loadDeployableArtifactsFromFile(DeployableArtifactsUtils.java:51)
	at org.jfrog.hudson.pipeline.common.types.buildInfo.BuildInfo$DeployPathsAndPropsCallable.invoke(BuildInfo.java:370)
	at org.jfrog.hudson.pipeline.common.types.buildInfo.BuildInfo$DeployPathsAndPropsCallable.invoke(BuildInfo.java:349)
	at hudson.FilePath$FileCallableWrapper.call(FilePath.java:3314)
	at hudson.remoting.UserRequest.perform(UserRequest.java:211)
	at hudson.remoting.UserRequest.perform(UserRequest.java:54)
	at hudson.remoting.Request$2.run(Request.java:376)
	at hudson.remoting.InterceptingExecutorService.lambda$wrap$0(InterceptingExecutorService.java:78)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at hudson.remoting.Engine$1.lambda$newThread$0(Engine.java:119)
	at java.lang.Thread.run(Thread.java:748)
```

**Expected behavior**
Artifactory publish with buildinfo should as expected 

**Screenshots**

**Versions**
- Jenkins Artifactory plugin version: 3.11.4
- Jenkins operating system: 2.227.4
- Artifactory Version: 6.18.1

**Additional context**
<img width="1079" alt="Screenshot 2021-06-30 at 12 40 40" src="https://user-images.githubusercontent.com/47561233/123947235-753f2780-d9a0-11eb-9bc7-fb65e66d1733.png">

**Comment by yahavi** [comment]
@dhaval-vithalani,
Jenkins Artifactory plugin 3.12.1 is released.
This version should include a fix for this issue.
We'd appreciate your feedback on that.

**Comment by eugenezarianov** [comment]
We have faced the similar issue once more. 

Jenkins version: 2.289.2
Jenkins Artifactory plugin version: 3.12.4
Error message is as follows: 

`hudson.remoting.ProxyException: com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "targetRepository" (class org.jfrog.build.client.DeployableArtifactDetail), not marked as ignorable (5 known properties: "sourcePath", "deploySucceeded", "artifactDest", "sha1", "sha256"])
 at [Source: (File); line: 1, column: 529] (through reference chain: java.util.LinkedHashMap["charging-notification-java-client"]->java.util.ArrayList[0]->org.jfrog.build.client.DeployableArtifactDetail["targetRepository"])
	at com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException.from(UnrecognizedPropertyException.java:61)
	at com.fasterxml.jackson.databind.DeserializationContext.handleUnknownProperty(DeserializationContext.java:987)
	at com.fasterxml.jackson.databind.deser.std.StdDeserializer.handleUnknownProperty(StdDeserializer.java:1974)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownProperty(BeanDeserializerBase.java:1701)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownVanilla(BeanDeserializerBase.java:1679)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:330)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:187)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer._deserializeFromArray(CollectionDeserializer.java:355)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:244)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:28)
	at com.fasterxml.jackson.databind.deser.std.MapDeserializer._readAndBindStringKeyMap(MapDeserializer.java:609)
	at com.fasterxml.jackson.databind.deser.std.MapDeserializer.deserialize(MapDeserializer.java:437)
	at com.fasterxml.jackson.databind.deser.std.MapDeserializer.deserialize(MapDeserializer.java:32)
	at com.fasterxml.jackson.databind.deser.DefaultDeserializationContext.readRootValue(DefaultDeserializationContext.java:322)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4593)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3433)
	at org.jfrog.build.extractor.clientConfiguration.deploy.DeployableArtifactsUtils.loadDeployableArtifactsByModuleFromFile(DeployableArtifactsUtils.java:65)
	at org.jfrog.build.extractor.clientConfiguration.deploy.DeployableArtifactsUtils.loadDeployableArtifactsFromFile(DeployableArtifactsUtils.java:53)
	at org.jfrog.hudson.pipeline.common.types.buildInfo.BuildInfo$DeployPathsAndPropsCallable.invoke(BuildInfo.java:370)
	at org.jfrog.hudson.pipeline.common.types.buildInfo.BuildInfo$DeployPathsAndPropsCallable.invoke(BuildInfo.java:349)
	at hudson.FilePath$FileCallableWrapper.call(FilePath.java:3317)
	at hudson.remoting.UserRequest.perform(UserRequest.java:211)
	at hudson.remoting.UserRequest.perform(UserRequest.java:54)
	at hudson.remoting.Request$2.run(Request.java:376)
	at hudson.remoting.InterceptingExecutorService.lambda$wrap$0(InterceptingExecutorService.java:78)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at hudson.remoting.Engine$1.lambda$newThread$0(Engine.java:119)
	at java.lang.Thread.run(Thread.java:748)`

**Comment by dhaval-vithalani** [comment]
@yahavi

**Comment by yahavi** [comment]
@eugenezarianov @dhaval-vithalani 
Thanks for reporting this issue!
We created https://github.com/jfrog/build-info/pull/537 to resolve it.

**Comment by yahavi** [comment]
@dhaval-vithalani 
Jenkins Artifactory plugin 3.12.5 is released.
This version includes a fix for this issue.
We'd appreciate your feedback on that.
