### ISSUE TITLE
Allow plugin to run all tasks in a Docker container

### ISSUE THREAD

**Issue by gangefors** [jfrog/jenkins-artifactory-plugin#536]
I will use the PipBuild.install task as an example, but this is true for other tasks as well.

**Is your feature request related to a problem? Please describe.**
Currently PipBuild.install needs to be run directly on the Jenkins worker due to it spawning a new java process to do its thing. This it not very flexible since many jobs today is run inside Docker images to get a definitive and clean workspace. Not allowing the PipBuild.install to work inside Docker containers limits the usability of the plugin to a great degree.

**Describe the solution you'd like to see**
I want to be able to collect dependency data for Python builds while running my steps inside arbitrary Docker containers.

**Describe alternatives you've considered**
The only other alternative is to use the Jfrog CLI in the Docker container, but this instead means that we need to build images with that tool installed. There is also the overhead of configuring the CLI properly with auth and resolvers directly through the shell instead of using the Jenkins plugin.

**Additional context**
The same issue is most likely present for Npm and NuGet tasks as well since the documentation indicates that it spawns a new java process.

**Comment by yahavi** [comment]
@gangefors,
One of the reasons for the spawned Java process is to run the plugin code inside the Docker container.
The code runs inside a Docker container **only if** it spawns a new process. The reason for that is that the Docker plugin must get a shell command to run in the created container. Otherwise, it will execute the Jenkins Artifactory plugin code in the host agent.
Running the JFrog CLI spawns a new `sh` process (`sh "jfrog rt ..."`) therefore it runs inside a Docker container as expected.

To run builds inside a Docker container, please make sure to use an image with Java.

**Examples:**
Scripted pipeline:
```groovy
docker.image('image-name').inside {
    rtPip.install ...
}
```
Decalarative pipeline:
```groovy
agent {
    docker { image 'image-name' }
}
...
stage('Exec pip install') {
    steps {
        rtPipInstall(
            ...
        )
    }
}
```
More examples:
1. https://github.com/jfrog/project-examples/blob/master/jenkins-examples/pipeline-examples/declarative-examples/npm-container-example/Jenkinsfile
2. https://github.com/jfrog/project-examples/tree/master/jenkins-examples/pipeline-examples/scripted-examples/gradle-container-example
3. https://github.com/jfrog/project-examples/tree/master/jenkins-examples/pipeline-examples/scripted-examples/maven-container-example
4. https://github.com/jfrog/project-examples/blob/master/jenkins-examples/pipeline-examples/scripted-examples/npm-container-example/Jenkinsfile


Please let me know if that helped.

**Comment by gangefors** [comment]
Could you help me understanding why I get this error? Looks to me like it is trying to launch a java process inside the container, where I don't have java since I am building python stuff.

```
[Pipeline] artifactoryPipRun
[hon-ci-example_python-ci-example] $ docker exec --env ******** [...] 52659cfeaee12045cf909c00fbbde8dc1d79db87517e6de7b9dc64599bd1aa40 java -cp /home/svcj/workspace/hon-ci-example_python-ci-example-tmp/artifactory/cache/artifactory-plugin/3.10.0/* org.jfrog.build.extractor.pip.extractor.PipInstall
OCI runtime exec failed: exec failed: container_linux.go:349: starting container process caused "exec: \"java\": executable file not found in $PATH": unknown
[Pipeline] }
[Pipeline] // stage
[Pipeline] }
$ docker stop --time=1 52659cfeaee12045cf909c00fbbde8dc1d79db87517e6de7b9dc64599bd1aa40
$ docker rm -f 52659cfeaee12045cf909c00fbbde8dc1d79db87517e6de7b9dc64599bd1aa40
[Pipeline] // withDockerContainer
[Pipeline] }
[Pipeline] // node
[Pipeline] End of Pipeline
java.lang.RuntimeException: pip build failed
	at org.jfrog.hudson.pipeline.common.Utils.launch(Utils.java:234)
	at org.jfrog.hudson.pipeline.common.executors.BuildInfoProcessRunner.execute(BuildInfoProcessRunner.java:56)
	at org.jfrog.hudson.pipeline.common.executors.PipInstallExecutor.execute(PipInstallExecutor.java:43)
	at org.jfrog.hudson.pipeline.scripted.steps.PipInstallStep$Execution.run(PipInstallStep.java:51)
	at org.jfrog.hudson.pipeline.scripted.steps.PipInstallStep$Execution.run(PipInstallStep.java:38)
	at org.jenkinsci.plugins.workflow.steps.SynchronousNonBlockingStepExecution.lambda$start$0(SynchronousNonBlockingStepExecution.java:47)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Finished: FAILURE
```

```
def rtServer = Artifactory.newServer(
    url: 'https://api',
    credentialsId: auth',
)
def rtBuildInfo = Artifactory.newBuildInfo()
def rtPip = Artifactory.newPipBuild()
rtPip.resolver repo: 'pypi-virtual', server: rtServer

node('docker-build-quick') {
    deleteDir()
    checkout scm
    docker.image('python:3').inside() {
        stage('pip install') {
            rtPip.install buildInfo: rtBuildInfo, args: "-r artifactory-python-ci-example/requirements.txt"
        }
    }
}
```

**Comment by yahavi** [comment]
@gangefors, it looks like your container doesn't have Java installed:
> OCI runtime exec failed: exec failed: container_linux.go:349: starting container process caused "exec: \"java\": executable file not found in $PATH": unknown

Please make sure to use a Docker image with Java. 
Alternatively, you can install Java before running `rtPip.install`:
```
docker.image('python:3').inside() {
    stage('install java') {
        ...
    }
    stage('pip install') {
        withEnv(['JAVA_HOME=<container-java-home-path>']) {
            rtPip.install buildInfo: rtBuildInfo, args: "-r artifactory-python-ci-example/requirements.txt"
        }
    }    
}
```

**Comment by gangefors** [comment]
See my edit in previous comment.

Java should not be a requirement to build Python packages.

**Comment by yahavi** [comment]
@gangefors thanks for your feedback.
Unfortunately, this is a technical limitation we currently have.
However, we are open to implementation suggestions.

**Comment by glevy** [comment]
@gangefors, did you try to create a volume pointing to a java installation on the host and set the JAVA_HOME environment variable while inside the container?

**Comment by gangefors** [comment]
@glevy No, we did not. We do not want to rely on a plugin that can't run in a minimal docker container. Adding java by installation or by bind mounting is not an acceptable solution for us.

Our solution was instead to use the jfrog cli client and its wrapping around pip to collect dependencies and submit build info. We created a few functions in groovy that we can call with a closure. These functions takes care of downloading and setting up the jfrog cli client to create an environment that can be used by commands in the closure.

So basically these functions
```groovy
def withJfrogCli(String credentialId, Closure script) {
    // Configure Jfrog CLI environment
    env.JFROG_CLI_BUILD_NAME = env.JOB_NAME
    env.JFROG_CLI_BUILD_NUMBER = env.BUILD_NUMBER
    env.JFROG_CLI_BUILD_URL = env.BUILD_URL
    env.JFROG_CLI_ENV_EXCLUDE = '*password*;*psw*;*secret*;*key*;*token*;*pwd*'
    env.JFROG_CLI_HOME_DIR = "${env.WORKSPACE}/.jfrog"

    // Install Jfrog CLI binary in $WORKSPACE
    // Creates the Jfrog client home dir, downloads a fixed version,
    // confirms the checksum and makes the binary executable.
    // Updating the client is done be changing the URL and checksum.
    def installJfrogCli = '''
        mkdir -p $JFROG_CLI_HOME_DIR &&
        curl -sL https://<artifactory>/artifactory/releases.jfrog.io-remote/artifactory/jfrog-cli/v2/2.1.1/jfrog-cli-linux-amd64/jfrog > $WORKSPACE/jfrog &&
        echo "164058d0e670455f8c783d2923d9f072c01f1ee598abeea29487859f1464aef0 $WORKSPACE/jfrog" |\
            sha256sum -c &&
        chmod u+x $WORKSPACE/jfrog &&
        $WORKSPACE/jfrog --version
    '''.stripIndent()
    sh installJfrogCli
    // Add Artifactory server configuration
    env.CI = 'true'
    withCredentials([
        usernamePassword(
            credentialsId: credentialId,
            passwordVariable: 'ARTIFACTORY_PASSWORD',
            usernameVariable: 'ARTIFACTORY_USERNAME',
        ),
    ]) {
        sh '''
            $WORKSPACE/jfrog config add art --overwrite --url=https://<artifactory> \
                --user=$ARTIFACTORY_USERNAME --password=$ARTIFACTORY_PASSWORD
        '''.stripIndent()
        sh '$WORKSPACE/jfrog config show'
    }
    try {
        script()
    }
    finally {
        // Remove configuration
        sh '$WORKSPACE/jfrog config rm'
    }
}

def jfrogCliPublishPythonPackage(givenArgs = [:]) {
    def args = [
            'repoName' : '',
            'packageName' : '',
            'srcPath' : 'dist/',
            'dstSubPath' : '',
            'requirementsFile' : '',
    ] + givenArgs
    assert args.repoName, 'Required argument `repoName` missing.'
    assert args.packageName, 'Required argument `packageName` missing.'
    // Register dependencies in build info
    if (args.requirementsFile) {
        // Configure PyPi resolver
        sh '$WORKSPACE/jfrog rt pip-config --repo-resolve all-pypi --server-id-resolve art'
        // To register all dependencies in the build info we need to run the
        // `rt pip-install` command with requirements.txt.
        // This will be done in a local venv created for just this purpose.
        sh """
            rm -rf \$JFROG_CLI_HOME_DIR/venv &&
            python -m venv \$JFROG_CLI_HOME_DIR/venv &&
            . \$JFROG_CLI_HOME_DIR/venv/bin/activate &&
            \$WORKSPACE/jfrog rt pip-install --module ${args.packageName} \
                --no-cache-dir --force-reinstall -r ${args.requirementsFile}
        """.stripIndent()
    }
    // Upload artifacts and register in build info
    if (args.dstSubPath && !args.dstSubPath.endsWith('/')) {
        args.dstSubPath += '/'
    }
    sh """
        \$WORKSPACE/jfrog rt upload ${args.srcPath} \
            ${args.repoName}/${args.packageName}/${args.dstSubPath} \
            --module ${args.packageName} --detailed-summary --flat
    """.stripIndent()

    // Register environment in build info
    sh '$WORKSPACE/jfrog rt build-collect-env'

    // Publish collected build info
    sh '$WORKSPACE/jfrog rt build-publish'
}

// Basic usage
withJfrogCli('<credential-id>') {
    // build python package before calling jfrogCliPublishPythonPackage()
    
    jfrogCliPublishPythonPackage([
        repoName: "tool-dev-pypi-local",
        packageName: "mypackage",
        dstSubPath: "mypackage",
        requirementsFile: "requirements.txt
    ])
}
```
