### ISSUE TITLE
NullPointerException with Gradle in 3.13.0

### ISSUE THREAD

**Issue by derekscp** [jfrog/jenkins-artifactory-plugin#551]
**Describe the bug**
A NullPointerException appears on Gradle Pipeline Builds after an upgrade of the Artifactory Jenkins Plugin from 3.12.5 -> 3.13.0.

I have reproduced the issue with the Jfrog project example by replacing the task configuration in rtGradleRun with just 'build':

rtGradleRun (
usesPlugin: true, // Artifactory plugin already defined in build script
useWrapper: true,
tool: "Gradle", // Tool name from Jenkins configuration
rootDir: "gradle-examples/gradle-example/",
buildFile: 'build.gradle',
**_tasks: 'build',_**
deployerId: "GRADLE_DEPLOYER",
resolverId: "GRADLE_RESOLVER"
)

This gives me a NPE:
`java.lang.NullPointerException
at org.jfrog.hudson.pipeline.common.types.deployers.Deployer.addDeployedArtifactsActionFromModules(Deployer.java:251)
at org.jfrog.hudson.pipeline.common.executors.GradleExecutor.execute(GradleExecutor.java:76)
at org.jfrog.hudson.pipeline.declarative.steps.gradle.GradleStep$Execution.runStep(GradleStep.java:128)
at org.jfrog.hudson.pipeline.declarative.steps.gradle.GradleStep$Execution.runStep(GradleStep.java:113)
at org.jfrog.hudson.pipeline.ArtifactorySynchronousNonBlockingStepExecution.run(ArtifactorySynchronousNonBlockingStepExecution.java:54)
at org.jenkinsci.plugins.workflow.steps.SynchronousNonBlockingStepExecution.lambda$start$0(SynchronousNonBlockingStepExecution.java:47)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:829)`

**To Reproduce**
1. Took the declarative Gradle example from JFrog's project examples (https://github.com/jfrog/project-examples/blob/master/jenkins-examples/pipeline-examples/declarative-examples/gradle-example/Jenkinsfile)
2. Replaced the variables to match my environment.
3. Replaced the tasks: 'clean artifactoryPublish'. line with tasks: 'build'
4. Tested the Jenkins build with 3.13.0 and get the NPE.
5. Tested the Jenkins build with 3.12.5 and did not get an NPE. The build was successful.

**Expected behavior**
The build should not produce a NullPointerException in 3.13.0

**Versions**
- Jenkins Artifactory plugin version: 3.13.0

**Comment by asteiner-psh** [comment]
I too have just updated the plugin and are getting this Exception.

**Comment by asteiner-psh** [comment]
Actually, slightly different for me:

> java.lang.NullPointerException
	at org.jfrog.hudson.pipeline.common.executors.GradleExecutor.execute(GradleExecutor.java:76)
	at org.jfrog.hudson.pipeline.declarative.steps.gradle.GradleStep$Execution.runStep(GradleStep.java:128)
	at org.jfrog.hudson.pipeline.declarative.steps.gradle.GradleStep$Execution.runStep(GradleStep.java:113)
	at org.jfrog.hudson.pipeline.ArtifactorySynchronousNonBlockingStepExecution.run(ArtifactorySynchronousNonBlockingStepExecution.java:54)
	at org.jenkinsci.plugins.workflow.steps.SynchronousNonBlockingStepExecution.lambda$start$0(SynchronousNonBlockingStepExecution.java:47)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

**Comment by eyalbe4** [comment]
This issue is fixed and released as part of version 3.13.1 of the Jenkins Artifactory Plugin. We would appreciate any feedback for the fix.
