### ISSUE TITLE
Docker push failed with ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by five-iron** [jfrog/jenkins-artifactory-plugin#582]
**Describe the bug**
After upgrading jenkins and some plugins including artifactory-plugin, some (and only some) docker pushes are failing with the stack trace down below.

**To Reproduce**
`docker.build` (docker-workflow plugin), followed by instantiating the artifactory docker instance (`def rtDocker = Artifactory.docker(server...)`) then `rtDocker.push(imageName, namespace)`.

**Expected behavior**
Docker push should succeed.

**Screenshots**
N/A

**Versions**
- Jenkins Artifactory plugin version: 3.13.2
- Jenkins operating system: centos7
- Artifactory Version: 7.21.5

**Additional context**
```
 ERROR: Couldn't execute docker task. ArrayIndexOutOfBoundsException: 200
 [Pipeline] }
 ERROR: Execution failed
 java.lang.RuntimeException: docker build failed
 	at org.jfrog.hudson.pipeline.common.Utils.launch(Utils.java:297)
 	at org.jfrog.hudson.pipeline.common.executors.BuildInfoProcessRunner.execute(BuildInfoProcessRunner.java:59)
 	at org.jfrog.hudson.pipeline.common.executors.DockerPushExecutor.execute(DockerPushExecutor.java:42)
 	at org.jfrog.hudson.pipeline.scripted.steps.DockerPushStep$Execution.runStep(DockerPushStep.java:91)
 	at org.jfrog.hudson.pipeline.scripted.steps.DockerPushStep$Execution.runStep(DockerPushStep.java:68)
 	at org.jfrog.hudson.pipeline.ArtifactorySynchronousNonBlockingStepExecution.run(ArtifactorySynchronousNonBlockingStepExecution.java:54)
 	at org.jenkinsci.plugins.workflow.steps.SynchronousNonBlockingStepExecution.lambda$start$0(SynchronousNonBlockingStepExecution.java:47)
 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
 	at java.base/java.lang.Thread.run(Thread.java:829)
```

**Comment by five-iron** [comment]
Upon further investigation I have found that this error only occurs when both of the following are true:
1. The build is run inside a docker container (`withDockerContainer` [described here](https://www.jenkins.io/doc/pipeline/steps/docker-workflow/), docker-in-docker)
2. The docker build and push steps are run in a subdirectory using `dir('...') {...}`
