### ISSUE TITLE
rtMavenRun gives java.io.FileNotFoundException: /usr/share/maven/lib/ext

### ISSUE THREAD

**Issue by chroche** [jfrog/jenkins-artifactory-plugin#607]
**Describe the bug**

`rtMavenRun` produces this error
```
java.io.FileNotFoundException: /usr/share/maven/lib/ext
```

**To Reproduce**

In a Jenkins declarative pipeline:
```
      stage('Build') {
        tools {
          jdk 'jdk-8'
        }
        steps {
          buildName "#${params.branch}-${env.BUILD_NUMBER}"
            rtMavenRun (
              tool: 'maven-3',
              pom: 'pom.xml',
              goals: '--batch-mode clean package -DskipTests=true'
            )
        }
      }
```
gives
```
12:50:46  New run name is '#master-9'
[Pipeline] dir
12:50:46  Running in /home/jenkins/agent/workspace/maven/MyProject
[Pipeline] {
[Pipeline] rtMavenRun
12:50:46  Jenkins Artifactory Plugin version: 3.14.2
12:50:46  Artifactory integration is enabled
12:50:49  [MyProject] $ /usr/lib/jvm/adoptopenjdk-8-hotspot-amd64/bin/java -classpath /usr/share/maven/boot/* -Dmaven.home=/usr/share/maven -Dmaven.conf=/usr/share/maven/conf -DbuildInfoConfig.propertiesFile=/home/jenkins/agent/workspace/maven/MyProject@tmp/artifactory/buildInfo7988225578579069999.properties -Dm3plugin.lib=/home/jenkins/agent/workspace/maven/MyProject@tmp/artifactory/cache/artifactory-plugin/3.14.2 -Dclassworlds.conf=/home/jenkins/agent/workspace/maven/MyProject@tmp/artifactory/classworlds5188771848753203897conf -Dmaven.multiModuleProjectDirectory=/home/jenkins/agent/workspace/maven/MyProject org.codehaus.plexus.classworlds.launcher.Launcher -f pom.xml --batch-mode clean package -DskipTests=true
12:50:49  java.io.FileNotFoundException: /usr/share/maven/lib/ext
12:50:49    at org.codehaus.plexus.classworlds.launcher.ConfigurationParser.loadGlob(ConfigurationParser.java:341)
12:50:49    at org.codehaus.plexus.classworlds.launcher.ConfigurationParser.parse(ConfigurationParser.java:252)
12:50:49    at org.codehaus.plexus.classworlds.launcher.Configurator.configure(Configurator.java:133)
12:50:49    at org.codehaus.plexus.classworlds.launcher.Launcher.configure(Launcher.java:127)
12:50:49    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:400)
12:50:49    at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:347)
```

**Expected behavior**

Maven should compile the project with no error

**Versions**
- Jenkins Artifactory plugin version:  3.14.2
- Jenkins operating system: Linux Debian 10 
- Artifactory Version: N/A
- Maven version: 3.6.0
- JDK version: 1.8.0_292, vendor: AdoptOpenJDK

**Additional context**

This was working with previous version of the plugin afaict.

The one place where I can see this path `/usr/share/maven/lib/ext` mentioned is in `/usr/share/maven/conf/m2.conf`:
```
main is org.apache.maven.cli.MavenCli from plexus.core

set maven.conf default ${maven.home}/conf

[plexus.core]
load       ${maven.conf}/logging
optionally ${maven.home}/lib/ext/*.jar
load       ${maven.home}/lib/*.jar
```

**Comment by tginiotis-at-work** [comment]
I have also encountered it with plugin version `3.15.1`.

**Comment by sverdlov93** [comment]
Hi @chroche and @tginiotis-at-work,
Jenkins Artifactory plugin 3.15.2 is released and includes a fix for this issue.
We'd appreciate your feedback on that.

**Comment by tginiotis-at-work** [comment]
Hi, @sverdlov93,

I cannot test, because I am blocked by #625 from moving past 3.13.2

**Comment by chroche** [comment]
I'll try to give it a go.
