### ISSUE TITLE
server.download is taking more time to download files more than a GB only while using artifacory plugins in Jenkins.

### ISSUE THREAD

**Issue by skumaridas10** [jfrog/jenkins-artifactory-plugin#608]
**Describe the bug**
We are trying to download more than 1 gb file through below code. It is taking more than 12 minutes to download. When we download using curl or manual download it takes just 30 seconds.

**To Reproduce**
Run this code to download any artifacts more than a 1 GB with the below code. You will see it will take more than 12 minutes.
pipeline {
    agent {
    label "any"
}
    stages {
        stage('Hello') {
            steps {
                echo 'Hello World'
                          }}
            
            		stage('Pull Artifacts') {
			steps {
				script {
				    cleanWs notFailBuild: true
					def buildsrv  = env.NODE_NAME.toLowerCase()
					
					echo "Pull Artifacts env "
					
						artifactoryRepo = "repoName"
				
					
					
					def server = Artifactory.server 'test-artifactory'
					def downloadSpec = """{
						"files":[
							{
								"pattern": "${artifactoryRepo}/test/test.zip"
								"target" : "${workspace}/tmp/",
								"flat": "true",
								"recursive": "false"

								
							}
						]
					}"""
					server.download(downloadSpec)
					
					
				}//End script
			}//End steps
		}
}
}

**Expected behavior**
It should download within a minute using plugins too. 

**Screenshots**

**Versions**
- Jenkins Artifactory plugin version: 3.13.0
- Jenkins operating system: windows
- Artifactory Version: 7.21.5

**Additional context**

**Comment by aloussayef** [comment]
+1

**Comment by jaykeerti** [comment]
i am unable to download large files
`	at org.jfrog.build.extractor.clientConfiguration.client.artifactory.services.DownloadToFile.saveInputStreamToFile(DownloadToFile.java:34)
	at org.jfrog.build.extractor.clientConfiguration.client.artifactory.services.DownloadToFile.setResponse(DownloadToFile.java:40)
	at org.jfrog.build.extractor.clientConfiguration.client.JFrogService.processResponse(JFrogService.java:143)
	at org.jfrog.build.extractor.clientConfiguration.client.JFrogService.execute(JFrogService.java:123)
	at org.jfrog.build.extractor.clientConfiguration.client.artifactory.ArtifactoryManager.downloadToFile(ArtifactoryManager.java:111)
	at org.jfrog.build.extractor.clientConfiguration.util.DependenciesDownloaderHelper.lambda$doConcurrentDownload$0(DependenciesDownloaderHelper.java:277)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.io.IOException: No space left on device
	at java.base/java.io.FileOutputStream.writeBytes(Native Method)
	at java.base/java.io.FileOutputStream.write(FileOutputStream.java:354)
	at org.apache.commons.io.IOUtils.copyLarge(IOUtils.java:1310)
	at org.apache.commons.io.IOUtils.copy(IOUtils.java:978)
	at org.apache.commons.io.IOUtils.copyLarge(IOUtils.java:1282)
	at org.jfrog.build.extractor.clientConfiguration.client.artifactory.services.DownloadToFile.saveInputStreamToFile(DownloadToFile.java:31)
	... 6 more`
