### ISSUE TITLE
Deployment fails with last commit has an ASCII quote in the first line (summary)

### ISSUE THREAD

**Issue by TIBCOrkrajews** [jfrog/jenkins-artifactory-plugin#618]
**Describe the bug**

Artifactory deployment using the plugin fails with 400 (Bad Request) error. The exact cause might be obscured a little because the plugin performs transactions in parallel, but you will see it. Job and server log excerpts at **Additional Context**.

**To Reproduce**

Commit to a source repository that will deploy a build to Artifactory, like a main branch to be deployed from a Maven build using the Jenkins Artifactory Plugin, supplying an ASCII double-quote in the first line of the commit message. Our Jenkins job used the rtMaven instance in the scripted part of a pipeline, but I suppose the "fill in the web form" Maven integration or Gradle support should exhibit this behavior as well. We used GitHub as the SCM for the repos where we've seen this, but it might be reproducible under Subversion and other source control systems. The important thing is that an ASCII double-quote appear in the _commit message summary_ (first line) so that it shows up as a `vcs.message` property of the build.

You will see at least one `Failed to upload file` message, depending on the number of artifacts to be deployed. For us, it looks like:

    [pool-8-thread-1] Deploying artifact: http://na-bos-artifacts.na.tibco.com/ep-snapshots/com/tibco/sandbox/ep/mb/root/1.0.0-SNAPSHOT/root-1.0.0-SNAPSHOT.pom
    [pool-8-thread-2] Deploying artifact: http://na-bos-artifacts.na.tibco.com/ep-snapshots/com/tibco/sandbox/ep/mb/processes/1.0.0-SNAPSHOT/processes-1.0.0-SNAPSHOT.jar
    [Pipeline] }
    [Pipeline] // script
    [Pipeline] }
    [Pipeline] // stage
    [Pipeline] stage
    [Pipeline] { (Declarative: Post Actions)
    [Pipeline] script
    [Pipeline] {
    [Pipeline] step
    INFO: Processing JUnit
    Failed to upload file
    Failed to upload file

**Expected behavior**
The artifacts should be deployed.

**Versions**
- Jenkins Artifactory plugin version: 3.15.1
- Jenkins operating system: Red Hat Enterprise Linux release 8.5 (Ootpa)
- Artifactory Version: 7.29.7

**Additional context**

Additional Jenkins-side error with backtrace:

    java.io.IOException: JFrog service failed. Received 400: <!doctype html><html lang="en"><head><title>HTTP Status 400 – Bad Request</title><style type="text/css">body {font-family:Tahoma,Arial,sans-serif;} h1, h2, h3, b {color:white;background-color:#525D76;} h1 {font-size:22px;} h2 {font-size:16px;} h3 {font-size:14px;} p {font-size:12px;} a {color:black;} .line {height:1px;background-color:#525D76;border:none;}</style></head><body><h1>HTTP Status 400 – Bad Request</h1></body></html>
    	at org.jfrog.build.extractor.clientConfiguration.client.JFrogService.throwException(JFrogService.java:53)
    	at org.jfrog.build.extractor.clientConfiguration.client.artifactory.services.Upload.handleUnsuccessfulResponse(Upload.java:59)
    	at org.jfrog.build.extractor.clientConfiguration.client.JFrogService.execute(JFrogService.java:130)
    	at org.jfrog.build.extractor.clientConfiguration.client.artifactory.services.Upload.execute(Upload.java:77)
    	at org.jfrog.build.extractor.clientConfiguration.client.artifactory.ArtifactoryManager.upload(ArtifactoryManager.java:295)
    	at org.jfrog.build.extractor.clientConfiguration.client.artifactory.ArtifactoryManager.upload(ArtifactoryManager.java:290)
    	at org.jfrog.build.extractor.ModuleParallelDeployHelper.lambda$deploy$4(ModuleParallelDeployHelper.java:46)
    Caused: java.lang.RuntimeException: Error occurred while publishing artifact to Artifactory: /mnt/jenkins/workspace/jews_ep-jenkins-multibranch_main/src/pom.xml.
     Skipping deployment of remaining artifacts (if any) and build info.
    	at org.jfrog.build.extractor.ModuleParallelDeployHelper.lambda$deploy$4(ModuleParallelDeployHelper.java:57)
    	at java.lang.Iterable.forEach(Iterable.java:75)
    	at org.jfrog.build.extractor.ModuleParallelDeployHelper.deploy(ModuleParallelDeployHelper.java:44)
    	at org.jfrog.build.extractor.ModuleParallelDeployHelper.lambda$null$1(ModuleParallelDeployHelper.java:34)
    	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1640)
    Caused: java.util.concurrent.ExecutionException
    	at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:357)
    	at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1908)
    	at org.jfrog.build.extractor.ModuleParallelDeployHelper.deployArtifacts(ModuleParallelDeployHelper.java:36)
    Also:   hudson.remoting.Channel$CallSiteStackTrace: Remote call to na1devstrje12.dev.tibco.com
    		at hudson.remoting.Channel.attachCallSiteStackTrace(Channel.java:1797)
    		at hudson.remoting.UserRequest$ExceptionResponse.retrieve(UserRequest.java:356)
    		at hudson.remoting.Channel.call(Channel.java:1001)
    		at hudson.FilePath.act(FilePath.java:1165)
    		at hudson.FilePath.act(FilePath.java:1154)
    		at org.jfrog.hudson.pipeline.common.types.deployers.Deployer.deployArtifacts(Deployer.java:224)
    		at org.jfrog.hudson.pipeline.scripted.steps.DeployStep$Execution.runStep(DeployStep.java:42)
    		at org.jfrog.hudson.pipeline.scripted.steps.DeployStep$Execution.runStep(DeployStep.java:30)
    		at org.jfrog.hudson.pipeline.ArtifactorySynchronousNonBlockingStepExecution.run(ArtifactorySynchronousNonBlockingStepExecution.java:54)
    		at org.jenkinsci.plugins.workflow.steps.SynchronousNonBlockingStepExecution.lambda$start$0(SynchronousNonBlockingStepExecution.java:47)
    		at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    Caused: java.lang.RuntimeException
    	at org.jfrog.build.extractor.ModuleParallelDeployHelper.deployArtifacts(ModuleParallelDeployHelper.java:38)
    	at org.jfrog.hudson.pipeline.common.types.deployers.Deployer$LateDeployCallable.invoke(Deployer.java:364)
    	at org.jfrog.hudson.pipeline.common.types.deployers.Deployer$LateDeployCallable.invoke(Deployer.java:335)
    	at hudson.FilePath$FileCallableWrapper.call(FilePath.java:3329)
    	at hudson.remoting.UserRequest.perform(UserRequest.java:211)
    	at hudson.remoting.UserRequest.perform(UserRequest.java:54)
    	at hudson.remoting.Request$2.run(Request.java:376)
    	at hudson.remoting.InterceptingExecutorService.lambda$wrap$0(InterceptingExecutorService.java:78)
    	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
    	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
    	at java.lang.Thread.run(Thread.java:748)

Server-side log excerpt with complaint about encoding: (it's one one line, so scroll to the right):

    2022-01-18T14:43:09.651L [35m[tomct][0m [INFO ] [                ] [org.apache.coyote.http11.Http11Processor] [org.apache.coyote.http11.Http11Processor service] - Error parsing HTTP request header
     Note: further occurrences of HTTP request parsing errors will be logged at DEBUG level. 
    java.lang.IllegalArgumentException: Invalid character found in the request target [/artifactory/ep-snapshots/com/tibco/sandbox/ep/mb/root/1.0.0-SNAPSHOT/root-1.0.0-SNAPSHOT.pom;artifactory.licenses=TIBCO;artifactory.licenses=TIBCO;vcs.revision=0471208f1ccf251eb3afffaaa843aa7e4c3ac4aa;vcs.revision=0471208f1ccf251eb3afffaaa843aa7e4c3ac4aa;vcs.revision=0471208f1ccf251eb3afffaaa843aa7e4c3ac4aa;build.timestamp=1642534709469;build.name=Users+::+rkrajews+::+ep-jenkins-multibranch+::+main;build.number=3;vcs.url=https:/github.com/tibcosandbox/ep-jenkins-multibranch.git;vcs.url=https:/github.com/tibcosandbox/ep-jenkins-multibranch.git;vcs.url=https:/github.com/tibcosandbox/ep-jenkins-multibranch.git;vcs.message=Update+copyright.+See+if+"+mark+in+commit+message+header+trips+up+Artifactory+deployment. ]. The valid characters are defined in RFC 7230 and RFC 3986
    	at org.apache.coyote.http11.Http11InputBuffer.parseRequestLine(Http11InputBuffer.java:517)
    	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:511)
    	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
    	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:831)
    	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1651)
    	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
    	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
    	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
    	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
    	at java.base/java.lang.Thread.run(Thread.java:829)

**Comment by TIBCOrkrajews** [comment]
Also seems to have URL request encoding issues if the commit message's first line has a semi-colon. In this case, the commit message was:

> Update standard plugin version; remove maven-clean-plugin version from lv_python_client.

`java.io.IOException: JFrog service failed. Received 400: {
  "errors" : [ {
    "status" : 400,
    "message" : "Property key: +remove+maven-clean-plugin+version+from+lv_python_client. is invalid due to Name must start with a letter and cannot contain whitespace or special characters"
  } ]
}
	at org.jfrog.build.extractor.clientConfiguration.client.JFrogService.throwException(JFrogService.java:53)
	at org.jfrog.build.extractor.clientConfiguration.client.artifactory.services.Upload.handleUnsuccessfulResponse(Upload.java:59)
	at org.jfrog.build.extractor.clientConfiguration.client.JFrogService.execute(JFrogService.java:130)
	at org.jfrog.build.extractor.clientConfiguration.client.artifactory.services.Upload.execute(Upload.java:77)
	at org.jfrog.build.extractor.clientConfiguration.client.artifactory.ArtifactoryManager.upload(ArtifactoryManager.java:295)
	at org.jfrog.build.extractor.clientConfiguration.client.artifactory.ArtifactoryManager.upload(ArtifactoryManager.java:290)
	at org.jfrog.build.extractor.ModuleParallelDeployHelper.lambda$deploy$4(ModuleParallelDeployHelper.java:46)`

**Comment by TIBCOrkrajews** [comment]
Still happening in plugin version 3.16.1 – try a commit message with a double quote.

**Comment by Sickafant** [comment]
Also seeing this with other special characters. `|` and `;` in the first commit message line broke the deploy.

One workaround that may or may not work for some Jenkins setups, is to disable the setting to clone into a local branch for the job configuration. This should make the `Executing command: /bin/sh -c git log --pretty=format:%s -1` that the plugin uses to fail and then it doesn't send any commit data to Artifactory. But this setting is useful to have git data accessible during the build.

**Comment by PM-JoakimGustavsson** [comment]
We are experiencing the same issue with our build pipelines. After some additional troubleshooting we concluded that this seems to be a bug affecting Artifactory as a whole rather than just the Jenkins Artifactory Plugin. We have been able to reproduce the bug with the Artifactory REST API as well:

```
$ curl -XPUT -T "testfile.txt" -u "user:password" "https://<ARTIFACTORY_URL>/artifactory/devops-generic-local/dockerce.txt;vcs.message=INPRO-11941%3A%20first%20part%3Bsecond%20part"
{
  "errors" : [ {
    "status" : 400,
    "message" : "Property key: second%20part is invalid due to Name must start with a letter and cannot contain whitespace or special characters"
  } ]
}%       
```
Note here that the semicolon is URL encoded - the same error occurs if they are not encoded. We also get the same error both if spaces are encoded as "+" or as "%20".

We are using Artifactory version 7.27.15. We also have an open support ticket with JFrog support regarding the issue.

**Comment by TIBCOrkrajews** [comment]
Interesting - I would think that the server wouldn't be at fault. We are still seeing this in Artifactory 7.38.8.

It doesn't help that at least in the old days, the quoting conventions for HTTP query parameters and path components for URLs were either not well-spelled-out or poorly implemented. The "real" fix would be have this publish operation pass its parameters as posted JSON instead of using the URL, so there's a lot less scope for ambiguity.

**Comment by tychobrailleur** [comment]
> Also seeing this with other special characters. `|` and `;` in the first commit message line broke the deploy.

We observe the same issue with curly braces (`{` and `}`) in the first line of the VCS commit message submitted as part of the publish info task.

**Comment by sverdlov93** [comment]
Hi all, 
Thanks for reporting this issue.
I tested it with all types of special characters and it worked as expected.
I think it might be a proxy-related issue like here - https://github.com/jfrog/jenkins-artifactory-plugin/issues/371or here or here https://github.com/jfrog/jenkins-artifactory-plugin/issues/553.
That resolved using the following comment: https://github.com/jfrog/jenkins-artifactory-plugin/issues/371#issuecomment-832514991

Can you also try running your builds with a Cloud JFrog Platform? 
You can create a Free JFrog Environment on https://jfrog.com/start-free by clicking `Skip Trial and Start with a Free JFrog Instance`
You can also create one from your CLI using the following command:
`curl -fL "https://getcli.jfrog.io?setup" | sh`

**Comment by PM-JoakimGustavsson** [comment]
Hi!

Following the suggestions from @sverdlov93 I tried to bypass the Apache reverse proxy we use and instead upload directly to Artifactory. This resulted in a successful upload. It does indeed appear that the issue is related to the reverse proxy. Huge thanks to @sverdlov93 for suggesting this. The suggested solution to use `AllowEncodedSlashes On` does however not work for us, as this setting is already enabled. We are using the automatically generated Apache config that the Artifactory Admin UI generates. See below:

```
LoadModule rewrite_module modules/mod_rewrite.so
LoadModule proxy_module modules/mod_proxy.so
LoadModule proxy_http_module modules/mod_proxy_http.so
LoadModule headers_module modules/mod_headers.so
LoadModule alias_module modules/mod_alias.so


# The following part comes from the snippet generator in Artifactory, with environment
# specific values replaced by variables.
<VirtualHost *:443>

    TimeOut 600

    ProxyPreserveHost On
    ProxyAddHeaders off

    ServerName public.urlforserver.se
    ServerAlias *.public.urlforserver.se
    ServerAdmin server@admin

    SSLEngine on
    SSLCertificateFile /etc/httpd/conf/certfile.crt
    SSLCertificateKeyFile /etc/httpd/conf/keyfile.key
    SSLProxyEngine on

    AllowEncodedSlashes On
    RewriteEngine on

    RewriteCond %{SERVER_PORT} (.*)
    RewriteRule (.*) - [E=my_server_port:%1]
    ##  NOTE: The 'REQUEST_SCHEME' Header is supported only from apache version 2.4 and above
    RewriteCond %{REQUEST_SCHEME} (.*)
    RewriteRule (.*) - [E=my_scheme:%1]

    RewriteCond %{HTTP_HOST} (.*)
    RewriteRule (.*) - [E=my_custom_host:%1]


    RewriteRule ^(/)?$      /ui/ [R,L]
    RewriteRule ^/ui$      /ui/ [R,L]

    RequestHeader set Host %{my_custom_host}e
    RequestHeader set X-Forwarded-Port %{my_server_port}e
    ## NOTE: {my_scheme} requires a module which is supported only from apache version 2.4 and above
    RequestHeader set X-Forwarded-Proto %{my_scheme}e
    RequestHeader set X-JFrog-Override-Base-Url %{my_scheme}e://public.urlforserver.se:%{my_server_port}e
    Header always set Strict-Transport-Security ""
    ProxyPassReverseCookiePath / /

    ProxyRequests off
    ProxyPreserveHost on
    ProxyPass /artifactory/ http://localhost:8081/artifactory/
    ProxyPassReverse /artifactory/ http://localhost:8081/artifactory/
    ProxyPass / http://localhost:8082/
    ProxyPassReverse / http://localhost:8082/
</VirtualHost>

```
URLs have been censored. We are using Apache 2.4.6 so all the functions that require 2.4 or greater should work.

**Comment by sverdlov93** [comment]
Great news @PM-JoakimGustavsson!
cc @tychobrailleur @TIBCOrkrajews @Sickafant

**Comment by PM-JoakimGustavsson** [comment]
Hi again everyone!

Based on the suggestions mentioned here https://www.jfrog.com/jira/browse/RTFACT-26841 I changed `AllowEncodedSlashes` to `NoDecode` and added `nocanon` to the ProxyPass directives. See updated config below:

```
LoadModule rewrite_module modules/mod_rewrite.so
LoadModule proxy_module modules/mod_proxy.so
LoadModule proxy_http_module modules/mod_proxy_http.so
LoadModule headers_module modules/mod_headers.so
LoadModule alias_module modules/mod_alias.so


# The following part comes from the snippet generator in Artifactory, with environment
# specific values replaced by variables.
<VirtualHost *:443>

    TimeOut 600

    ProxyPreserveHost On
    ProxyAddHeaders off

    ServerName public.urlforserver.se
    ServerAlias *.public.urlforserver.se
    ServerAdmin server@admin

    SSLEngine on
    SSLCertificateFile /etc/httpd/conf/certfile.crt
    SSLCertificateKeyFile /etc/httpd/conf/keyfile.key
    SSLProxyEngine on

    AllowEncodedSlashes NoDecode
    RewriteEngine on

    RewriteCond %{SERVER_PORT} (.*)
    RewriteRule (.*) - [E=my_server_port:%1]
    ##  NOTE: The 'REQUEST_SCHEME' Header is supported only from apache version 2.4 and above
    RewriteCond %{REQUEST_SCHEME} (.*)
    RewriteRule (.*) - [E=my_scheme:%1]

    RewriteCond %{HTTP_HOST} (.*)
    RewriteRule (.*) - [E=my_custom_host:%1]


    RewriteRule ^(/)?$      /ui/ [R,L]
    RewriteRule ^/ui$      /ui/ [R,L]

    RequestHeader set Host %{my_custom_host}e
    RequestHeader set X-Forwarded-Port %{my_server_port}e
    ## NOTE: {my_scheme} requires a module which is supported only from apache version 2.4 and above
    RequestHeader set X-Forwarded-Proto %{my_scheme}e
    RequestHeader set X-JFrog-Override-Base-Url %{my_scheme}e://public.urlforserver.se:%{my_server_port}e
    Header always set Strict-Transport-Security ""
    ProxyPassReverseCookiePath / /

    ProxyRequests off
    ProxyPreserveHost on
    ProxyPass /artifactory/ http://localhost:8081/artifactory/ nocanon
    ProxyPassReverse /artifactory/ http://localhost:8081/artifactory/ nocanon
    ProxyPass / http://localhost:8082/
    ProxyPassReverse / http://localhost:8082/
</VirtualHost>
```

This works flawlessly. Hopefully this workaround will work for the rest of you as well.
