### ISSUE TITLE
java.util.jar.JarException: artifactory-plugin/3.15.2/AmazonCorrettoCryptoProvider-1.6.1.jar is not signed by a trusted signer

### ISSUE THREAD

**Issue by uweng** [jfrog/jenkins-artifactory-plugin#621]
We have recently updated our jenkins server to version 2.319.1 including all plugins. Now when we build any job we will get the following message:

[ERROR] HmacMD5 failed self-test 0
[ERROR] Self-test result for JCE algo HmacMD5: FAILED
java.lang.SecurityException: JCE cannot authenticate the provider test provider
	at javax.crypto.JceSecurity.getInstance(JceSecurity.java:114)
	at javax.crypto.Mac.getInstance(Mac.java:257)
	at com.amazon.corretto.crypto.provider.HmacMD5Spi.runSelfTest(HmacMD5Spi.java:181)
	at com.amazon.corretto.crypto.provider.HmacMD5Spi$$Lambda$51/253189375.get(Unknown Source)
	at com.amazon.corretto.crypto.provider.SelfTestSuite$SelfTest.runTest0(SelfTestSuite.java:68)
	at com.amazon.corretto.crypto.provider.SelfTestSuite$SelfTest.runTest(SelfTestSuite.java:59)
	at com.amazon.corretto.crypto.provider.SelfTestSuite.lambda$runTests$2(SelfTestSuite.java:171)
	at com.amazon.corretto.crypto.provider.SelfTestSuite$$Lambda$53/424224333.accept(Unknown Source)
	at java.util.concurrent.ConcurrentHashMap.forEach(ConcurrentHashMap.java:1597)
	at com.amazon.corretto.crypto.provider.SelfTestSuite.runTests(SelfTestSuite.java:170)
	at com.amazon.corretto.crypto.provider.AmazonCorrettoCryptoProvider$ACCPService$$Lambda$44/535691272.get(Unknown Source)
	at com.amazon.corretto.crypto.provider.AmazonCorrettoCryptoProvider$ACCPService.checkTests(AmazonCorrettoCryptoProvider.java:219)
	at com.amazon.corretto.crypto.provider.AmazonCorrettoCryptoProvider$ACCPService.newInstance(AmazonCorrettoCryptoProvider.java:182)
	at sun.security.jca.GetInstance.getInstance(GetInstance.java:236)
	at sun.security.jca.GetInstance.getInstance(GetInstance.java:164)
	at java.security.Security.getImpl(Security.java:695)
	at java.security.MessageDigest.getInstance(MessageDigest.java:167)
	at org.jfrog.build.api.util.FileChecksumCalculator.calculate(FileChecksumCalculator.java:92)
	at org.jfrog.build.api.util.FileChecksumCalculator.calculateChecksums(FileChecksumCalculator.java:69)
	at org.jfrog.build.extractor.maven.BuildInfoRecorder.setDependencyChecksums(BuildInfoRecorder.java:670)
	at org.jfrog.build.extractor.maven.BuildInfoRecorder.addDependenciesToCurrentModule(BuildInfoRecorder.java:647)
	at org.jfrog.build.extractor.maven.BuildInfoRecorder.addModuleToBuild(BuildInfoRecorder.java:465)
	at org.jfrog.build.extractor.maven.BuildInfoRecorder.finalizeModule(BuildInfoRecorder.java:388)
	at org.jfrog.build.extractor.maven.BuildInfoRecorder.projectSucceeded(BuildInfoRecorder.java:207)
	at org.apache.maven.lifecycle.internal.DefaultExecutionEventCatapult.fire(DefaultExecutionEventCatapult.java:74)
	at org.apache.maven.lifecycle.internal.DefaultExecutionEventCatapult.fire(DefaultExecutionEventCatapult.java:42)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:127)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:56)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:305)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:192)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:105)
	at org.jvnet.hudson.maven3.launcher.Maven35Launcher.main(Maven35Launcher.java:130)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at jenkins.maven3.agent.Maven35Main.launch(Maven35Main.java:178)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at hudson.maven.Maven3Builder.call(Maven3Builder.java:139)
	at hudson.maven.Maven3Builder.call(Maven3Builder.java:70)
	at hudson.remoting.UserRequest.perform(UserRequest.java:211)
	at hudson.remoting.UserRequest.perform(UserRequest.java:54)
	at hudson.remoting.Request$2.run(Request.java:376)
	at hudson.remoting.InterceptingExecutorService.lambda$wrap$0(InterceptingExecutorService.java:78)
	at hudson.remoting.InterceptingExecutorService$$Lambda$4/206363707.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.util.jar.JarException: file:/jenkins/cache/artifactory-plugin/3.15.2/AmazonCorrettoCryptoProvider-1.6.1.jar is not signed by a trusted signer.
	at javax.crypto.JarVerifier.verifySingleJar(JarVerifier.java:502)
	at javax.crypto.JarVerifier.verifyJars(JarVerifier.java:322)
	at javax.crypto.JarVerifier.verify(JarVerifier.java:250)
	at javax.crypto.JceSecurity.verifyProviderJar(JceSecurity.java:160)
	at javax.crypto.JceSecurity.getVerificationResult(JceSecurity.java:186)
	at javax.crypto.JceSecurity.getInstance(JceSecurity.java:110)
	... 55 more

[ERROR] HmacMD5 failed self-test 0
[ERROR] Self-test result for JCE algo HmacMD5: FAILED
java.lang.SecurityException: JCE cannot authenticate the provider test provider
	at javax.crypto.JceSecurity.getInstance(JceSecurity.java:114)
	at javax.crypto.Mac.getInstance(Mac.java:257)
	at com.amazon.corretto.crypto.provider.HmacMD5Spi.runSelfTest(HmacMD5Spi.java:181)
	at com.amazon.corretto.crypto.provider.HmacMD5Spi$$Lambda$51/253189375.get(Unknown Source)
	at com.amazon.corretto.crypto.provider.SelfTestSuite$SelfTest.runTest0(SelfTestSuite.java:68)
	at com.amazon.corretto.crypto.provider.SelfTestSuite$SelfTest.runTest(SelfTestSuite.java:59)
	at com.amazon.corretto.crypto.provider.SelfTestSuite.lambda$runTests$2(SelfTestSuite.java:171)
	at com.amazon.corretto.crypto.provider.SelfTestSuite$$Lambda$53/424224333.accept(Unknown Source)
	at java.util.concurrent.ConcurrentHashMap.forEach(ConcurrentHashMap.java:1597)
	at com.amazon.corretto.crypto.provider.SelfTestSuite.runTests(SelfTestSuite.java:170)
	at com.amazon.corretto.crypto.provider.AmazonCorrettoCryptoProvider$$Lambda$52/1613420852.call(Unknown Source)
	at java.util.concurrent.ForkJoinTask$AdaptedCallable.exec(ForkJoinTask.java:1424)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1689)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
Caused by: java.util.jar.JarException: file:/jenkins/cache/artifactory-plugin/3.15.2/AmazonCorrettoCryptoProvider-1.6.1.jar is not signed by a trusted signer.
	at javax.crypto.JarVerifier.verifySingleJar(JarVerifier.java:502)
	at javax.crypto.JarVerifier.verifyJars(JarVerifier.java:322)
	at javax.crypto.JarVerifier.verify(JarVerifier.java:250)
	at javax.crypto.JceSecurity.verifyProviderJar(JceSecurity.java:160)
	at javax.crypto.JceSecurity.getVerificationResult(JceSecurity.java:186)
	at javax.crypto.JceSecurity.getInstance(JceSecurity.java:110)
	... 15 more

**Versions**
- Jenkins Artifactory plugin 3.15.2: 
- Jenkins operating system RedHat 7.3:
- Artifactory Version 4.14.1:

**Comment by yahavi** [comment]
@uweng,
Thanks for reporting this issue! We are looking into it.
Could you please provide your JDK version?

As a workaround, for now, you can downgrade to the Jenkins Artifactory plugin 3.15.1.

**Comment by uweng** [comment]
Jenkins is running on **java-11-openjdk-11.0.13.0.8-1.el7_9.x86_64**
The job will build using **java-1.8.0-openjdk-1.8.0.312.b07-1.el7_9.x86_64**
This is the jenkins running with parameter:
/etc/alternatives/java -Xms512m -Xmx4096m -Djava.awt.headless=true -Djavax.net.ssl.trustStore=/jenkins/cacerts -Djava.naming.referral=ignore -Dcom.sun.jndi.ldap.object.disableEndpointIdentification=true -DJENKINS_HOME=/jenkins -jar /usr/lib/jenkins/jenkins.war --logfile=/var/log/jenkins/jenkins.log --webroot=/var/cache/jenkins/war --httpPort=8080 --httpListenAddress=localhost --debug=5 --handlerCountMax=100 --handlerCountMaxIdle=20

/jenkins/cacerts is a copy of /usr/lib/jvm/java-11-openjdk-11.0.13.0.8-1.el7_9.x86_64/lib/security/cacerts including our CA-Cert necessary for LDAP SSL encryption.

**Comment by uweng** [comment]
The bug is allready in Jenkins Artifactory plugin 3.15.1 !

**Comment by yahavi** [comment]
@uweng I'm sorry, I didn't notice it included in 3.15.1.
Please use version 3.15.0. 

This is the commit that added AmazonCorrettoCryptoProvider: https://github.com/jfrog/build-info/commit/6f1cab737eb14454a576cecd6481f69334096792
The Jenkins Artifactory plugin 3.15.0 [includes](https://github.com/jfrog/jenkins-artifactory-plugin/blob/artifactory-3.15.0/pom.xml#L44) build-info 2.32.6 which doesn't include AmazonCorrettoCryptoProvider.

**Comment by uweng** [comment]
Right, it helps. Bat this is only a workaround. It should be fixed in the actual version!

**Comment by yahavi** [comment]
@uweng 
We released Jenkins Artifactory plugin 3.15.3 to target this issue. 
In this release, we [removed](https://github.com/jfrog/build-info/pull/609/files) the AmazonCorrettoCryptoProvider code.

Feel free to upgrade.
We'd appreciate your feedback on that.

**Comment by uweng** [comment]
Yes i can confirm, the plugin version 3.15.3 is now without the exception! The problem is fixed.
Thank you for your fast help!!!
