### ISSUE TITLE
Failed to save System configuration 

### ISSUE THREAD

**Issue by ftredang** [jfrog/jenkins-artifactory-plugin#641]
When trying to save System Configuration (even nothing change), Jenkins report "A problem occurred while processing the request.". Check the system log and got the following exception 

Caught unhandled exception with ID e18e8e23-7c0f-4da9-8911-f6ad3bdf9340
java.lang.NullPointerException
	at org.jfrog.hudson.ArtifactoryBuilder$DescriptorImpl.configure(ArtifactoryBuilder.java:285)
	at jenkins.model.Jenkins.configureDescriptor(Jenkins.java:3859)
	at jenkins.model.Jenkins.doConfigSubmit(Jenkins.java:3823)
	at java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:627)
	at org.kohsuke.stapler.Function$MethodFunction.invoke(Function.java:396)
	at org.kohsuke.stapler.Function$InstanceFunction.invoke(Function.java:408)
	at org.kohsuke.stapler.Function.bindAndInvoke(Function.java:212)
	at org.kohsuke.stapler.SelectionInterceptedFunction$Adapter.invoke(SelectionInterceptedFunction.java:36)
	at org.kohsuke.stapler.verb.HttpVerbInterceptor.invoke(HttpVerbInterceptor.java:48)
	at org.kohsuke.stapler.SelectionInterceptedFunction.bindAndInvoke(SelectionInterceptedFunction.java:26)
	at org.kohsuke.stapler.Function.bindAndInvokeAndServeResponse(Function.java:145)
	at org.kohsuke.stapler.MetaClass$11.doDispatch(MetaClass.java:536)
	at org.kohsuke.stapler.NameBasedDispatcher.dispatch(NameBasedDispatcher.java:58)
	at org.kohsuke.stapler.Stapler.tryInvoke(Stapler.java:766) 

**To Reproduce**
Manage Jenkins -> Configure System -> Save

**Expected behavior**
Able to save system configuration

**Screenshots**

**Versions**
- Jenkins Artifactory plugin version:  3.13.2 & 3.15.4
- Jenkins operating system: 2.277.4-3
- Artifactory Version: 6.17.0

**Comment by yahavi** [comment]
@ftredang,
Thanks for reporting this issue!
Jenkins Artifactory plugin 3.16.0 is released. This version should include the fix for this issue.
Feel free to upgrade.
We'd appreciate your feedback on that!
