### ISSUE TITLE
NPE thrown when trying to resolve nuget dependencies.

### ISSUE THREAD

**Issue by madelaney** [jfrog/jenkins-artifactory-plugin#648]
**Describe the bug**

**To Reproduce**
1. create new instance of `Artifactory.server`, and `Artifactory.newDotnetBuild`; using NuGet API v3.
2. create new instance of `Artifactory.newBuildInfo`.
3. check out repo from git.
4. attemp to resolve dependencies `rtBuild.run args: 'restore "./SolutionFile.sln"', buildInfo: buildInfo`

**Expected behavior**
I would expect that all found dependencies get resolved and no exceptions are thrown.

**Screenshots**
Here is the output from the jenkins log.
```
Mar 15, 2022 3:44:44 PM org.jfrog.build.extractor.packageManager.PackageManagerLogger error
SEVERE: null
java.lang.NullPointerException
	at org.jfrog.build.extractor.nuget.extractor.NugetRun.collectDependencies(NugetRun.java:299)
	at org.jfrog.build.extractor.nuget.extractor.NugetRun.execute(NugetRun.java:179)
	at org.jfrog.build.extractor.packageManager.PackageManagerExtractor.executeAndSaveBuildInfo(PackageManagerExtractor.java:33)
	at org.jfrog.build.extractor.nuget.extractor.NugetRun.main(NugetRun.java:163)

java.lang.NullPointerException
	at org.jfrog.build.extractor.nuget.extractor.NugetRun.collectDependencies(NugetRun.java:299)
	at org.jfrog.build.extractor.nuget.extractor.NugetRun.execute(NugetRun.java:179)
 [wrapped] java.lang.RuntimeException: java.lang.NullPointerException
	at org.jfrog.build.extractor.nuget.extractor.NugetRun.execute(NugetRun.java:184)
	at org.jfrog.build.extractor.packageManager.PackageManagerExtractor.executeAndSaveBuildInfo(PackageManagerExtractor.java:33)
	at org.jfrog.build.extractor.nuget.extractor.NugetRun.main(NugetRun.java:163)
```

**Versions**
- Jenkins Artifactory plugin version: 3.15.3
- Jenkins operating system: Windows Server 2012 R2
- Artifactory Version: Artifactory Cloud

**Additional context**

**Comment by madelaney** [comment]
I was also able to get the NPE during a single dependency install.

Running the command: 
`rtBuild.run args: 'install Microsoft.NETCore.Platforms -Version 1.1.0'`

Results in:
```
Attempting to gather dependency information for package 'Microsoft.NETCore.Platforms.1.1.0' with respect to project 'C:\temp\super-services', targeting 'Any,Version=v0.0'
Gathering dependency information took 1.57 sec
Attempting to resolve dependencies for package 'Microsoft.NETCore.Platforms.1.1.0' with DependencyBehavior 'Lowest'
Resolving dependency information took 0 ms
Resolving actions to install package 'Microsoft.NETCore.Platforms.1.1.0'
Resolved actions to install package 'Microsoft.NETCore.Platforms.1.1.0'
Retrieving package 'Microsoft.NETCore.Platforms 1.1.0' from 'JFrogJenkins'.
  GET https://somecompany.jfrog.io/artifactory/api/nuget/v3/nuget/registration-semver2/Download/microsoft.netcore.platforms/1.1.0
  OK https://somecompany.jfrog.io/artifactory/api/nuget/v3/nuget/registration-semver2/Download/microsoft.netcore.platforms/1.1.0 165ms
Installing Microsoft.NETCore.Platforms 1.1.0.
Adding package 'Microsoft.NETCore.Platforms.1.1.0' to folder 'C:\temp\super-services'
Added package 'Microsoft.NETCore.Platforms.1.1.0' to folder 'C:\temp\super-services'
Successfully installed 'Microsoft.NETCore.Platforms 1.1.0' to C:\temp\super-services
Executing nuget actions took 1.05 sec

Mar 16, 2022 11:56:01 AM org.jfrog.build.extractor.packageManager.PackageManagerLogger error
SEVERE: null
java.lang.NullPointerException
	at org.jfrog.build.extractor.nuget.extractor.NugetRun.collectDependencies(NugetRun.java:299)
	at org.jfrog.build.extractor.nuget.extractor.NugetRun.execute(NugetRun.java:179)
	at org.jfrog.build.extractor.packageManager.PackageManagerExtractor.executeAndSaveBuildInfo(PackageManagerExtractor.java:33)
	at org.jfrog.build.extractor.nuget.extractor.NugetRun.main(NugetRun.java:163)

java.lang.NullPointerException
	at org.jfrog.build.extractor.nuget.extractor.NugetRun.collectDependencies(NugetRun.java:299)
	at org.jfrog.build.extractor.nuget.extractor.NugetRun.execute(NugetRun.java:179)
 [wrapped] java.lang.RuntimeException: java.lang.NullPointerException
	at org.jfrog.build.extractor.nuget.extractor.NugetRun.execute(NugetRun.java:184)
	at org.jfrog.build.extractor.packageManager.PackageManagerExtractor.executeAndSaveBuildInfo(PackageManagerExtractor.java:33)
	at org.jfrog.build.extractor.nuget.extractor.NugetRun.main(NugetRun.java:163)
```
