### ISSUE TITLE
Calling `MavenDescriptor.transform()` results in `java.lang.StackOverflowError`

### ISSUE THREAD

**Issue by tanelitaipale** [jfrog/jenkins-artifactory-plugin#652]
**Describe the bug**
Calling `MavenDescriptor.transform()` results in `java.lang.StackOverflowError`.

**To Reproduce**
```groovy
MavenDescriptor mavenDescriptor = Artifactory.mavenDescriptor()
mavenDescriptor.
mavenDescriptor.setPomFile("pom.xml")
mavenDescriptor.transform()
```
results in
```
java.lang.StackOverflowError
	at java.nio.HeapByteBuffer.compact(HeapByteBuffer.java:229)
	at sun.nio.cs.StreamDecoder.readBytes(StreamDecoder.java:270)
	at sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:326)
	at sun.nio.cs.StreamDecoder.read(StreamDecoder.java:178)
	at java.io.InputStreamReader.read(InputStreamReader.java:184)
	at java.io.BufferedReader.read1(BufferedReader.java:210)
	at java.io.BufferedReader.read(BufferedReader.java:286)
	at org.codehaus.plexus.util.xml.pull.MXParser.fillBuf(MXParser.java:3797)
	at org.codehaus.plexus.util.xml.pull.MXParser.more(MXParser.java:3893)
	at org.codehaus.plexus.util.xml.pull.MXParser.parseProlog(MXParser.java:1774)
	at org.codehaus.plexus.util.xml.pull.MXParser.nextImpl(MXParser.java:1757)
	at org.codehaus.plexus.util.xml.pull.MXParser.next(MXParser.java:1375)
	at org.apache.maven.model.io.xpp3.MavenXpp3Reader.read(MavenXpp3Reader.java:3876)
	at org.apache.maven.model.io.xpp3.MavenXpp3Reader.read(MavenXpp3Reader.java:595)
	at org.apache.maven.model.io.xpp3.MavenXpp3Reader.read(MavenXpp3Reader.java:609)
	at org.jfrog.hudson.pipeline.scripted.steps.MavenDescriptorStep$Execution.findPomModules(MavenDescriptorStep.java:144)
	at org.jfrog.hudson.pipeline.scripted.steps.MavenDescriptorStep$Execution.findPomModules(MavenDescriptorStep.java:165)
	at org.jfrog.hudson.pipeline.scripted.steps.MavenDescriptorStep$Execution.findPomModules(MavenDescriptorStep.java:165)
	at org.jfrog.hudson.pipeline.scripted.steps.MavenDescriptorStep$Execution.findPomModules(MavenDescriptorStep.java:165)
	at org.jfrog.hudson.pipeline.scripted.steps.MavenDescriptorStep$Execution.findPomModules(MavenDescriptorStep.java:165)
	...
	at org.jfrog.hudson.pipeline.scripted.steps.MavenDescriptorStep$Execution.findPomModules(MavenDescriptorStep.java:165)
	at org.jfrog.hudson.pipeline.scripted.steps.MavenDescriptorStep$Execution.findPomModules(MavenDescriptorStep.java:165)
	at org.jfrog.hudson.pipeline.scripted.steps.MavenDescriptorStep$Execution.findPomModules(MavenDescriptorStep.java:165)
Also:   	Also:   java.lang.InterruptedException
			at java.lang.Object.wait(Native Method)
			at hudson.remoting.Request$1.get(Request.java:317)
			at hudson.remoting.Request$1.get(Request.java:240)
			at hudson.remoting.FutureAdapter.get(FutureAdapter.java:65)
			at hudson.FilePath.copyRecursiveTo(FilePath.java:2641)
			at jenkins.model.StandardArtifactManager.archive(StandardArtifactManager.java:73)
			at hudson.tasks.ArtifactArchiver.perform(ArtifactArchiver.java:255)
			at org.jenkinsci.plugins.workflow.steps.CoreStep$Execution.run(CoreStep.java:100)
			at org.jenkinsci.plugins.workflow.steps.CoreStep$Execution.run(CoreStep.java:70)
			at org.jenkinsci.plugins.workflow.steps.SynchronousNonBlockingStepExecution.lambda$start$0(SynchronousNonBlockingStepExecution.java:47)
org.jenkinsci.plugins.workflow.steps.FlowInterruptedException
		at org.jenkinsci.plugins.workflow.cps.CpsBodyExecution.cancel(CpsBodyExecution.java:253)
		at org.jenkinsci.plugins.workflow.cps.steps.ParallelStepExecution.stop(ParallelStepExecution.java:74)
		at org.jenkinsci.plugins.workflow.cps.steps.ParallelStep$ResultHandler$Callback.checkAllDone(ParallelStep.java:151)
		at org.jenkinsci.plugins.workflow.cps.steps.ParallelStep$ResultHandler$Callback.onFailure(ParallelStep.java:138)
		at org.jenkinsci.plugins.workflow.cps.CpsBodyExecution$FailureAdapter.receive(CpsBodyExecution.java:361)
		at com.cloudbees.groovy.cps.impl.ValueBoundContinuation.receive(ValueBoundContinuation.java:21)
		at com.cloudbees.groovy.cps.impl.ForInLoopBlock$ContinuationImpl.increment(ForInLoopBlock.java:67)
		at com.cloudbees.groovy.cps.impl.ForInLoopBlock$ContinuationImpl.loopHead(ForInLoopBlock.java:57)
		at sun.reflect.GeneratedMethodAccessor464.invoke(Unknown Source)
		at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
		at java.lang.reflect.Method.invoke(Method.java:498)
		at com.cloudbees.groovy.cps.impl.ContinuationPtr$ContinuationImpl.receive(ContinuationPtr.java:72)
		at com.cloudbees.groovy.cps.impl.PropertyishBlock$ContinuationImpl.get(PropertyishBlock.java:76)
		at com.cloudbees.groovy.cps.LValueBlock$GetAdapter.receive(LValueBlock.java:30)
		at com.cloudbees.groovy.cps.impl.PropertyishBlock$ContinuationImpl.fixName(PropertyishBlock.java:66)
		at sun.reflect.GeneratedMethodAccessor430.invoke(Unknown Source)
Caused: java.io.IOException: Remote call on *****-**** failed
	at hudson.remoting.Channel.call(Channel.java:1005)
	at org.jfrog.hudson.pipeline.scripted.steps.MavenDescriptorStep$Execution.runStep(MavenDescriptorStep.java:89)
	at org.jfrog.hudson.pipeline.scripted.steps.MavenDescriptorStep$Execution.runStep(MavenDescriptorStep.java:66)
	at org.jfrog.hudson.pipeline.ArtifactorySynchronousStepExecution.run(ArtifactorySynchronousStepExecution.java:54)
	at org.jenkinsci.plugins.workflow.steps.SynchronousStepExecution.start(SynchronousStepExecution.java:37)
	at org.jenkinsci.plugins.workflow.cps.DSL.invokeStep(DSL.java:319)
	at org.jenkinsci.plugins.workflow.cps.DSL.invokeMethod(DSL.java:193)
	at org.jenkinsci.plugins.workflow.cps.CpsScript.invokeMethod(CpsScript.java:122)
	at org.jfrog.hudson.pipeline.common.types.MavenDescriptor.transform(MavenDescriptor.java:72)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1213)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1022)
	at org.codehaus.groovy.runtime.callsite.PojoMetaClassSite.call(PojoMetaClassSite.java:47)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
	at com.cloudbees.groovy.cps.sandbox.DefaultInvoker.methodCall(DefaultInvoker.java:20)
```

**Versions**
- Jenkins Artifactory plugin version: 3.16.1

**Additional context**
The StackOverflowError started to get thrown when the plugin was updated to 3.16.1, previous version was 3.15.4.

Seems that the bug is coming from this modification: https://github.com/jfrog/jenkins-artifactory-plugin/commit/df6d33af7bd5ff62bd41e9141b133d9cfbe41f70#diff-9688d2a25b0a1525f2c652f7e38cd87b2e85fd028161b0a7bc52b5b5172c63b7L143-R142

The modification made it so that `pomPath` generated from input parameters was not used anymore in `findPomModules`, and instead it uses the class variable `pomFile`. Since this function is being called recursively with `findPomModules(tempFilePath, "pom.xml", result);`, that recursive call is not probably doing the correct thing as it's constantly reading the same pom file.

**Comment by fraz3alpha** [comment]
@yahavi - is there any outlook on creating a new release of the plugin that contains this fix?

**Comment by eyalbe4** [comment]
@fraz3alpha,
A new release of the plugin which includes this fix is planned to become available during next week.

**Comment by yahavi** [comment]
@tanelitaipale @fraz3alpha, 
Jenkins Artifactory plugin 3.16.2 is released. This version includes the fix for this issue. (Thanks for this fix, @tanelitaipale!!)
Feel free to upgrade - we'd appreciate your feedback on that.

**Comment by fraz3alpha** [comment]
1.16.2 did indeed fix my colleague's jobs who were previously hitting the StackOverflowError
