### ISSUE TITLE
artifactory plugin from cloudbees failing with java.lang.NullPointerException

### ISSUE THREAD

**Issue by pavan-acquia** [jfrog/jenkins-artifactory-plugin#686]
**Describe the bug**
Artifactory plugin failing with java.lang.NullPointerException

**To Reproduce**
Whenever we try to upload artifacts, we face the below issue whenever we generate cloudbees jobs from Jobdsl for the first time we see this issue. And then once you reset "Override default deployer credentials" to none from Artifactory plugin parameter, and re-run the issue disappears. It's behaving weird.

**Expected behavior**
It has to upload artifacts to jfrog without null pointer exception even though you had over the credentials.
**Note**: I had already configured Artifactory plugin configuration globally in cloudbees with creds

**Screenshots**
<img width="1050" alt="image" src="https://user-images.githubusercontent.com/90752815/178139328-707e469b-8fce-4e3a-b579-1a9c3e18b237.png">
**Versions**
- Jenkins Artifactory plugin version: 3.16.2
- Jenkins operating system: [CloudBees CI Managed Controller 2.332.2.6-rolling](https://release-notes.cloudbees.com/product/141) 
- Artifactory Version: Enterprise Plus 7.37.14 rev 73714900 Licensed to Acquia, Inc.

**Additional context**
12:04:36 FATAL: null
12:04:36 java.lang.NullPointerException
12:04:36 	at org.jfrog.hudson.util.SpecUtils.getSpecStringFromSpecConf(SpecUtils.java:20)
12:04:36 	at org.jfrog.hudson.generic.ArtifactoryGenericConfigurator.setUp(ArtifactoryGenericConfigurator.java:375)
12:04:36 	at hudson.model.Build$BuildExecution.doRun(Build.java:158)
12:04:36 	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:522)
12:04:36 	at hudson.model.Run.execute(Run.java:1896)
12:04:36 	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:44)
12:04:36 	at hudson.model.ResourceController.execute(ResourceController.java:101)
12:04:36 	at hudson.model.Executor.run(Executor.java:442)

**Comment by pavan-acquia** [comment]
@yahavi 

Can you help check here

**Comment by MarkEWaite** [comment]
@pavan-acquia the Artifactory plugin is not "from CloudBees".  It is a Jenkins plugin that is provided by JFrog.
