### ISSUE TITLE
Fail-no-op: No files were affected in the upload process even though the file exists

### ISSUE THREAD

**Issue by c-semaan** [jfrog/jenkins-artifactory-plugin#711]
**Describe the bug**
I am running a jenkins pipeline that build a maven project and uploads the jar file to my local artifactory using rtUpload(). The jar is being built successfully and I can see that through the logs 

> "[INFO] Building jar: /var/lib/jenkins/workspace/Java Library Koario (Maven Pipeline)/target/JavaLibraryKoarioMaven-1.2-SNAPSHOT.jar BUILD SUCCESS"

Yet when I pass this in my pattern that can be found in my spec property it's always producing this error "java.lang.RuntimeException: Fail-no-op: No files were affected in the upload process." which shouldn't be the case. I tried the following patterns and none of them worked:

- $WORKSPACE/target/*.jar
- $WORKSPACE/target/*
- /var/lib/jenkins/workspace/Java Library Koario (Maven Pipeline)/target/JavaLibraryKoarioMaven-1.2-SNAPSHOT.jar

The only pattern that worked is "*" which is not useful for my case. Is this a bug or am I missing something?

Here is my pipeline:

```
pipeline {
    agent any

    environment {
        VERSION = "${env.BUILD_NUMBER}"
        PROJECT_REPO = 'http://176.31.98.125:3000/Charles/Jenkins_Test_Library.git'
        POM_DIR = 'pom.xml'
    }

    stages {
                stage('Artifactory Configuration') {
            steps {
                rtServer(
                    id: 'central',
                    url: 'http://192.168.1.115:8082/artifactory',
                    credentialsId: 'jfrog'
                )
            }
                }

        stage('Clone') {
            steps {
                git(
          url: PROJECT_REPO,
          credentialsId: 'git',
          branch: 'master'
      )
            }
        }

        stage('Build') {
            
                steps{
                script {
                    
                    pom = readMavenPom file: 'pom.xml'
                    env.PROJECT_NAME = pom.artifactId
                    sh 'mvn -B -DskipTests clean package'
                    sh 'rm upload-pom-*.xml'
                    sh "sed 's/REPLACE_VERSION_HERE/${env.VERSION}/g' upload-pom.xml > upload-pom-${env.VERSION}.xml"
                    echo "$WORKSPACE"
                    echo "${env.PROJECT_NAME}"
                    // zip zipFile: "${env.PROJECT_NAME}-${env.VERSION}-distribution.zip", archive: true, dir: 'dist'
                }
                }
            }
        
        stage('Artifactory Upload') {
            
        steps {
            
        rtUpload(
        serverId: 'central',
            spec: """{
          "files": [
            {
              "pattern": "$WORKSPACE/target/JavaLibraryKoarioMaven-1.2-SNAPSHOT.jar",
              "target": "koariomaven/com/koario/fr/JavaLibraryKoarioMaven/${env.VERSION}/"
            },
            {
            "pattern": "$WORKSPACE/upload-pom-${env.VERSION}.xml",
                  "target" : "koariomaven/com/koario/fr/JavaLibraryKoarioMaven/${env.VERSION}/"
            }
          ]
    }""",
        failNoOp: true)
            }
        }
    }
}

```

Here are my jenkins build logs:

> Started by user unknown or anonymous
> [Pipeline] Start of Pipeline
> [Pipeline] node
> Running on [Jenkins](http://192.168.1.115:8080/manage/computer/(built-in)/) in /var/lib/jenkins/workspace/Java Library Koario (Maven Pipeline)
> [Pipeline] {
> [Pipeline] withEnv
> [Pipeline] {
> [Pipeline] stage
> [Pipeline] { (Artifactory Configuration)
> [Pipeline] rtServer
> [Pipeline] }
> [Pipeline] // stage
> [Pipeline] stage
> [Pipeline] { (Clone)
> [Pipeline] git
> The recommended git tool is: NONE
> using credential git
>  > git rev-parse --resolve-git-dir /var/lib/jenkins/workspace/Java Library Koario (Maven Pipeline)/.git # timeout=10
> Fetching changes from the remote Git repository
>  > git config remote.origin.url http://176.31.98.125:3000/Charles/Jenkins_Test_Library.git # timeout=10
> Fetching upstream changes from http://176.31.98.125:3000/Charles/Jenkins_Test_Library.git
>  > git --version # timeout=10
>  > git --version # 'git version 2.34.1'
> using GIT_ASKPASS to set credentials 
>  > git fetch --tags --force --progress -- http://176.31.98.125:3000/Charles/Jenkins_Test_Library.git +refs/heads/*:refs/remotes/origin/* # timeout=10
>  > git rev-parse refs/remotes/origin/master^{commit} # timeout=10
> Checking out Revision a37457803e1620d813b16d47dfbdd51b52bf46a4 (refs/remotes/origin/master)
>  > git config core.sparsecheckout # timeout=10
>  > git checkout -f a37457803e1620d813b16d47dfbdd51b52bf46a4 # timeout=10
>  > git branch -a -v --no-abbrev # timeout=10
>  > git branch -D master # timeout=10
>  > git checkout -b master a37457803e1620d813b16d47dfbdd51b52bf46a4 # timeout=10
> Commit message: "testing scripts "
>  > git rev-list --no-walk a37457803e1620d813b16d47dfbdd51b52bf46a4 # timeout=10
> [Pipeline] }
> [Pipeline] // stage
> [Pipeline] stage
> [Pipeline] { (Build)
> [Pipeline] script
> [Pipeline] {
> [Pipeline] readMavenPom
> [Pipeline] sh
> + mvn -B -DskipTests clean package
> [INFO] Scanning for projects...
> [INFO] 
> [INFO] ----------------< com.koario.fr:JavaLibraryKoarioMaven >----------------
> [INFO] Building JavaLibraryKoarioMaven 1.2-SNAPSHOT
> [INFO] --------------------------------[ jar ]---------------------------------
> [INFO] 
> [INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ JavaLibraryKoarioMaven ---
> [INFO] Deleting /var/lib/jenkins/workspace/Java Library Koario (Maven Pipeline)/target
> [INFO] 
> [INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ JavaLibraryKoarioMaven ---
> [INFO] Using 'UTF-8' encoding to copy filtered resources.
> [INFO] skip non existing resourceDirectory /var/lib/jenkins/workspace/Java Library Koario (Maven Pipeline)/src/main/resources
> [INFO] 
> [INFO] --- maven-compiler-plugin:3.1:compile (default-compile) @ JavaLibraryKoarioMaven ---
> [INFO] Changes detected - recompiling the module!
> [INFO] Compiling 181 source files to /var/lib/jenkins/workspace/Java Library Koario (Maven Pipeline)/target/classes
> [WARNING] /var/lib/jenkins/workspace/Java Library Koario (Maven Pipeline)/src/main/java/framework/ThreadCalculPool.java: Some input files use or override a deprecated API.
> [WARNING] /var/lib/jenkins/workspace/Java Library Koario (Maven Pipeline)/src/main/java/framework/ThreadCalculPool.java: Recompile with -Xlint:deprecation for details.
> [WARNING] /var/lib/jenkins/workspace/Java Library Koario (Maven Pipeline)/src/main/java/framework/prototypes/ICalcul.java: Some input files use unchecked or unsafe operations.
> [WARNING] /var/lib/jenkins/workspace/Java Library Koario (Maven Pipeline)/src/main/java/framework/prototypes/ICalcul.java: Recompile with -Xlint:unchecked for details.
> [INFO] 
> [INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ JavaLibraryKoarioMaven ---
> [INFO] Using 'UTF-8' encoding to copy filtered resources.
> [INFO] skip non existing resourceDirectory /var/lib/jenkins/workspace/Java Library Koario (Maven Pipeline)/src/test/resources
> [INFO] 
> [INFO] --- maven-compiler-plugin:3.1:testCompile (default-testCompile) @ JavaLibraryKoarioMaven ---
> [INFO] No sources to compile
> [INFO] 
> [INFO] --- maven-surefire-plugin:2.12.4:test (default-test) @ JavaLibraryKoarioMaven ---
> [INFO] Tests are skipped.
> [INFO] 
> [INFO] --- maven-jar-plugin:2.4:jar (default-jar) @ JavaLibraryKoarioMaven ---
> [INFO] Building jar: /var/lib/jenkins/workspace/Java Library Koario (Maven Pipeline)/target/JavaLibraryKoarioMaven-1.2-SNAPSHOT.jar
> [INFO] ------------------------------------------------------------------------
> [INFO] BUILD SUCCESS
> [INFO] ------------------------------------------------------------------------
> [INFO] Total time:  7.150 s
> [INFO] Finished at: 2022-11-25T11:05:20+01:00
> [INFO] ------------------------------------------------------------------------
> [Pipeline] sh
> + rm upload-pom-103.xml
> [Pipeline] sh
> + sed s/REPLACE_VERSION_HERE/104/g upload-pom.xml
> [Pipeline] echo
> /var/lib/jenkins/workspace/Java Library Koario (Maven Pipeline)
> [Pipeline] echo
> JavaLibraryKoarioMaven
> [Pipeline] }
> [Pipeline] // script
> [Pipeline] }
> [Pipeline] // stage
> [Pipeline] stage
> [Pipeline] { (Artifactory Upload)
> [Pipeline] script
> [Pipeline] {
> [Pipeline] sh
> + ls /var/lib/jenkins/workspace/Java Library Koario (Maven Pipeline)/target/
> [Pipeline] echo
> FILES_LIST : classes
> generated-sources
> JavaLibraryKoarioMaven-1.2-SNAPSHOT.jar
> maven-archiver
> maven-status
> [Pipeline] echo
> >>>classes<<<
> [Pipeline] echo
> >>>generated-sources<<<
> [Pipeline] echo
> >>>JavaLibraryKoarioMaven-1.2-SNAPSHOT.jar<<<
> [Pipeline] echo
> >>>maven-archiver<<<
> [Pipeline] echo
> >>>maven-status<<<
> [Pipeline] }
> [Pipeline] // script
> [Pipeline] rtUpload
> Executing command: /bin/sh -c git log --pretty=format:%s -1
> [Pipeline] }
> [Pipeline] // stage
> [Pipeline] stage
> [Pipeline] { (Declarative: Post Actions)
> [Pipeline] emailext
> An attempt to send an e-mail to empty list of recipients, ignored.
> [Pipeline] }
> [Pipeline] // stage
> [Pipeline] }
> [Pipeline] // withEnv
> [Pipeline] }
> [Pipeline] // node
> [Pipeline] End of Pipeline
> java.lang.RuntimeException: Fail-no-op: No files were affected in the upload process.
> 	at org.jfrog.hudson.pipeline.common.executors.GenericUploadExecutor.execute(GenericUploadExecutor.java:59)
> 	at org.jfrog.hudson.pipeline.declarative.steps.generic.UploadStep$Execution.runStep(UploadStep.java:39)
> 	at org.jfrog.hudson.pipeline.declarative.steps.generic.UploadStep$Execution.runStep(UploadStep.java:24)
> 	at org.jfrog.hudson.pipeline.ArtifactorySynchronousNonBlockingStepExecution.run(ArtifactorySynchronousNonBlockingStepExecution.java:55)
> 	at org.jenkinsci.plugins.workflow.steps.SynchronousNonBlockingStepExecution.lambda$start$0(SynchronousNonBlockingStepExecution.java:47)
> 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
> 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
> 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
> 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
> 	at java.base/java.lang.Thread.run(Thread.java:829)
> /var/lib/jenkins/workspace/Java Library Koario (Maven Pipeline)@tmp/jfrog/104/.jfrog deleted
> Finished: FAILURE

The jar file exists. I have checked the path in my code and even in the jenkins workspace. Only pattern that works and does the upload is "*". Please assist if possible.

**Versions**
- Jenkins Artifactory plugin version: 3.17.3
- Jenkins operating system: Ubuntu
- Artifactory Version: 7.46.11 rev 74611900

**Comment by c-semaan** [comment]
fixed it by doing this;

            {
              "pattern": "target/*.jar",
              "target": "koariomaven/com/koario/fr/JavaLibraryKoarioMaven/${env.VERSION}/"
            },
            {
            "pattern": "upload-pom-${env.VERSION}.xml",
                  "target" : "koariomaven/com/koario/fr/JavaLibraryKoarioMaven/${env.VERSION}/"
            }

I still don't get it how a definitive path is not being picked up...
