### ISSUE TITLE
Plugin should pull in jersey2 libraries via jersey2-api plugin to not conflict with other plugins

### ISSUE THREAD

**Issue by jakegt1** [jfrog/jenkins-artifactory-plugin#735]
**Describe the bug**
Artifactory jenkins plugin packages jersey2 libraries via transitive dependency on build-info-extractor. This causes jersey-hk2 failures if any other jersey-dependant plugin is installed (For example, GitLab Branch Source plugin.)

**To Reproduce**
1. Install Jenkins artifactory plugin
2. Install Gitlab Branch Source plugin
3. Set up multibranch pipeline with gitlab branch source plugin
4. Triggers will fail to update gitlab with jersey-hk2 errors

**Expected behavior**
Jenkins artifactory plugin does not conflict with other plugins.

**Screenshots**
N/A

**Versions**
- Jenkins Artifactory plugin version: 3.18.0
- Jenkins operating system: 2.346.2
- Artifactory Version: N/A as due to it breaking other plugins

**Additional context**

**Comment by usinelogicielle** [comment]
We have the same problem right now when upgraging Jenkins.
This plugin use jersey2 jar but not the plugin.
And different version is used with other plugin.
And we have exception because of that

```bash
Apr 12, 2023 2:51:32 PM INFO io.jenkins.plugins.gitlabbranchsource.helpers.GitLabPipelineStatusNotifier$JobScheduledListener lambda$onEnterWaiting$0
Querying the current revision of branch <branch_name>...
Apr 12, 2023 2:51:32 PM WARNING io.jenkins.plugins.gitlabbranchsource.GitLabSCMSource retrieve
Exception caught:org.gitlab4j.api.GitLabApiException: Cannot cast org.glassfish.jersey.inject.hk2.Hk2InjectionManagerFactory to org.glassfish.jersey.internal.inject.InjectionManagerFactory
java.lang.ClassCastException: Cannot cast org.glassfish.jersey.inject.hk2.Hk2InjectionManagerFactory to org.glassfish.jersey.internal.inject.InjectionManagerFactory
        at java.base/java.lang.Class.cast(Class.java:3605)
        at org.glassfish.jersey.internal.ServiceFinder$LazyObjectIterator.hasNext(ServiceFinder.java:690)
        at org.glassfish.jersey.internal.inject.Injections.lookupService(Injections.java:88)
        at org.glassfish.jersey.internal.inject.Injections.lookupInjectionManagerFactory(Injections.java:73)
        at org.glassfish.jersey.internal.inject.Injections.createInjectionManager(Injections.java:44)
        at org.glassfish.jersey.client.ClientConfig$State.initRuntime(ClientConfig.java:413)
        at org.glassfish.jersey.internal.util.collection.Values$LazyValueImpl.get(Values.java:317)
        at org.glassfish.jersey.client.ClientConfig.getRuntime(ClientConfig.java:820)
        at org.glassfish.jersey.client.ClientRequest.getClientRuntime(ClientRequest.java:176)
        at org.glassfish.jersey.client.ClientRequest.getInjectionManager(ClientRequest.java:567)
        at org.glassfish.jersey.client.JerseyWebTarget.onBuilder(JerseyWebTarget.java:371)
        at org.glassfish.jersey.client.JerseyWebTarget.request(JerseyWebTarget.java:199)
        at org.glassfish.jersey.client.JerseyWebTarget.request(JerseyWebTarget.java:38)
        at org.gitlab4j.api.GitLabApiClient.invocation(GitLabApiClient.java:808)
        at org.gitlab4j.api.GitLabApiClient.invocation(GitLabApiClient.java:772)
        at org.gitlab4j.api.GitLabApiClient.get(GitLabApiClient.java:416)
        at org.gitlab4j.api.GitLabApiClient.get(GitLabApiClient.java:404)
        at org.gitlab4j.api.AbstractApi.get(AbstractApi.java:214)
Caused: org.gitlab4j.api.GitLabApiException: Cannot cast org.glassfish.jersey.inject.hk2.Hk2InjectionManagerFactory to org.glassfish.jersey.internal.inject.InjectionManagerFactory
        at org.gitlab4j.api.AbstractApi.handle(AbstractApi.java:664)
        at org.gitlab4j.api.AbstractApi.get(AbstractApi.java:216)
        at org.gitlab4j.api.RepositoryApi.getBranch(RepositoryApi.java:110)
        at io.jenkins.plugins.gitlabbranchsource.GitLabSCMSource.retrieve(GitLabSCMSource.java:258)
        at jenkins.scm.api.SCMSource.fetch(SCMSource.java:582)
        at io.jenkins.plugins.gitlabbranchsource.helpers.GitLabPipelineStatusNotifier$JobScheduledListener.lambda$onEnterWaiting$0(GitLabPipelineStatusNotifier.java:388)
        at jenkins.util.ContextResettingExecutorService$1.run(ContextResettingExecutorService.java:30)
        at jenkins.security.ImpersonatingExecutorService$1.run(ImpersonatingExecutorService.java:70)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:829)

Apr 12, 2023 2:51:32 PM INFO io.jenkins.plugins.gitlabbranchsource.helpers.GitLabPipelineStatusNotifier$JobScheduledListener lambda$onEnterWaiting$0
Could not send commit status notification for <gitlab_project> to default
java.lang.ClassCastException: Cannot cast org.glassfish.jersey.inject.hk2.Hk2InjectionManagerFactory to org.glassfish.jersey.internal.inject.InjectionManagerFactory
        at java.base/java.lang.Class.cast(Class.java:3605)
        at org.glassfish.jersey.internal.ServiceFinder$LazyObjectIterator.hasNext(ServiceFinder.java:690)
        at org.glassfish.jersey.internal.inject.Injections.lookupService(Injections.java:88)
        at org.glassfish.jersey.internal.inject.Injections.lookupInjectionManagerFactory(Injections.java:73)
        at org.glassfish.jersey.internal.inject.Injections.createInjectionManager(Injections.java:44)
        at org.glassfish.jersey.client.ClientConfig$State.initRuntime(ClientConfig.java:413)
        at org.glassfish.jersey.internal.util.collection.Values$LazyValueImpl.get(Values.java:317)
        at org.glassfish.jersey.client.ClientConfig.getRuntime(ClientConfig.java:820)
        at org.glassfish.jersey.client.ClientRequest.getClientRuntime(ClientRequest.java:176)
        at org.glassfish.jersey.client.ClientRequest.getInjectionManager(ClientRequest.java:567)
        at org.glassfish.jersey.client.JerseyWebTarget.onBuilder(JerseyWebTarget.java:371)
        at org.glassfish.jersey.client.JerseyWebTarget.request(JerseyWebTarget.java:199)
        at org.glassfish.jersey.client.JerseyWebTarget.request(JerseyWebTarget.java:38)
        at org.gitlab4j.api.GitLabApiClient.invocation(GitLabApiClient.java:808)
        at org.gitlab4j.api.GitLabApiClient.invocation(GitLabApiClient.java:772)
        at org.gitlab4j.api.GitLabApiClient.get(GitLabApiClient.java:416)
        at org.gitlab4j.api.GitLabApiClient.get(GitLabApiClient.java:404)
        at org.gitlab4j.api.AbstractApi.get(AbstractApi.java:214)
Caused: org.gitlab4j.api.GitLabApiException: Cannot cast org.glassfish.jersey.inject.hk2.Hk2InjectionManagerFactory to org.glassfish.jersey.internal.inject.InjectionManagerFactory
        at org.gitlab4j.api.AbstractApi.handle(AbstractApi.java:664)
        at org.gitlab4j.api.AbstractApi.get(AbstractApi.java:216)
        at org.gitlab4j.api.RepositoryApi.getBranch(RepositoryApi.java:110)
        at io.jenkins.plugins.gitlabbranchsource.GitLabSCMSource.retrieve(GitLabSCMSource.java:258)
Caused: java.io.IOException: Failed to retrieve the SCM revision for <branch_name>
        at io.jenkins.plugins.gitlabbranchsource.GitLabSCMSource.retrieve(GitLabSCMSource.java:298)
        at jenkins.scm.api.SCMSource.fetch(SCMSource.java:582)
        at io.jenkins.plugins.gitlabbranchsource.helpers.GitLabPipelineStatusNotifier$JobScheduledListener.lambda$onEnterWaiting$0(GitLabPipelineStatusNotifier.java:388)
        at jenkins.util.ContextResettingExecutorService$1.run(ContextResettingExecutorService.java:30)
        at jenkins.security.ImpersonatingExecutorService$1.run(ImpersonatingExecutorService.java:70)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:829)
```

The ticket in gitlab-branch-source https://github.com/jenkinsci/gitlab-branch-source-plugin/issues/302

**Comment by jakegt1** [comment]
@usinelogicielle arrifactory plugin is the problem, not gitlab.

**Comment by RobiNino** [comment]
Hi @jakegt1 @usinelogicielle ,
Plugin version 4.0.6 was just released and includes a fix to this issue.
@jakegt1 Thank you again for your contribution and patience!
