### ISSUE TITLE
Gradle-based publishing hangs indefinitely

### ISSUE THREAD

**Issue by rainerfrey-inxmail** [jfrog/jenkins-artifactory-plugin#741]
**Describe the bug**
In projects with the gradle artifactory plugin applied, the Jenkins step `rtGradleRun` hangs indefinitely when executing `gradle artifactoryPublish` *after* successfully publishing the artifacts

**To Reproduce**
Jenkins multi-branch pipeline job with this excerpt in the pipeline:
```groovy
                container( 'gradle' ) {
                    rtBuildInfo (
                            captureEnv: true,
                            maxBuilds: (env.BRANCH_NAME == 'master') ? 10 : 3,
                            buildName: env.JOB_NAME.replace( '/', '_' ),
                            buildNumber: VERSION_APPENDIX // defined earlier in Jenkinsfile
                    )

                    rtGradleResolver (
                            id: "resolver-platform",
                            serverId: "from-global-jenkins-config",
                            repo: "platform.resolve"
                    )

                    rtGradleDeployer (
                            id: "deployer-platform",
                            serverId: "from-global-jenkins-config",
                            repo: "platform.lib.local",
                            deployMavenDescriptors: true
                    )

                    rtGradleRun (
                            usesPlugin: true,
                            useWrapper: true,
                            buildFile: 'build.gradle',
                            tasks: 'clean artifactoryPublish',
                            resolverId: "resolver-platform",
                            deployerId: "deployer-platform"
                    )

                    rtPublishBuildInfo (
                            serverId: "from-global-jenkins-config"
                    )
                }
```

**Expected behavior**
Build continues and terminates successfully

**Screenshots**
```
10:30:07.662  [Pipeline] container
10:30:07.700  [Pipeline] {
10:30:07.854  [Pipeline] rtBuildInfo
10:30:16.514  [Pipeline] rtGradleResolver
10:30:16.729  [Pipeline] rtGradleDeployer
10:30:16.922  [Pipeline] rtGradleRun
10:30:19.305  [DEPRECATION]: The "buildFile" parameter is deprecated because its value is used for the -b option of Gradle. This option has been declared as deprecated by Gradle and will no longer work since Gradle 8. Please use the "rootDir" parameter only. Its value should be the path to the directory which includes the build.gradle file.
10:30:19.306  Executing sh script inside container gradle of pod aborted-sendings-dd805ce2-382c-42f5-87f5-11d1c7159059-3tg-4rkjp
10:30:18.509  Executing command: /bin/sh -c git log --pretty=format:%s -1
10:30:19.602  Executing command: "/home/jenkins/agent/workspace/xpv-aborted-sendings_jenkinstest/gradlew" "clean" "artifactoryPublish" "-b" "build.gradle" 
10:30:19.602  exit
10:30:22.119  > Task :clean
10:30:24.111  > Task :compileJava
10:30:24.111  > Task :compileGroovy NO-SOURCE
10:30:24.111  > Task :processResources NO-SOURCE
10:30:24.112  > Task :classes
10:30:24.211  > Task :jar
10:30:24.211  > Task :assemble
10:30:24.411  > Task :generateMetadataFileForMavenJavaPublication
10:30:25.111  > Task :generatePomFileForMavenJavaPublication
10:30:29.411  > Task :javadoc
10:30:29.511  > Task :javadocJar
10:30:29.511  > Task :sourcesJar
10:30:29.611  > Task :artifactoryPublish
10:30:30.011  > Task :extractModuleInfo
10:30:30.111  [pool-1-thread-1] Deploying artifact: https://redacted-1.1.2023-02-02_10-26-37-javadoc.jar
10:30:30.711  [pool-1-thread-1] Deploying artifact: https://redacted-1.1.2023-02-02_10-26-37-sources.jar
10:30:30.711  [pool-1-thread-1] Deploying artifact: https://redacted-1.1.2023-02-02_10-26-37.jar
10:30:30.811  [pool-1-thread-1] Deploying artifact: https://redacted-1.1.2023-02-02_10-26-37.module
10:30:30.811  [pool-1-thread-1] Deploying artifact: https://redacted-1.1.2023-02-02_10-26-37.pom
10:30:31.011  > Task :artifactoryDeploy
10:30:31.011  
10:30:31.011  Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.
10:30:31.011  
10:30:31.011  You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.
10:30:31.011  
10:30:31.011  See https://docs.gradle.org/7.6/userguide/command_line_interface.html#sec:command_line_warnings
10:30:31.011  
10:30:31.011  BUILD SUCCESSFUL in 11s
10:30:31.011  11 actionable tasks: 11 executed
10:49:18.334  Aborted by [Rainer Frey]
10:49:18.337  ERROR: Couldn't execute Gradle task. InterruptedException:
10:49:21.928  java.lang.InterruptedException
10:49:21.928  	at java.base/java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireSharedInterruptibly(AbstractQueuedSynchronizer.java:1048)
10:49:21.928  	at java.base/java.util.concurrent.CountDownLatch.await(CountDownLatch.java:230)
10:49:21.928  	at org.csanchez.jenkins.plugins.kubernetes.pipeline.ContainerExecProc.join(ContainerExecProc.java:87)
10:49:21.928  	at hudson.Launcher$ProcStarter.join(Launcher.java:534)
10:49:21.928  	at org.jfrog.hudson.pipeline.common.Utils.launch(Utils.java:278)
10:49:21.928  Caused: java.lang.RuntimeException: Gradle build failed. Couldn't execute Gradle task. InterruptedException: 
10:49:21.928  	at org.jfrog.hudson.pipeline.common.Utils.launch(Utils.java:285)
10:49:21.928  	at org.jfrog.hudson.pipeline.common.executors.GradleExecutor.execute(GradleExecutor.java:75)
10:49:21.928  	at org.jfrog.hudson.pipeline.declarative.steps.gradle.GradleStep$Execution.runStep(GradleStep.java:128)
10:49:21.928  	at org.jfrog.hudson.pipeline.declarative.steps.gradle.GradleStep$Execution.runStep(GradleStep.java:113)
10:49:21.928  	at org.jfrog.hudson.pipeline.ArtifactorySynchronousNonBlockingStepExecution.run(ArtifactorySynchronousNonBlockingStepExecution.java:55)
10:49:21.928  	at org.jenkinsci.plugins.workflow.steps.SynchronousNonBlockingStepExecution.lambda$start$0(SynchronousNonBlockingStepExecution.java:47)
10:49:21.928  	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
10:49:21.928  	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
10:49:21.928  	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
10:49:21.928  	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
10:49:21.928  	at java.base/java.lang.Thread.run(Thread.java:833)
```

**Versions**
- Jenkins Artifactory plugin version: 3.18.0 and 3.17.4
- Jenkins operating system: Kubernetes / official Docker image / Kubernetes plugin for agents
- Jenkins Version: 2.375.2 LTS
- Artifactory Version: 7.38.10
- Gradle Artifactory Plugin version: 4.31.0 / 4.25.1
- Gradle versions 7.4, 7.4.2, 7.6

**Additional context**
Note that the gradle build reports to be finished, yet the Jenkins pipeline step continues to execute/block. Jenkins and Artifactory plugin were upgraded at the same time, I then tested to downgrade the artifactory plugin, but that proved unsuccessful.

Builds that use `rtUpload` and `rtDockerPush` (with similar build-info configurations) execute and finish successfully.

**Comment by rainerfrey-inxmail** [comment]
This problem still persists after upgrading Jenkins to [Jenkins 2.387.1](https://www.jenkins.io/)

**Comment by kh0ma** [comment]
We faced the same with maven build. 

The issue is intermittent. Some of the builds stuck, and some no. 

When connecting to the container where maven was executing - all the processes are stopped.

@rainerfrey-inxmail have you found anything that has helped you so far?

**Comment by rainerfrey-inxmail** [comment]
> @rainerfrey-inxmail have you found anything that has helped you so far?

No, but we switched a few affected builds to the alternative jfrog (cli) plugin https://plugins.jenkins.io/jfrog/

**Comment by swamygoud18** [comment]
I do see this issue very repeatedly and have enough number services depends on this functionality and it was so frustrating since couple of week. I have raise bug/issue in jenkins - https://issues.jenkins.io/browse/JENKINS-71708

" when I gone into more details - I could able to trace down that it is the issue with launcher what they using to run the commands and  if it is just RemoteLauncher everything goes good other than that it just times out/hangs post task execution.

I could able to debug a little and it seems the - https://github.com/jenkinsci/artifactory-plugin/blob/master/src/main/java/org/jfrog/hudson/pipeline/common/Utils.java # line # 278 is just hanging there with launcher launcher org.csanchez.jenkins.plugins.kubernetes.pipeline.ContainerExecDecorator which was with pipeline kuberentes agent.

but goes good when we use node with scripted pipeline which is using the launcher RemoteLauncher[hudson.remoting.Channel "

I have submitted PR with Fix which is creating the default RemoteLauncher all the time and works great. If you guys want you can have snapshot of it and test.?
