### ISSUE TITLE
Artifactory upload failing for unicode characters in file names

### ISSUE THREAD

**Issue by forry** [jfrog/jenkins-artifactory-plugin#742]
**Describe the bug**
When uploading a batch of files with rtUpload when using version 3.10.6 everything works fine. After I tried to update (most recently I have tried it with 3.18.0) the upload failed when encountering a file with an umlaut in the name. It's on win10 jenkins agent.

**To Reproduce**
I have a file named Trägerbohlwand.png.zip in some folder. In a declarative pipeline, I use this command:
```
rtUpload(
    serverId: '***',
    spec: """{
       "files": 
       [
          {
             "pattern": "./*",
             "target": "something/somewhere/",
             "flat": false
          }
       ]
      }""",
   buildNumber: "${REVISION_NUMBER}"
)
```

**Expected behavior**
Upload the files.

**Versions**
- Jenkins Artifactory plugin version: 3.18.0
- Jenkins version: 2.375.3
- Jenkins operating system: win10 agent, linux master
- Artifactory Version: Conan edition 7.49.6 and also 6.15.0

**Additional context**
We have also tried things like starting the agent with -Dfile.encoding=UTF-8 as a JVM argument and other things. And we have pinpointed this to the AF plugin being the problem.
It fails either with just "Failed uploading artifacts by spec" or it produces a stack trace into a console output. I use *** to hide our URL.
```
[consumer_1] Deploying artifact: [***/./BuildingBlocks/12/0/Tr%C3%A4gerbohlwand.png.zip](***/BuildingBlocks/12/0/Tr%C3%A4gerbohlwand.png.zip)

[consumer_0] Deploying artifact: [***/./BuildingBlocks/12/0/Tr%C3%A4gerbohlwand.py.zip](***/BuildingBlocks/12/0/Tr%C3%A4gerbohlwand.py.zip)

[consumer_1] An exception occurred during execution:
java.lang.RuntimeException: com.fasterxml.jackson.databind.JsonMappingException: Invalid UTF-8 middle byte 0x67
 at [Source: (org.apache.http.conn.EofSensorInputStream); line: 3, column: 68] (through reference chain: org.jfrog.build.client.ArtifactoryUploadResponse["path"])
	at org.jfrog.build.extractor.clientConfiguration.util.spec.SpecDeploymentConsumer.consumerRun(SpecDeploymentConsumer.java:44)
	at org.jfrog.build.extractor.producerConsumer.ConsumerRunnableBase.run(ConsumerRunnableBase.java:11)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: com.fasterxml.jackson.databind.JsonMappingException: Invalid UTF-8 middle byte 0x67
 at [Source: (org.apache.http.conn.EofSensorInputStream); line: 3, column: 68] (through reference chain: org.jfrog.build.client.ArtifactoryUploadResponse["path"])
	at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:402)
	at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:361)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.wrapAndThrow(BeanDeserializerBase.java:1826)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:316)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:177)
	at com.fasterxml.jackson.databind.deser.DefaultDeserializationContext.readRootValue(DefaultDeserializationContext.java:323)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4730)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3714)
	at org.jfrog.build.extractor.clientConfiguration.client.artifactory.services.Upload.setResponse(Upload.java:65)
	at org.jfrog.build.extractor.clientConfiguration.client.JFrogService.processResponse(JFrogService.java:143)
	at org.jfrog.build.extractor.clientConfiguration.client.JFrogService.execute(JFrogService.java:123)
	at org.jfrog.build.extractor.clientConfiguration.client.artifactory.services.Upload.execute(Upload.java:77)
	at org.jfrog.build.extractor.clientConfiguration.client.artifactory.ArtifactoryManager.upload(ArtifactoryManager.java:267)
	at org.jfrog.build.extractor.clientConfiguration.client.artifactory.ArtifactoryManager.upload(ArtifactoryManager.java:262)
	at org.jfrog.build.extractor.clientConfiguration.util.spec.SpecDeploymentConsumer.consumerRun(SpecDeploymentConsumer.java:39)
	... 2 more
Caused by: com.fasterxml.jackson.core.JsonParseException: Invalid UTF-8 middle byte 0x67
 at [Source: (org.apache.http.conn.EofSensorInputStream); line: 3, column: 68]
	at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:2418)
	at com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:749)
	at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._reportInvalidOther(UTF8StreamJsonParser.java:3710)
	at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._reportInvalidOther(UTF8StreamJsonParser.java:3717)
	at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._decodeUtf8_3fast(UTF8StreamJsonParser.java:3523)
	at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._finishString2(UTF8StreamJsonParser.java:2606)
	at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._finishAndReturnString(UTF8StreamJsonParser.java:2554)
	at com.fasterxml.jackson.core.json.UTF8StreamJsonParser.getText(UTF8StreamJsonParser.java:334)
	at com.fasterxml.jackson.databind.deser.std.StringDeserializer.deserialize(StringDeserializer.java:42)
	at com.fasterxml.jackson.databind.deser.std.StringDeserializer.deserialize(StringDeserializer.java:11)
	at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:129)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:314)
	... 13 more
[consumer_0] An exception occurred during execution:
java.lang.RuntimeException: com.fasterxml.jackson.databind.JsonMappingException: Invalid UTF-8 middle byte 0x67
 at [Source: (org.apache.http.conn.EofSensorInputStream); line: 3, column: 68] (through reference chain: org.jfrog.build.client.ArtifactoryUploadResponse["path"])
	at org.jfrog.build.extractor.clientConfiguration.util.spec.SpecDeploymentConsumer.consumerRun(SpecDeploymentConsumer.java:44)
	at org.jfrog.build.extractor.producerConsumer.ConsumerRunnableBase.run(ConsumerRunnableBase.java:11)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: com.fasterxml.jackson.databind.JsonMappingException: Invalid UTF-8 middle byte 0x67
 at [Source: (org.apache.http.conn.EofSensorInputStream); line: 3, column: 68] (through reference chain: org.jfrog.build.client.ArtifactoryUploadResponse["path"])
	at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:402)
	at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:361)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.wrapAndThrow(BeanDeserializerBase.java:1826)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:316)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:177)
	at com.fasterxml.jackson.databind.deser.DefaultDeserializationContext.readRootValue(DefaultDeserializationContext.java:323)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4730)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3714)
	at org.jfrog.build.extractor.clientConfiguration.client.artifactory.services.Upload.setResponse(Upload.java:65)
	at org.jfrog.build.extractor.clientConfiguration.client.JFrogService.processResponse(JFrogService.java:143)
	at org.jfrog.build.extractor.clientConfiguration.client.JFrogService.execute(JFrogService.java:123)
	at org.jfrog.build.extractor.clientConfiguration.client.artifactory.services.Upload.execute(Upload.java:77)
	at org.jfrog.build.extractor.clientConfiguration.client.artifactory.ArtifactoryManager.upload(ArtifactoryManager.java:267)
	at org.jfrog.build.extractor.clientConfiguration.client.artifactory.ArtifactoryManager.upload(ArtifactoryManager.java:262)
	at org.jfrog.build.extractor.clientConfiguration.util.spec.SpecDeploymentConsumer.consumerRun(SpecDeploymentConsumer.java:39)
	... 2 more
Caused by: com.fasterxml.jackson.core.JsonParseException: Invalid UTF-8 middle byte 0x67
 at [Source: (org.apache.http.conn.EofSensorInputStream); line: 3, column: 68]
	at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:2418)
	at com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:749)
	at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._reportInvalidOther(UTF8StreamJsonParser.java:3710)
	at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._reportInvalidOther(UTF8StreamJsonParser.java:3717)
	at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._decodeUtf8_3fast(UTF8StreamJsonParser.java:3523)
	at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._finishString2(UTF8StreamJsonParser.java:2606)
	at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._finishAndReturnString(UTF8StreamJsonParser.java:2554)
	at com.fasterxml.jackson.core.json.UTF8StreamJsonParser.getText(UTF8StreamJsonParser.java:334)
	at com.fasterxml.jackson.databind.deser.std.StringDeserializer.deserialize(StringDeserializer.java:42)
	at com.fasterxml.jackson.databind.deser.std.StringDeserializer.deserialize(StringDeserializer.java:11)
	at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:129)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:314)
	... 13 more
```

**Comment by TIBCOrkrajews** [comment]
Still happening with Artifactory Plugin 3.18.1.
