### ISSUE TITLE
NPE on pipeline job over docker maven 3.9.0 / JDK 11 image

### ISSUE THREAD

**Issue by draco31fr** [jfrog/jenkins-artifactory-plugin#747]
**Describe the bug**
Jenkins pipeline job ends with NullPointerException since docker image maven:3-eclipse-temurin-11 has been updated to Maven 3.9.0

**To Reproduce**
Inside docker image maven:3.9.0-eclipse-temurin-11, execute "install" goal with Artifactory plugin.
Our groovy code is :
```
                def server = pipeline.Artifactory.server params.deploy.artifact.serverId

                def rt = pipeline.Artifactory.newMavenBuild()
                rt.deployer server: server, releaseRepo: 'xxx', snapshotRepo: 'yyy'
                def buildInfo = pipeline.Artifactory.newBuildInfo()
                buildInfo = rt.run pom: 'pom.xml', goals: 'install', buildInfo: buildInfo
                rt.deployer.deployArtifacts buildInfo
                server.publishBuildInfo buildInfo
```

The job end with the following error :
```
java.lang.RuntimeException: Maven build failed with exit code 1
	at org.jfrog.hudson.pipeline.common.Utils.launch(Utils.java:280)
Caused: java.lang.RuntimeException: Maven build failed. Couldn't execute Maven task. RuntimeException: Maven build failed with exit code 1
	at org.jfrog.hudson.pipeline.common.Utils.launch(Utils.java:285)
	at org.jfrog.hudson.maven3.Maven3Builder.RunMaven(Maven3Builder.java:121)
	at org.jfrog.hudson.maven3.Maven3Builder.perform(Maven3Builder.java:116)
	at org.jfrog.hudson.pipeline.common.executors.MavenExecutor.execute(MavenExecutor.java:72)
	at org.jfrog.hudson.pipeline.scripted.steps.ArtifactoryMavenBuild$Execution.runStep(ArtifactoryMavenBuild.java:65)
	at org.jfrog.hudson.pipeline.scripted.steps.ArtifactoryMavenBuild$Execution.runStep(ArtifactoryMavenBuild.java:51)
	at org.jfrog.hudson.pipeline.ArtifactorySynchronousNonBlockingStepExecution.run(ArtifactorySynchronousNonBlockingStepExecution.java:54)
	at org.jenkinsci.plugins.workflow.steps.SynchronousNonBlockingStepExecution.lambda$start$0(SynchronousNonBlockingStepExecution.java:47)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Finished: FAILURE
```

**Expected behavior**
Install goal is executed, and artifacts and build info are uploaded.

**Screenshots**
Running with -X -e options produce the following log : 
[maven-verbose-sanitized.log](https://github.com/jfrog/jenkins-artifactory-plugin/files/10764772/maven-verbose-sanitized.log)

**Versions**
- Jenkins Artifactory plugin version: 3.16.2
- Jenkins operating system: Debian + docker
- Artifactory Version: 7.10.6 rev 71006900

**Additional context**
A `mvn clean deploy` with Maven 3.9.0 / JDK 11 version does not throw NPE on windows.
Same pipeline job with maven:3.8-eclipse-temurin-11 image is OK.

**Comment by knoobie** [comment]
@yahavi Do you happen to have time to look at this? This is critical and makes the integration from Jenkins to Artifactory (Pro / Enterprise etc.) broken. There is also a highly upvoted Jenkins Issue about the same problem: https://issues.jenkins.io/browse/JENKINS-70654

**Comment by yahavi** [comment]
@draco31fr @knoobie,
Thanks for reporting this issue!
This issue is expected to be resolved in Jenkins Artifactory plugin 3.18.1 by https://github.com/jfrog/build-info/pull/718 and https://github.com/jfrog/build-info/pull/706.
That was a breaking change in Maven 3.9.0.

Please feel free to upgrade to the latest version. We'd appreciate your feedback on that.
