### ISSUE TITLE
Publishing a build with a commit message containing a '|' character can result in a 400 error

### ISSUE THREAD

**Issue by derekscp** [jfrog/jenkins-artifactory-plugin#755]
**Describe the bug**
When creating a build with the plugin it takes the commit message in a build and publishes it as the vcs.message property. There does not look to be a way to disable this.

When you have a '|' character as the commit message it will try and publish everything after the pipe as another property.
An example of a commit message:
`JIRA-123 | Fix for display issue`

A simplified message to reproduce this is:
`|test test`

This will produce a 400 error because the whitespace is an illegal character for a key value as per setting item properties in Artifactory.
https://www.jfrog.com/confluence/display/JFROG/Artifactory+REST+API#ArtifactoryRESTAPI-ItemProperties
```
The following special characters are forbidden in the key field: )(}{][*+^$\/~`!@#%&<>;=,±§ and the Space character.
```

**To Reproduce**
This issue was seen in publishing a Docker build and can be reproduced with this project example.
https://github.com/jfrog/project-examples/blob/5dc9e29c98dc8292cd46c0a6f4455d62f128959a/jenkins-examples/pipeline-examples/scripted-examples/docker-push-example/Jenkinsfile
Fork this project and in your own environment, you can perform the following changes needed.
1. In Jenkins, add the above jenkins file into a pipeline replacing the Variables and Fields as needed for your environment.
2. Then all that needs to be done to reproduce is to add a commit to your fork on the [Dockerfile](https://github.com/jfrog/project-examples/blob/master/jenkins-examples/pipeline-examples/resources/Dockerfile) and add a commit message like:
`|test test`
3. Then run the Jenkins build and observe the build failure.

**Expected behavior**
I would expect that either the vcs.message can be disabled from publishing to Artifactory with the build to prevent this.
Preferably I would expect that the vcs.message be sanitized so that it is sent as an entire value instead of being split up.

**Additional Context**
Here is the error in the build pipeline after it tries to publish the build.
```
Mar 14, 2023 10:02:20 PM org.jfrog.build.extractor.packageManager.PackageManagerLogger error
SEVERE: Failed to set properties to  'test-docker/some-world/latest/manifest.json'
Mar 14, 2023 10:02:20 PM org.jfrog.build.extractor.packageManager.PackageManagerLogger error
SEVERE: JFrog service failed. Received 400: {
  "errors" : [ {
    "status" : 400,
    "message" : "Name must start with a letter and cannot contain whitespace or special characters"
  } ]
}
java.io.IOException: JFrog service failed. Received 400: {
  "errors" : [ {
    "status" : 400,
    "message" : "Name must start with a letter and cannot contain whitespace or special characters"
  } ]
}
	at org.jfrog.build.extractor.clientConfiguration.client.JFrogService.throwException(JFrogService.java:49)
	at org.jfrog.build.extractor.clientConfiguration.client.artifactory.services.SetProperties.handleUnsuccessfulResponse(SetProperties.java:56)
	at org.jfrog.build.extractor.clientConfiguration.client.JFrogService.execute(JFrogService.java:121)
	at org.jfrog.build.extractor.clientConfiguration.client.artifactory.ArtifactoryManager.setProperties(ArtifactoryManager.java:79)
	at org.jfrog.build.extractor.docker.extractor.DockerPush.setImageLayersProps(DockerPush.java:113)
	at org.jfrog.build.extractor.docker.extractor.DockerPush.execute(DockerPush.java:91)
	at org.jfrog.build.extractor.packageManager.PackageManagerExtractor.executeAndSaveBuildInfo(PackageManagerExtractor.java:33)
	at org.jfrog.build.extractor.docker.extractor.DockerPush.main(DockerPush.java:69)

java.io.IOException: JFrog service failed. Received 400: {
  "errors" : [ {
    "status" : 400,
    "message" : "Name must start with a letter and cannot contain whitespace or special characters"
  } ]
}
	at org.jfrog.build.extractor.clientConfiguration.client.JFrogService.throwException(JFrogService.java:49)
	at org.jfrog.build.extractor.clientConfiguration.client.artifactory.services.SetProperties.handleUnsuccessfulResponse(SetProperties.java:56)
	at org.jfrog.build.extractor.clientConfiguration.client.JFrogService.execute(JFrogService.java:121)
	at org.jfrog.build.extractor.clientConfiguration.client.artifactory.ArtifactoryManager.setProperties(ArtifactoryManager.java:79)
	at org.jfrog.build.extractor.docker.extractor.DockerPush.setImageLayersProps(DockerPush.java:113)
	at org.jfrog.build.extractor.docker.extractor.DockerPush.execute(DockerPush.java:91)
 [wrapped] java.lang.RuntimeException: java.io.IOException: JFrog service failed. Received 400: {
  "errors" : [ {
    "status" : 400,
    "message" : "Name must start with a letter and cannot contain whitespace or special characters"
  } ]
}
	at org.jfrog.build.extractor.docker.extractor.DockerPush.execute(DockerPush.java:100)
	at org.jfrog.build.extractor.packageManager.PackageManagerExtractor.executeAndSaveBuildInfo(PackageManagerExtractor.java:33)
	at org.jfrog.build.extractor.docker.extractor.DockerPush.main(DockerPush.java:69)
ERROR: Couldn't execute docker task. RuntimeException: docker build failed with exit code 1
```

**Versions**
- Jenkins Artifactory plugin version: 3.18.0
- Jenkins operating system: 2.375.3
- Artifactory Version: 7.38.8

**Comment by attiasas** [comment]
Issue resolved and the released version with the fix is 3.18.1
We will appreciate your feedback.
