### ISSUE TITLE
NoSuchFileException in version 4.0.1

### ISSUE THREAD

**Issue by denis-matchenko** [jfrog/jenkins-artifactory-plugin#910]
**Describe the bug**
Such an error occurs in the `4.0.1` version, there is no error in version `4.0.0`
```
13:40:30  hudson.remoting.ProxyException: java.nio.file.NoSuchFileException: /home/jenkins/workspace/cloud_master@tmp/artifactory/buildInfo5093472757169252321.properties
13:40:30  	at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:92)
13:40:30  	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:106)
13:40:30  	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
13:40:30  	at java.base/sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:218)
13:40:30  	at java.base/java.nio.file.spi.FileSystemProvider.newOutputStream(FileSystemProvider.java:484)
13:40:30  	at java.base/java.nio.file.Files.newOutputStream(Files.java:228)
13:40:30  	at org.jfrog.hudson.util.ExtractorUtils.savePropertiesToFile(ExtractorUtils.java:598)
13:40:30  Caused: hudson.remoting.ProxyException: java.lang.RuntimeException: java.nio.file.NoSuchFileException: /home/jenkins/workspace/cloud_master@tmp/artifactory/buildInfo5093472757169252321.properties
13:40:30  	at org.jfrog.hudson.util.ExtractorUtils.savePropertiesToFile(ExtractorUtils.java:609)
13:40:30  	at org.jfrog.hudson.util.ExtractorUtils.persistConfiguration(ExtractorUtils.java:577)
13:40:30  	at org.jfrog.hudson.pipeline.common.executors.EnvExtractor.persistConfiguration(EnvExtractor.java:96)
13:40:30  	at org.jfrog.hudson.pipeline.common.executors.EnvExtractor.execute(EnvExtractor.java:75)
13:40:30  Also:   org.jenkinsci.plugins.workflow.actions.ErrorAction$ErrorId: da620d94-0df0-4e90-9806-bc5bbd9bcc83
13:40:30  Caused: hudson.remoting.ProxyException: java.lang.RuntimeException: java.lang.RuntimeException: java.nio.file.NoSuchFileException: /home/jenkins/workspace/cloud_master@tmp/artifactory/buildInfo5093472757169252321.properties
13:40:30  	at org.jfrog.hudson.pipeline.common.executors.EnvExtractor.execute(EnvExtractor.java:77)
13:40:30  	at org.jfrog.hudson.pipeline.common.executors.MavenExecutor.execute(MavenExecutor.java:59)
13:40:30  	at org.jfrog.hudson.pipeline.declarative.steps.maven.MavenStep$Execution.runStep(MavenStep.java:106)
13:40:30  	at org.jfrog.hudson.pipeline.declarative.steps.maven.MavenStep$Execution.runStep(MavenStep.java:91)
13:40:30  	at org.jfrog.hudson.pipeline.ArtifactorySynchronousNonBlockingStepExecution.run(ArtifactorySynchronousNonBlockingStepExecution.java:55)
13:40:30  	at org.jenkinsci.plugins.workflow.steps.SynchronousNonBlockingStepExecution.lambda$start$0(SynchronousNonBlockingStepExecution.java:47)
13:40:30  	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
13:40:30  	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
13:40:30  	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
13:40:30  	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
13:40:30  	at java.base/java.lang.Thread.run(Thread.java:840)
```
**To Reproduce**n such an error occurs
Steps to reproduce the behavior

This part causes an error in the pipeline

```
rtMavenDeployer(
  id: 'MAVEN_DEPLOYER',
  serverId: artifactoryServerId,
  releaseRepo: 'libs-release',
  snapshotRepo: 'libs-snapshot-local',
  excludePatterns: ["${pipelineParams.rtExcludePatterns}"]
)
rtMavenResolver(
  id: 'MAVEN_RESOLVER',
  serverId: artifactoryServerId,
  releaseRepo: 'libs-release',
  snapshotRepo: 'libs-snapshot-local'
)
rtBuildInfo(
  maxBuilds: 100,
  maxDays: 30,
  deleteBuildArtifacts: true,
  captureEnv: true
)

rtMavenRun(
  pom: 'pom.xml',
  goals: "clean versions:set -DnewVersion=${RELEASE_NUMBER}-${BUILD_NUMBER} " +
          '-DprocessAllModules=true -B -ntp',
  resolverId: 'MAVEN_RESOLVER'
)
```

**Expected behavior**

**Screenshots**

**Versions**
- Jenkins Artifactory plugin version: 4.0.1
- Jenkins operating system: 2.426.2
- Artifactory Version: 7.71.8

**Additional context**

**Comment by fraz3alpha** [comment]
This has affected us pretty badly too, so we are in the process of downgrading to `4.0.0` as well.

I see that there were a bunch of changes relating to writing out properties files in https://github.com/jfrog/jenkins-artifactory-plugin/pull/900/files, (specifically [here](https://github.com/jfrog/jenkins-artifactory-plugin/pull/900/files#diff-89608c2f9694c926c61c31fe44ea8ce0b7fe19aa7d787345d030b9d8682d461aL551) where it split the writing of the properties file into two steps,) so I wonder if that is involved in what has broken here

**Comment by yahavi** [comment]
@denis-matchenko @fraz3alpha 
Jenkins Artifactory plugin [4.0.3](https://github.com/jfrog/jenkins-artifactory-plugin/releases/tag/artifactory-4.0.3) has been released. This version includes the fix for this issue.
Feel free to upgrade - we'd appreciate your feedback on that.

**Comment by pjinggithub** [comment]
@yahavi 
do we need restart Jenkins server after upgrade this plug-in?
Thank you for your support
Ping

**Comment by pjinggithub** [comment]
@yahavi  thank you for confirming this.

**Comment by jekkel** [comment]
I am afraid the issue is not fully resolved, see #918 .

**Comment by Or-Geva** [comment]
@pjinggithub & @jekkel Thank you all for reporting this issue, Artifactory Jenkins plugin 4.0.4 has been released, including a fix for this issue.
Feel free to upgrade. We'd appreciate your feedback on that.

**Comment by ChristianGeie** [comment]
i just update to plugin version 4.0.5 and issues out of #918 seems to be fixed. All related agent builds are running as expected.
thx to @Or-Geva for contributing #923
