### ISSUE TITLE
Exception after Upgrading to 4.0.2/4.0.3 -> Malformed \uxxxx encoding

### ISSUE THREAD

**Issue by c-koell** [jfrog/jenkins-artifactory-plugin#913]
**Describe the bug**
After Upgrading to 4.0.2 or 4.0.3 from 4.0.0 we see follewing Stracktace in a Maven Project Job
```
ERROR: Processing failed due to a bug in the code. Please report this to the issue tracker (https://jenkins.io/redirect/report-an-issue).
java.lang.IllegalArgumentException: Malformed \uxxxx encoding.
	at java.base/java.util.Properties.loadConvert(Unknown Source)
	at java.base/java.util.Properties.load0(Unknown Source)
	at java.base/java.util.Properties.load(Unknown Source)
	at org.jfrog.build.extractor.BuildInfoExtractorUtils.searchAdditionalPropertiesFile(BuildInfoExtractorUtils.java:113)
	at org.jfrog.build.extractor.BuildInfoExtractorUtils.mergePropertiesWithSystemAndPropertyFile(BuildInfoExtractorUtils.java:70)
	at org.jfrog.build.extractor.maven.resolver.ResolutionHelper.init(ResolutionHelper.java:31)
	at org.jfrog.build.extractor.maven.resolver.ArtifactoryEclipseResolversHelper.initResolutionHelper(ArtifactoryEclipseResolversHelper.java:67)
	at org.jfrog.build.extractor.maven.resolver.ArtifactoryEclipseResolversHelper.getResolutionRepositories(ArtifactoryEclipseResolversHelper.java:45)
	at org.jfrog.build.extractor.maven.resolver.ArtifactoryEclipseArtifactResolver.enforceResolutionRepositories(ArtifactoryEclipseArtifactResolver.java:36)
	at org.jfrog.build.extractor.maven.resolver.ArtifactoryEclipseArtifactResolver.resolveArtifacts(ArtifactoryEclipseArtifactResolver.java:53)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifact(DefaultArtifactResolver.java:212)
	at org.eclipse.aether.internal.impl.DefaultRepositorySystem.resolveArtifact(DefaultRepositorySystem.java:272)
	at org.apache.maven.project.ProjectModelResolver.resolveModel(ProjectModelResolver.java:192)
	at org.apache.maven.project.ProjectModelResolver.resolveModel(ProjectModelResolver.java:242)
	at org.apache.maven.model.building.DefaultModelBuilder.readParentExternally(DefaultModelBuilder.java:1077)
	at org.apache.maven.model.building.DefaultModelBuilder.readParent(DefaultModelBuilder.java:853)
	at org.apache.maven.model.building.DefaultModelBuilder.build(DefaultModelBuilder.java:344)
	at org.apache.maven.model.building.DefaultModelBuilder.build(DefaultModelBuilder.java:252)
	at org.apache.maven.project.DefaultProjectBuilder.build(DefaultProjectBuilder.java:448)
	at org.apache.maven.project.DefaultProjectBuilder.build(DefaultProjectBuilder.java:414)
	at org.apache.maven.project.DefaultProjectBuilder.build(DefaultProjectBuilder.java:377)
	at org.jfrog.build.extractor.maven.ArtifactoryProjectBuilder.build(ArtifactoryProjectBuilder.java:47)
	at hudson.maven.MavenEmbedder.buildProjects(MavenEmbedder.java:370)
	at hudson.maven.MavenEmbedder.readProjects(MavenEmbedder.java:340)
	at hudson.maven.MavenModuleSetBuild$PomParser.invoke(MavenModuleSetBuild.java:1330)
	at hudson.maven.MavenModuleSetBuild$PomParser.invoke(MavenModuleSetBuild.java:1124)
	at hudson.FilePath.act(FilePath.java:1198)
	at hudson.FilePath.act(FilePath.java:1181)
	at hudson.maven.MavenModuleSetBuild$MavenModuleSetBuildExecution.parsePoms(MavenModuleSetBuild.java:985)
	at hudson.maven.MavenModuleSetBuild$MavenModuleSetBuildExecution.doRun(MavenModuleSetBuild.java:689)
	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:526)
	at hudson.model.Run.execute(Run.java:1895)
	at hudson.maven.MavenModuleSetBuild.run(MavenModuleSetBuild.java:543)
	at hudson.model.ResourceController.execute(ResourceController.java:101)
	at hudson.model.Executor.run(Executor.java:442)
```

**To Reproduce**
Update to latest Plugin Version

**Versions**
- Jenkins Artifactory plugin version: 4.0.3
- Jenkins operating system: Windows Server 2019
- Artifactory Version: 7.71.9

**Comment by Or-Geva** [comment]
@c-koell, thank you for your report. I wasn't able to replicate this issue. Could you please clear the cache for all agents? Additionally, providing more information about your Maven project script would be helpful in gaining a better understanding of the issue.

**Comment by c-koell** [comment]
HI @Or-Geva can you tell me how i clear the cache please ?

What information do you need ? 
The Job is a normal Maven Project Job where we have configured two things regarding artifactory

1. Artifactory Release Management (Enable Artifactory release management)
2. A Post Build Action (Deploy artifacts to Artifactory) to deploy the artifacts to our artifactory

**Comment by Or-Geva** [comment]
@c-koell, navigate to the workspace directory inside the Jenkins home directory. You will find the cache for all your agents there. Remove the directory related to the Maven Project agent and then restart the job.
Is both the master and the agent operating on a Windows environment?

Moreover, we strongly recommend switching over from the old Jenkins Artifactory Plugin to the new next-gen [Jenkins JFrog Plugin](https://docs.jfrog-applications.jfrog.io/ci-and-sdks/ci-integrations/jenkins-jfrog-plugin?_gl=1*1o6wryb*_ga*MTk5MDc2ODczOS4xNzA1NjQ4NjY3*_ga_SQ1NR9VTFJ*MTcwNTY0ODY2Ny4xLjAuMTcwNTY0ODY2Ny4wLjAuMA..*_fplc*Tm1jYnF4dHNzS0slMkYxcUEyV0oyNGhMSnRNSXBmNWFWWTJ6SE9qUnVmM2lWZ1FZMGt0Y2VYNU1oTVVsaTRSUzF0SUl4anZjQzRCNlpxUWwxMU5uc3NVMHVqaXVCUTY0MXYwVEZpdTdkZ0l6ak5JeWtGQ3MxTlVzZ1k2ejE5RWclM0QlM0Q.) to avoid issues.

**Comment by c-koell** [comment]
The master and one agent are both on Windows .. yes
I will try to clear the cache next week.

Okay but i think it is not so easy to switch to the new plugin :-) we have a lot of jobs ...

**Comment by c-koell** [comment]
I have cleared all the folders under d:\Jenkins\cache\artifactory-plugin and now it works :-)

**Comment by rzo1** [comment]
It also happens for us from time to time (even if we clear the build caches). Moving to the "new" plugin isn't an option because we are not using pipeline jobs (yet) and it doesn't seem to work with "normal" Maven jobs on Jenkins.

**Comment by wborn** [comment]
This issue should be reopened because it's still happening for us after clearing the cache when using the Artifactory Plug-in 4.0.8.

See: https://ci.openhab.org/job/openHAB-Addons/1451/console

**Comment by wborn** [comment]
I had a look at the code and it looks like this `IllegalArgumentException` is missing from the catch in [BuildInfoExtractorUtils#searchAdditionalPropertiesFile](https://github.com/jfrog/build-info/blob/b82ee0627bd002fc987e85898d3ba48f950a6366/build-info-extractor/src/main/java/org/jfrog/build/extractor/BuildInfoExtractorUtils.java#L116-L119). Haven't checked if it would then properly handle the thrown `RuntimeException`. But adding the `IllegalArgumentException` to the catch would help a lot with identifying what file is causing the exceptions.

**Comment by rzo1** [comment]
@eyalbe4 Can we re-open this issue please? It isn't gone and we should just fix it as proposed by @wborn or by myself (ignore the exception). Any thoughts on this? Shall we just provide a PR so it gets included? 

This is really annoying and appears from time to time.

**Comment by wborn** [comment]
Seems like Aether resolves metadata using multiple threads. So it could be one thread is reading the file while another thread is still writing the file ([MRESOLVER-216](https://issues.apache.org/jira/browse/MRESOLVER-216)).

I've now added `-Daether.metadataResolver.threads=1` which may help. See [Artifact Resolver Configuration Options](https://maven.apache.org/resolver/configuration.html).

**Comment by rzo1** [comment]
We deployed a patched version locally, so if it happens again, we have the Stacktrace for the IllegalArgumentException, i.e. the file producing it.
